package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA



/**
 * AqDefAqerrorF generated by hbm2java
 */
public class AqDefAqerrorF  implements java.io.Serializable {


     private AqDefAqerrorFId id;

    

    
   
    public AqDefAqerrorFId getId() {
        return this.id;
    }
    
    public void setId(AqDefAqerrorFId id) {
        this.id = id;
    }




}


