package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA



/**
 * AqdefAqerror generated by hbm2java
 */
public class AqdefAqerror  implements java.io.Serializable {


     private AqdefAqerrorId id;

    

    
   
    public AqdefAqerrorId getId() {
        return this.id;
    }
    
    public void setId(AqdefAqerrorId id) {
        this.id = id;
    }




}


