package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA



/**
 * AqDefAqcallF generated by hbm2java
 */
public class AqDefAqcallF  implements java.io.Serializable {


     private AqDefAqcallFId id;

    

    
   
    public AqDefAqcallFId getId() {
        return this.id;
    }
    
    public void setId(AqDefAqcallFId id) {
        this.id = id;
    }




}


