package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Arrays;
import java.util.Date;

/**
 * AqDefAqerrorFId generated by hbm2java
 */
public class AqDefAqerrorFId  implements java.io.Serializable {


     private String QName;
     private Date rowId;
     private byte[] msgid;
     private String corrid;
     private BigDecimal priority;
     private BigDecimal state;
     private Date delay;
     private BigDecimal expiration;
     private Date enqTime;
     private BigDecimal enqUid;
     private String enqTid;
     private Date deqTime;
     private BigDecimal deqUid;
     private String deqTid;
     private BigDecimal retryCount;
     private String exceptionQschema;
     private String exceptionQueue;
     private BigDecimal cscn;
     private BigDecimal dscn;
     private BigDecimal chainNo;
     private BigDecimal localOrderNo;
     private Date timeManagerInfo;
     private BigDecimal stepNo;
     private Blob userData;
     private BigDecimal queueId;

    

	
    
    
   
    public String getQName() {
        return this.QName;
    }
    
    public void setQName(String QName) {
        this.QName = QName;
    }
    public Date getRowId() {
        return this.rowId;
    }
    
    public void setRowId(Date rowId) {
        this.rowId = rowId;
    }
    public byte[] getMsgid() {
        return this.msgid;
    }
    
    public void setMsgid(byte[] msgid) {
        this.msgid = msgid;
    }
    public String getCorrid() {
        return this.corrid;
    }
    
    public void setCorrid(String corrid) {
        this.corrid = corrid;
    }
    public BigDecimal getPriority() {
        return this.priority;
    }
    
    public void setPriority(BigDecimal priority) {
        this.priority = priority;
    }
    public BigDecimal getState() {
        return this.state;
    }
    
    public void setState(BigDecimal state) {
        this.state = state;
    }
    public Date getDelay() {
        return this.delay;
    }
    
    public void setDelay(Date delay) {
        this.delay = delay;
    }
    public BigDecimal getExpiration() {
        return this.expiration;
    }
    
    public void setExpiration(BigDecimal expiration) {
        this.expiration = expiration;
    }
    public Date getEnqTime() {
        return this.enqTime;
    }
    
    public void setEnqTime(Date enqTime) {
        this.enqTime = enqTime;
    }
    public BigDecimal getEnqUid() {
        return this.enqUid;
    }
    
    public void setEnqUid(BigDecimal enqUid) {
        this.enqUid = enqUid;
    }
    public String getEnqTid() {
        return this.enqTid;
    }
    
    public void setEnqTid(String enqTid) {
        this.enqTid = enqTid;
    }
    public Date getDeqTime() {
        return this.deqTime;
    }
    
    public void setDeqTime(Date deqTime) {
        this.deqTime = deqTime;
    }
    public BigDecimal getDeqUid() {
        return this.deqUid;
    }
    
    public void setDeqUid(BigDecimal deqUid) {
        this.deqUid = deqUid;
    }
    public String getDeqTid() {
        return this.deqTid;
    }
    
    public void setDeqTid(String deqTid) {
        this.deqTid = deqTid;
    }
    public BigDecimal getRetryCount() {
        return this.retryCount;
    }
    
    public void setRetryCount(BigDecimal retryCount) {
        this.retryCount = retryCount;
    }
    public String getExceptionQschema() {
        return this.exceptionQschema;
    }
    
    public void setExceptionQschema(String exceptionQschema) {
        this.exceptionQschema = exceptionQschema;
    }
    public String getExceptionQueue() {
        return this.exceptionQueue;
    }
    
    public void setExceptionQueue(String exceptionQueue) {
        this.exceptionQueue = exceptionQueue;
    }
    public BigDecimal getCscn() {
        return this.cscn;
    }
    
    public void setCscn(BigDecimal cscn) {
        this.cscn = cscn;
    }
    public BigDecimal getDscn() {
        return this.dscn;
    }
    
    public void setDscn(BigDecimal dscn) {
        this.dscn = dscn;
    }
    public BigDecimal getChainNo() {
        return this.chainNo;
    }
    
    public void setChainNo(BigDecimal chainNo) {
        this.chainNo = chainNo;
    }
    public BigDecimal getLocalOrderNo() {
        return this.localOrderNo;
    }
    
    public void setLocalOrderNo(BigDecimal localOrderNo) {
        this.localOrderNo = localOrderNo;
    }
    public Date getTimeManagerInfo() {
        return this.timeManagerInfo;
    }
    
    public void setTimeManagerInfo(Date timeManagerInfo) {
        this.timeManagerInfo = timeManagerInfo;
    }
    public BigDecimal getStepNo() {
        return this.stepNo;
    }
    
    public void setStepNo(BigDecimal stepNo) {
        this.stepNo = stepNo;
    }
    public Blob getUserData() {
        return this.userData;
    }
    
    public void setUserData(Blob userData) {
        this.userData = userData;
    }
    public BigDecimal getQueueId() {
        return this.queueId;
    }
    
    public void setQueueId(BigDecimal queueId) {
        this.queueId = queueId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AqDefAqerrorFId) ) return false;
		 AqDefAqerrorFId castOther = ( AqDefAqerrorFId ) other; 
         
		 return ( (this.getQName()==castOther.getQName()) || ( this.getQName()!=null && castOther.getQName()!=null && this.getQName().equals(castOther.getQName()) ) )
 && ( (this.getRowId()==castOther.getRowId()) || ( this.getRowId()!=null && castOther.getRowId()!=null && this.getRowId().equals(castOther.getRowId()) ) )
 && ( (this.getMsgid()==castOther.getMsgid()) || ( this.getMsgid()!=null && castOther.getMsgid()!=null && Arrays.equals(this.getMsgid(), castOther.getMsgid()) ) )
 && ( (this.getCorrid()==castOther.getCorrid()) || ( this.getCorrid()!=null && castOther.getCorrid()!=null && this.getCorrid().equals(castOther.getCorrid()) ) )
 && ( (this.getPriority()==castOther.getPriority()) || ( this.getPriority()!=null && castOther.getPriority()!=null && this.getPriority().equals(castOther.getPriority()) ) )
 && ( (this.getState()==castOther.getState()) || ( this.getState()!=null && castOther.getState()!=null && this.getState().equals(castOther.getState()) ) )
 && ( (this.getDelay()==castOther.getDelay()) || ( this.getDelay()!=null && castOther.getDelay()!=null && this.getDelay().equals(castOther.getDelay()) ) )
 && ( (this.getExpiration()==castOther.getExpiration()) || ( this.getExpiration()!=null && castOther.getExpiration()!=null && this.getExpiration().equals(castOther.getExpiration()) ) )
 && ( (this.getEnqTime()==castOther.getEnqTime()) || ( this.getEnqTime()!=null && castOther.getEnqTime()!=null && this.getEnqTime().equals(castOther.getEnqTime()) ) )
 && ( (this.getEnqUid()==castOther.getEnqUid()) || ( this.getEnqUid()!=null && castOther.getEnqUid()!=null && this.getEnqUid().equals(castOther.getEnqUid()) ) )
 && ( (this.getEnqTid()==castOther.getEnqTid()) || ( this.getEnqTid()!=null && castOther.getEnqTid()!=null && this.getEnqTid().equals(castOther.getEnqTid()) ) )
 && ( (this.getDeqTime()==castOther.getDeqTime()) || ( this.getDeqTime()!=null && castOther.getDeqTime()!=null && this.getDeqTime().equals(castOther.getDeqTime()) ) )
 && ( (this.getDeqUid()==castOther.getDeqUid()) || ( this.getDeqUid()!=null && castOther.getDeqUid()!=null && this.getDeqUid().equals(castOther.getDeqUid()) ) )
 && ( (this.getDeqTid()==castOther.getDeqTid()) || ( this.getDeqTid()!=null && castOther.getDeqTid()!=null && this.getDeqTid().equals(castOther.getDeqTid()) ) )
 && ( (this.getRetryCount()==castOther.getRetryCount()) || ( this.getRetryCount()!=null && castOther.getRetryCount()!=null && this.getRetryCount().equals(castOther.getRetryCount()) ) )
 && ( (this.getExceptionQschema()==castOther.getExceptionQschema()) || ( this.getExceptionQschema()!=null && castOther.getExceptionQschema()!=null && this.getExceptionQschema().equals(castOther.getExceptionQschema()) ) )
 && ( (this.getExceptionQueue()==castOther.getExceptionQueue()) || ( this.getExceptionQueue()!=null && castOther.getExceptionQueue()!=null && this.getExceptionQueue().equals(castOther.getExceptionQueue()) ) )
 && ( (this.getCscn()==castOther.getCscn()) || ( this.getCscn()!=null && castOther.getCscn()!=null && this.getCscn().equals(castOther.getCscn()) ) )
 && ( (this.getDscn()==castOther.getDscn()) || ( this.getDscn()!=null && castOther.getDscn()!=null && this.getDscn().equals(castOther.getDscn()) ) )
 && ( (this.getChainNo()==castOther.getChainNo()) || ( this.getChainNo()!=null && castOther.getChainNo()!=null && this.getChainNo().equals(castOther.getChainNo()) ) )
 && ( (this.getLocalOrderNo()==castOther.getLocalOrderNo()) || ( this.getLocalOrderNo()!=null && castOther.getLocalOrderNo()!=null && this.getLocalOrderNo().equals(castOther.getLocalOrderNo()) ) )
 && ( (this.getTimeManagerInfo()==castOther.getTimeManagerInfo()) || ( this.getTimeManagerInfo()!=null && castOther.getTimeManagerInfo()!=null && this.getTimeManagerInfo().equals(castOther.getTimeManagerInfo()) ) )
 && ( (this.getStepNo()==castOther.getStepNo()) || ( this.getStepNo()!=null && castOther.getStepNo()!=null && this.getStepNo().equals(castOther.getStepNo()) ) )
 && ( (this.getUserData()==castOther.getUserData()) || ( this.getUserData()!=null && castOther.getUserData()!=null && this.getUserData().equals(castOther.getUserData()) ) )
 && ( (this.getQueueId()==castOther.getQueueId()) || ( this.getQueueId()!=null && castOther.getQueueId()!=null && this.getQueueId().equals(castOther.getQueueId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getQName() == null ? 0 : this.getQName().hashCode() );
         result = 37 * result + ( getRowId() == null ? 0 : this.getRowId().hashCode() );
         int msgidHashcode = 0;
         byte[] msgidProperty = this.getMsgid();
         if(msgidProperty != null) {
             msgidHashcode = 1;
             for (int i=0; i<msgidProperty.length; i++) {
                 msgidHashcode = 37 * msgidHashcode + msgidProperty[i];
             }
         }

         result = 37 * result + msgidHashcode;

         result = 37 * result + ( getCorrid() == null ? 0 : this.getCorrid().hashCode() );
         result = 37 * result + ( getPriority() == null ? 0 : this.getPriority().hashCode() );
         result = 37 * result + ( getState() == null ? 0 : this.getState().hashCode() );
         result = 37 * result + ( getDelay() == null ? 0 : this.getDelay().hashCode() );
         result = 37 * result + ( getExpiration() == null ? 0 : this.getExpiration().hashCode() );
         result = 37 * result + ( getEnqTime() == null ? 0 : this.getEnqTime().hashCode() );
         result = 37 * result + ( getEnqUid() == null ? 0 : this.getEnqUid().hashCode() );
         result = 37 * result + ( getEnqTid() == null ? 0 : this.getEnqTid().hashCode() );
         result = 37 * result + ( getDeqTime() == null ? 0 : this.getDeqTime().hashCode() );
         result = 37 * result + ( getDeqUid() == null ? 0 : this.getDeqUid().hashCode() );
         result = 37 * result + ( getDeqTid() == null ? 0 : this.getDeqTid().hashCode() );
         result = 37 * result + ( getRetryCount() == null ? 0 : this.getRetryCount().hashCode() );
         result = 37 * result + ( getExceptionQschema() == null ? 0 : this.getExceptionQschema().hashCode() );
         result = 37 * result + ( getExceptionQueue() == null ? 0 : this.getExceptionQueue().hashCode() );
         result = 37 * result + ( getCscn() == null ? 0 : this.getCscn().hashCode() );
         result = 37 * result + ( getDscn() == null ? 0 : this.getDscn().hashCode() );
         result = 37 * result + ( getChainNo() == null ? 0 : this.getChainNo().hashCode() );
         result = 37 * result + ( getLocalOrderNo() == null ? 0 : this.getLocalOrderNo().hashCode() );
         result = 37 * result + ( getTimeManagerInfo() == null ? 0 : this.getTimeManagerInfo().hashCode() );
         result = 37 * result + ( getStepNo() == null ? 0 : this.getStepNo().hashCode() );
         result = 37 * result + ( getUserData() == null ? 0 : this.getUserData().hashCode() );
         result = 37 * result + ( getQueueId() == null ? 0 : this.getQueueId().hashCode() );
         return result;
   }   


}


