package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA



/**
 * AqInternetAgentPrivs generated by hbm2java
 */
public class AqInternetAgentPrivs  implements java.io.Serializable {


     private AqInternetAgentPrivsId id;
     private AqInternetAgents aqInternetAgents;

    

    
   
    public AqInternetAgentPrivsId getId() {
        return this.id;
    }
    
    public void setId(AqInternetAgentPrivsId id) {
        this.id = id;
    }
    public AqInternetAgents getAqInternetAgents() {
        return this.aqInternetAgents;
    }
    
    public void setAqInternetAgents(AqInternetAgents aqInternetAgents) {
        this.aqInternetAgents = aqInternetAgents;
    }




}


