package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * AqInternetAgents generated by hbm2java
 */
public class AqInternetAgents  implements java.io.Serializable {


     private String agentName;
     private BigDecimal protocol;
     private String spare1;
     private Set aqInternetAgentPrivses = new HashSet(0);

    

	
    
    
   
    public String getAgentName() {
        return this.agentName;
    }
    
    public void setAgentName(String agentName) {
        this.agentName = agentName;
    }
    public BigDecimal getProtocol() {
        return this.protocol;
    }
    
    public void setProtocol(BigDecimal protocol) {
        this.protocol = protocol;
    }
    public String getSpare1() {
        return this.spare1;
    }
    
    public void setSpare1(String spare1) {
        this.spare1 = spare1;
    }
    public Set getAqInternetAgentPrivses() {
        return this.aqInternetAgentPrivses;
    }
    
    public void setAqInternetAgentPrivses(Set aqInternetAgentPrivses) {
        this.aqInternetAgentPrivses = aqInternetAgentPrivses;
    }




}


