package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * AqSchedules generated by hbm2java
 */
public class AqSchedules  implements java.io.Serializable {


     private AqSchedulesId id;
     private Date startTime;
     private String duration;
     private String nextTime;
     private String latency;
     private Date lastTime;
     private BigDecimal jobno;

    

	
    
    
   
    public AqSchedulesId getId() {
        return this.id;
    }
    
    public void setId(AqSchedulesId id) {
        this.id = id;
    }
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    public String getDuration() {
        return this.duration;
    }
    
    public void setDuration(String duration) {
        this.duration = duration;
    }
    public String getNextTime() {
        return this.nextTime;
    }
    
    public void setNextTime(String nextTime) {
        this.nextTime = nextTime;
    }
    public String getLatency() {
        return this.latency;
    }
    
    public void setLatency(String latency) {
        this.latency = latency;
    }
    public Date getLastTime() {
        return this.lastTime;
    }
    
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }
    public BigDecimal getJobno() {
        return this.jobno;
    }
    
    public void setJobno(BigDecimal jobno) {
        this.jobno = jobno;
    }




}


