package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;

/**
 * DefAqerror generated by hbm2java
 */
public class DefAqerror  implements java.io.Serializable {


     private DefAqerrorId id;
     private String QName;
     private byte[] msgid;
     private String corrid;
     private BigDecimal priority;
     private BigDecimal state;
     private Date delay;
     private BigDecimal expiration;
     private Date timeManagerInfo;
     private BigDecimal localOrderNo;
     private BigDecimal chainNo;
     private BigDecimal cscn;
     private BigDecimal dscn;
     private Date enqTime;
     private BigDecimal enqUid;
     private Date deqTime;
     private BigDecimal deqUid;
     private String deqTid;
     private BigDecimal retryCount;
     private String exceptionQschema;
     private String exceptionQueue;
     private BigDecimal recipientKey;
     private byte[] dequeueMsgid;
     private Blob userData;

    

	
    
    
   
    public DefAqerrorId getId() {
        return this.id;
    }
    
    public void setId(DefAqerrorId id) {
        this.id = id;
    }
    public String getQName() {
        return this.QName;
    }
    
    public void setQName(String QName) {
        this.QName = QName;
    }
    public byte[] getMsgid() {
        return this.msgid;
    }
    
    public void setMsgid(byte[] msgid) {
        this.msgid = msgid;
    }
    public String getCorrid() {
        return this.corrid;
    }
    
    public void setCorrid(String corrid) {
        this.corrid = corrid;
    }
    public BigDecimal getPriority() {
        return this.priority;
    }
    
    public void setPriority(BigDecimal priority) {
        this.priority = priority;
    }
    public BigDecimal getState() {
        return this.state;
    }
    
    public void setState(BigDecimal state) {
        this.state = state;
    }
    public Date getDelay() {
        return this.delay;
    }
    
    public void setDelay(Date delay) {
        this.delay = delay;
    }
    public BigDecimal getExpiration() {
        return this.expiration;
    }
    
    public void setExpiration(BigDecimal expiration) {
        this.expiration = expiration;
    }
    public Date getTimeManagerInfo() {
        return this.timeManagerInfo;
    }
    
    public void setTimeManagerInfo(Date timeManagerInfo) {
        this.timeManagerInfo = timeManagerInfo;
    }
    public BigDecimal getLocalOrderNo() {
        return this.localOrderNo;
    }
    
    public void setLocalOrderNo(BigDecimal localOrderNo) {
        this.localOrderNo = localOrderNo;
    }
    public BigDecimal getChainNo() {
        return this.chainNo;
    }
    
    public void setChainNo(BigDecimal chainNo) {
        this.chainNo = chainNo;
    }
    public BigDecimal getCscn() {
        return this.cscn;
    }
    
    public void setCscn(BigDecimal cscn) {
        this.cscn = cscn;
    }
    public BigDecimal getDscn() {
        return this.dscn;
    }
    
    public void setDscn(BigDecimal dscn) {
        this.dscn = dscn;
    }
    public Date getEnqTime() {
        return this.enqTime;
    }
    
    public void setEnqTime(Date enqTime) {
        this.enqTime = enqTime;
    }
    public BigDecimal getEnqUid() {
        return this.enqUid;
    }
    
    public void setEnqUid(BigDecimal enqUid) {
        this.enqUid = enqUid;
    }
    public Date getDeqTime() {
        return this.deqTime;
    }
    
    public void setDeqTime(Date deqTime) {
        this.deqTime = deqTime;
    }
    public BigDecimal getDeqUid() {
        return this.deqUid;
    }
    
    public void setDeqUid(BigDecimal deqUid) {
        this.deqUid = deqUid;
    }
    public String getDeqTid() {
        return this.deqTid;
    }
    
    public void setDeqTid(String deqTid) {
        this.deqTid = deqTid;
    }
    public BigDecimal getRetryCount() {
        return this.retryCount;
    }
    
    public void setRetryCount(BigDecimal retryCount) {
        this.retryCount = retryCount;
    }
    public String getExceptionQschema() {
        return this.exceptionQschema;
    }
    
    public void setExceptionQschema(String exceptionQschema) {
        this.exceptionQschema = exceptionQschema;
    }
    public String getExceptionQueue() {
        return this.exceptionQueue;
    }
    
    public void setExceptionQueue(String exceptionQueue) {
        this.exceptionQueue = exceptionQueue;
    }
    public BigDecimal getRecipientKey() {
        return this.recipientKey;
    }
    
    public void setRecipientKey(BigDecimal recipientKey) {
        this.recipientKey = recipientKey;
    }
    public byte[] getDequeueMsgid() {
        return this.dequeueMsgid;
    }
    
    public void setDequeueMsgid(byte[] dequeueMsgid) {
        this.dequeueMsgid = dequeueMsgid;
    }
    public Blob getUserData() {
        return this.userData;
    }
    
    public void setUserData(Blob userData) {
        this.userData = userData;
    }




}


