package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * DefCalldestId generated by hbm2java
 */
public class DefCalldestId  implements java.io.Serializable {


     private String enqTid;
     private String dblink;
     private BigDecimal stepNo;

    

    
   
    public String getEnqTid() {
        return this.enqTid;
    }
    
    public void setEnqTid(String enqTid) {
        this.enqTid = enqTid;
    }
    public String getDblink() {
        return this.dblink;
    }
    
    public void setDblink(String dblink) {
        this.dblink = dblink;
    }
    public BigDecimal getStepNo() {
        return this.stepNo;
    }
    
    public void setStepNo(BigDecimal stepNo) {
        this.stepNo = stepNo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DefCalldestId) ) return false;
		 DefCalldestId castOther = ( DefCalldestId ) other; 
         
		 return ( (this.getEnqTid()==castOther.getEnqTid()) || ( this.getEnqTid()!=null && castOther.getEnqTid()!=null && this.getEnqTid().equals(castOther.getEnqTid()) ) )
 && ( (this.getDblink()==castOther.getDblink()) || ( this.getDblink()!=null && castOther.getDblink()!=null && this.getDblink().equals(castOther.getDblink()) ) )
 && ( (this.getStepNo()==castOther.getStepNo()) || ( this.getStepNo()!=null && castOther.getStepNo()!=null && this.getStepNo().equals(castOther.getStepNo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEnqTid() == null ? 0 : this.getEnqTid().hashCode() );
         result = 37 * result + ( getDblink() == null ? 0 : this.getDblink().hashCode() );
         result = 37 * result + ( getStepNo() == null ? 0 : this.getStepNo().hashCode() );
         return result;
   }   


}


