package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.util.Arrays;

/**
 * DefDestinationId generated by hbm2java
 */
public class DefDestinationId  implements java.io.Serializable {


     private String dblink;
     private byte[] catchup;

    

    
   
    public String getDblink() {
        return this.dblink;
    }
    
    public void setDblink(String dblink) {
        this.dblink = dblink;
    }
    public byte[] getCatchup() {
        return this.catchup;
    }
    
    public void setCatchup(byte[] catchup) {
        this.catchup = catchup;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DefDestinationId) ) return false;
		 DefDestinationId castOther = ( DefDestinationId ) other; 
         
		 return ( (this.getDblink()==castOther.getDblink()) || ( this.getDblink()!=null && castOther.getDblink()!=null && this.getDblink().equals(castOther.getDblink()) ) )
 && ( (this.getCatchup()==castOther.getCatchup()) || ( this.getCatchup()!=null && castOther.getCatchup()!=null && Arrays.equals(this.getCatchup(), castOther.getCatchup()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDblink() == null ? 0 : this.getDblink().hashCode() );
         int catchupHashcode = 0;
         byte[] catchupProperty = this.getCatchup();
         if(catchupProperty != null) {
             catchupHashcode = 1;
             for (int i=0; i<catchupProperty.length; i++) {
                 catchupHashcode = 37 * catchupHashcode + catchupProperty[i];
             }
         }

         result = 37 * result + catchupHashcode;

         return result;
   }   


}


