package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * DefDestination generated by hbm2java
 */
public class DefDestination  implements java.io.Serializable {


     private DefDestinationId id;
     private BigDecimal lastDelivered;
     private String lastEnqTid;
     private BigDecimal lastSeq;
     private String disabled;
     private BigDecimal job;
     private BigDecimal lastTxnCount;
     private BigDecimal lastErrorNumber;
     private String lastErrorMessage;
     private String applyInit;
     private String alternate;
     private BigDecimal totalTxnCount;
     private BigDecimal totalPropTimeThroughput;
     private BigDecimal totalPropTimeLatency;
     private BigDecimal toCommunicationSize;
     private BigDecimal fromCommunicationSize;
     private byte[] flag;
     private BigDecimal spare1;
     private BigDecimal spare2;
     private BigDecimal spare3;
     private BigDecimal spare4;
     private Set repcatRepschemas = new HashSet(0);
     private Set defCalldests = new HashSet(0);

    

	
    
    
   
    public DefDestinationId getId() {
        return this.id;
    }
    
    public void setId(DefDestinationId id) {
        this.id = id;
    }
    public BigDecimal getLastDelivered() {
        return this.lastDelivered;
    }
    
    public void setLastDelivered(BigDecimal lastDelivered) {
        this.lastDelivered = lastDelivered;
    }
    public String getLastEnqTid() {
        return this.lastEnqTid;
    }
    
    public void setLastEnqTid(String lastEnqTid) {
        this.lastEnqTid = lastEnqTid;
    }
    public BigDecimal getLastSeq() {
        return this.lastSeq;
    }
    
    public void setLastSeq(BigDecimal lastSeq) {
        this.lastSeq = lastSeq;
    }
    public String getDisabled() {
        return this.disabled;
    }
    
    public void setDisabled(String disabled) {
        this.disabled = disabled;
    }
    public BigDecimal getJob() {
        return this.job;
    }
    
    public void setJob(BigDecimal job) {
        this.job = job;
    }
    public BigDecimal getLastTxnCount() {
        return this.lastTxnCount;
    }
    
    public void setLastTxnCount(BigDecimal lastTxnCount) {
        this.lastTxnCount = lastTxnCount;
    }
    public BigDecimal getLastErrorNumber() {
        return this.lastErrorNumber;
    }
    
    public void setLastErrorNumber(BigDecimal lastErrorNumber) {
        this.lastErrorNumber = lastErrorNumber;
    }
    public String getLastErrorMessage() {
        return this.lastErrorMessage;
    }
    
    public void setLastErrorMessage(String lastErrorMessage) {
        this.lastErrorMessage = lastErrorMessage;
    }
    public String getApplyInit() {
        return this.applyInit;
    }
    
    public void setApplyInit(String applyInit) {
        this.applyInit = applyInit;
    }
    public String getAlternate() {
        return this.alternate;
    }
    
    public void setAlternate(String alternate) {
        this.alternate = alternate;
    }
    public BigDecimal getTotalTxnCount() {
        return this.totalTxnCount;
    }
    
    public void setTotalTxnCount(BigDecimal totalTxnCount) {
        this.totalTxnCount = totalTxnCount;
    }
    public BigDecimal getTotalPropTimeThroughput() {
        return this.totalPropTimeThroughput;
    }
    
    public void setTotalPropTimeThroughput(BigDecimal totalPropTimeThroughput) {
        this.totalPropTimeThroughput = totalPropTimeThroughput;
    }
    public BigDecimal getTotalPropTimeLatency() {
        return this.totalPropTimeLatency;
    }
    
    public void setTotalPropTimeLatency(BigDecimal totalPropTimeLatency) {
        this.totalPropTimeLatency = totalPropTimeLatency;
    }
    public BigDecimal getToCommunicationSize() {
        return this.toCommunicationSize;
    }
    
    public void setToCommunicationSize(BigDecimal toCommunicationSize) {
        this.toCommunicationSize = toCommunicationSize;
    }
    public BigDecimal getFromCommunicationSize() {
        return this.fromCommunicationSize;
    }
    
    public void setFromCommunicationSize(BigDecimal fromCommunicationSize) {
        this.fromCommunicationSize = fromCommunicationSize;
    }
    public byte[] getFlag() {
        return this.flag;
    }
    
    public void setFlag(byte[] flag) {
        this.flag = flag;
    }
    public BigDecimal getSpare1() {
        return this.spare1;
    }
    
    public void setSpare1(BigDecimal spare1) {
        this.spare1 = spare1;
    }
    public BigDecimal getSpare2() {
        return this.spare2;
    }
    
    public void setSpare2(BigDecimal spare2) {
        this.spare2 = spare2;
    }
    public BigDecimal getSpare3() {
        return this.spare3;
    }
    
    public void setSpare3(BigDecimal spare3) {
        this.spare3 = spare3;
    }
    public BigDecimal getSpare4() {
        return this.spare4;
    }
    
    public void setSpare4(BigDecimal spare4) {
        this.spare4 = spare4;
    }
    public Set getRepcatRepschemas() {
        return this.repcatRepschemas;
    }
    
    public void setRepcatRepschemas(Set repcatRepschemas) {
        this.repcatRepschemas = repcatRepschemas;
    }
    public Set getDefCalldests() {
        return this.defCalldests;
    }
    
    public void setDefCalldests(Set defCalldests) {
        this.defCalldests = defCalldests;
    }




}


