package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * DefError generated by hbm2java
 */
public class DefError  implements java.io.Serializable {


     private String enqTid;
     private String originTranDb;
     private String originEnqTid;
     private String destination;
     private BigDecimal stepNo;
     private BigDecimal receiver;
     private Date enqTime;
     private BigDecimal errorNumber;
     private String errorMsg;

    

	
    
    
   
    public String getEnqTid() {
        return this.enqTid;
    }
    
    public void setEnqTid(String enqTid) {
        this.enqTid = enqTid;
    }
    public String getOriginTranDb() {
        return this.originTranDb;
    }
    
    public void setOriginTranDb(String originTranDb) {
        this.originTranDb = originTranDb;
    }
    public String getOriginEnqTid() {
        return this.originEnqTid;
    }
    
    public void setOriginEnqTid(String originEnqTid) {
        this.originEnqTid = originEnqTid;
    }
    public String getDestination() {
        return this.destination;
    }
    
    public void setDestination(String destination) {
        this.destination = destination;
    }
    public BigDecimal getStepNo() {
        return this.stepNo;
    }
    
    public void setStepNo(BigDecimal stepNo) {
        this.stepNo = stepNo;
    }
    public BigDecimal getReceiver() {
        return this.receiver;
    }
    
    public void setReceiver(BigDecimal receiver) {
        this.receiver = receiver;
    }
    public Date getEnqTime() {
        return this.enqTime;
    }
    
    public void setEnqTime(Date enqTime) {
        this.enqTime = enqTime;
    }
    public BigDecimal getErrorNumber() {
        return this.errorNumber;
    }
    
    public void setErrorNumber(BigDecimal errorNumber) {
        this.errorNumber = errorNumber;
    }
    public String getErrorMsg() {
        return this.errorMsg;
    }
    
    public void setErrorMsg(String errorMsg) {
        this.errorMsg = errorMsg;
    }




}


