package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA



/**
 * DefOrigin generated by hbm2java
 */
public class DefOrigin  implements java.io.Serializable {


     private DefOriginId id;

    

    
   
    public DefOriginId getId() {
        return this.id;
    }
    
    public void setId(DefOriginId id) {
        this.id = id;
    }




}


