package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * DefPushedTransactions generated by hbm2java
 */
public class DefPushedTransactions  implements java.io.Serializable {


     private BigDecimal sourceSiteId;
     private BigDecimal lastTranId;
     private String disabled;
     private String sourceSite;

    

	
    
    
   
    public BigDecimal getSourceSiteId() {
        return this.sourceSiteId;
    }
    
    public void setSourceSiteId(BigDecimal sourceSiteId) {
        this.sourceSiteId = sourceSiteId;
    }
    public BigDecimal getLastTranId() {
        return this.lastTranId;
    }
    
    public void setLastTranId(BigDecimal lastTranId) {
        this.lastTranId = lastTranId;
    }
    public String getDisabled() {
        return this.disabled;
    }
    
    public void setDisabled(String disabled) {
        this.disabled = disabled;
    }
    public String getSourceSite() {
        return this.sourceSite;
    }
    
    public void setSourceSite(String sourceSite) {
        this.sourceSite = sourceSite;
    }




}


