package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA



/**
 * Help generated by hbm2java
 */
public class Help  implements java.io.Serializable {


     private HelpId id;
     private String info;

    

	
    
    
   
    public HelpId getId() {
        return this.id;
    }
    
    public void setId(HelpId id) {
        this.id = id;
    }
    public String getInfo() {
        return this.info;
    }
    
    public void setInfo(String info) {
        this.info = info;
    }




}


