package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * LogmnrObj generated by hbm2java
 */
public class LogmnrObj  implements java.io.Serializable {


     private LogmnrObjId id;
     private BigDecimal objv_;
     private BigDecimal owner_;
     private String name;
     private BigDecimal namespace;
     private String subname;
     private BigDecimal type_;
     private byte[] oid;
     private String remoteowner;
     private String linkname;
     private BigDecimal flags;
     private BigDecimal spare3;
     private Date stime;
     private BigDecimal logmnrFlags;
     private BigDecimal startScnbas;
     private BigDecimal startScnwrp;

    

	
    
    
   
    public LogmnrObjId getId() {
        return this.id;
    }
    
    public void setId(LogmnrObjId id) {
        this.id = id;
    }
    public BigDecimal getObjv_() {
        return this.objv_;
    }
    
    public void setObjv_(BigDecimal objv_) {
        this.objv_ = objv_;
    }
    public BigDecimal getOwner_() {
        return this.owner_;
    }
    
    public void setOwner_(BigDecimal owner_) {
        this.owner_ = owner_;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public BigDecimal getNamespace() {
        return this.namespace;
    }
    
    public void setNamespace(BigDecimal namespace) {
        this.namespace = namespace;
    }
    public String getSubname() {
        return this.subname;
    }
    
    public void setSubname(String subname) {
        this.subname = subname;
    }
    public BigDecimal getType_() {
        return this.type_;
    }
    
    public void setType_(BigDecimal type_) {
        this.type_ = type_;
    }
    public byte[] getOid() {
        return this.oid;
    }
    
    public void setOid(byte[] oid) {
        this.oid = oid;
    }
    public String getRemoteowner() {
        return this.remoteowner;
    }
    
    public void setRemoteowner(String remoteowner) {
        this.remoteowner = remoteowner;
    }
    public String getLinkname() {
        return this.linkname;
    }
    
    public void setLinkname(String linkname) {
        this.linkname = linkname;
    }
    public BigDecimal getFlags() {
        return this.flags;
    }
    
    public void setFlags(BigDecimal flags) {
        this.flags = flags;
    }
    public BigDecimal getSpare3() {
        return this.spare3;
    }
    
    public void setSpare3(BigDecimal spare3) {
        this.spare3 = spare3;
    }
    public Date getStime() {
        return this.stime;
    }
    
    public void setStime(Date stime) {
        this.stime = stime;
    }
    public BigDecimal getLogmnrFlags() {
        return this.logmnrFlags;
    }
    
    public void setLogmnrFlags(BigDecimal logmnrFlags) {
        this.logmnrFlags = logmnrFlags;
    }
    public BigDecimal getStartScnbas() {
        return this.startScnbas;
    }
    
    public void setStartScnbas(BigDecimal startScnbas) {
        this.startScnbas = startScnbas;
    }
    public BigDecimal getStartScnwrp() {
        return this.startScnwrp;
    }
    
    public void setStartScnwrp(BigDecimal startScnwrp) {
        this.startScnwrp = startScnwrp;
    }




}


