package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * LogmnrEncId generated by hbm2java
 */
public class LogmnrEncId  implements java.io.Serializable {


     private BigDecimal logmnrUid;
     private BigDecimal obj_;
     private BigDecimal owner_;

    

    
   
    public BigDecimal getLogmnrUid() {
        return this.logmnrUid;
    }
    
    public void setLogmnrUid(BigDecimal logmnrUid) {
        this.logmnrUid = logmnrUid;
    }
    public BigDecimal getObj_() {
        return this.obj_;
    }
    
    public void setObj_(BigDecimal obj_) {
        this.obj_ = obj_;
    }
    public BigDecimal getOwner_() {
        return this.owner_;
    }
    
    public void setOwner_(BigDecimal owner_) {
        this.owner_ = owner_;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LogmnrEncId) ) return false;
		 LogmnrEncId castOther = ( LogmnrEncId ) other; 
         
		 return ( (this.getLogmnrUid()==castOther.getLogmnrUid()) || ( this.getLogmnrUid()!=null && castOther.getLogmnrUid()!=null && this.getLogmnrUid().equals(castOther.getLogmnrUid()) ) )
 && ( (this.getObj_()==castOther.getObj_()) || ( this.getObj_()!=null && castOther.getObj_()!=null && this.getObj_().equals(castOther.getObj_()) ) )
 && ( (this.getOwner_()==castOther.getOwner_()) || ( this.getOwner_()!=null && castOther.getOwner_()!=null && this.getOwner_().equals(castOther.getOwner_()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLogmnrUid() == null ? 0 : this.getLogmnrUid().hashCode() );
         result = 37 * result + ( getObj_() == null ? 0 : this.getObj_().hashCode() );
         result = 37 * result + ( getOwner_() == null ? 0 : this.getOwner_().hashCode() );
         return result;
   }   


}


