package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * LogmnrKopm generated by hbm2java
 */
public class LogmnrKopm  implements java.io.Serializable {


     private LogmnrKopmId id;
     private BigDecimal length;
     private byte[] metadata;
     private BigDecimal logmnrFlags;

    

	
    
    
   
    public LogmnrKopmId getId() {
        return this.id;
    }
    
    public void setId(LogmnrKopmId id) {
        this.id = id;
    }
    public BigDecimal getLength() {
        return this.length;
    }
    
    public void setLength(BigDecimal length) {
        this.length = length;
    }
    public byte[] getMetadata() {
        return this.metadata;
    }
    
    public void setMetadata(byte[] metadata) {
        this.metadata = metadata;
    }
    public BigDecimal getLogmnrFlags() {
        return this.logmnrFlags;
    }
    
    public void setLogmnrFlags(BigDecimal logmnrFlags) {
        this.logmnrFlags = logmnrFlags;
    }




}


