package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * LogmnrSubcoltype generated by hbm2java
 */
public class LogmnrSubcoltype  implements java.io.Serializable {


     private LogmnrSubcoltypeId id;
     private BigDecimal version_;
     private BigDecimal intcols;
     private byte[] intcol_s;
     private BigDecimal flags;
     private BigDecimal synobj_;
     private BigDecimal logmnrFlags;

    

	
    
    
   
    public LogmnrSubcoltypeId getId() {
        return this.id;
    }
    
    public void setId(LogmnrSubcoltypeId id) {
        this.id = id;
    }
    public BigDecimal getVersion_() {
        return this.version_;
    }
    
    public void setVersion_(BigDecimal version_) {
        this.version_ = version_;
    }
    public BigDecimal getIntcols() {
        return this.intcols;
    }
    
    public void setIntcols(BigDecimal intcols) {
        this.intcols = intcols;
    }
    public byte[] getIntcol_s() {
        return this.intcol_s;
    }
    
    public void setIntcol_s(byte[] intcol_s) {
        this.intcol_s = intcol_s;
    }
    public BigDecimal getFlags() {
        return this.flags;
    }
    
    public void setFlags(BigDecimal flags) {
        this.flags = flags;
    }
    public BigDecimal getSynobj_() {
        return this.synobj_;
    }
    
    public void setSynobj_(BigDecimal synobj_) {
        this.synobj_ = synobj_;
    }
    public BigDecimal getLogmnrFlags() {
        return this.logmnrFlags;
    }
    
    public void setLogmnrFlags(BigDecimal logmnrFlags) {
        this.logmnrFlags = logmnrFlags;
    }




}


