package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA



/**
 * LogmnrGtXidInclude generated by hbm2java
 */
public class LogmnrGtXidInclude  implements java.io.Serializable {


     private LogmnrGtXidIncludeId id;

    

    
   
    public LogmnrGtXidIncludeId getId() {
        return this.id;
    }
    
    public void setId(LogmnrGtXidIncludeId id) {
        this.id = id;
    }




}


