package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA



/**
 * LogmnrGtUserInclude generated by hbm2java
 */
public class LogmnrGtUserInclude  implements java.io.Serializable {


     private LogmnrGtUserIncludeId id;

    

    
   
    public LogmnrGtUserIncludeId getId() {
        return this.id;
    }
    
    public void setId(LogmnrGtUserIncludeId id) {
        this.id = id;
    }




}


