package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.sql.Blob;

/**
 * LogmnrRestartCkpt generated by hbm2java
 */
public class LogmnrRestartCkpt  implements java.io.Serializable {


     private LogmnrRestartCkptId id;
     private BigDecimal valid;
     private Blob ckptInfo;
     private BigDecimal flag;
     private BigDecimal offset;
     private Blob clientData;
     private BigDecimal spare1;
     private BigDecimal spare2;

    

	
    
    
   
    public LogmnrRestartCkptId getId() {
        return this.id;
    }
    
    public void setId(LogmnrRestartCkptId id) {
        this.id = id;
    }
    public BigDecimal getValid() {
        return this.valid;
    }
    
    public void setValid(BigDecimal valid) {
        this.valid = valid;
    }
    public Blob getCkptInfo() {
        return this.ckptInfo;
    }
    
    public void setCkptInfo(Blob ckptInfo) {
        this.ckptInfo = ckptInfo;
    }
    public BigDecimal getFlag() {
        return this.flag;
    }
    
    public void setFlag(BigDecimal flag) {
        this.flag = flag;
    }
    public BigDecimal getOffset() {
        return this.offset;
    }
    
    public void setOffset(BigDecimal offset) {
        this.offset = offset;
    }
    public Blob getClientData() {
        return this.clientData;
    }
    
    public void setClientData(Blob clientData) {
        this.clientData = clientData;
    }
    public BigDecimal getSpare1() {
        return this.spare1;
    }
    
    public void setSpare1(BigDecimal spare1) {
        this.spare1 = spare1;
    }
    public BigDecimal getSpare2() {
        return this.spare2;
    }
    
    public void setSpare2(BigDecimal spare2) {
        this.spare2 = spare2;
    }




}


