package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;

/**
 * LogmnrIntegratedSpill generated by hbm2java
 */
public class LogmnrIntegratedSpill  implements java.io.Serializable {


     private LogmnrIntegratedSpillId id;
     private Date ctime;
     private Date mtime;
     private Blob spillData;
     private BigDecimal spare1;
     private BigDecimal spare2;
     private BigDecimal spare3;
     private Date spare4;
     private Date spare5;

    

	
    
    
   
    public LogmnrIntegratedSpillId getId() {
        return this.id;
    }
    
    public void setId(LogmnrIntegratedSpillId id) {
        this.id = id;
    }
    public Date getCtime() {
        return this.ctime;
    }
    
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }
    public Date getMtime() {
        return this.mtime;
    }
    
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }
    public Blob getSpillData() {
        return this.spillData;
    }
    
    public void setSpillData(Blob spillData) {
        this.spillData = spillData;
    }
    public BigDecimal getSpare1() {
        return this.spare1;
    }
    
    public void setSpare1(BigDecimal spare1) {
        this.spare1 = spare1;
    }
    public BigDecimal getSpare2() {
        return this.spare2;
    }
    
    public void setSpare2(BigDecimal spare2) {
        this.spare2 = spare2;
    }
    public BigDecimal getSpare3() {
        return this.spare3;
    }
    
    public void setSpare3(BigDecimal spare3) {
        this.spare3 = spare3;
    }
    public Date getSpare4() {
        return this.spare4;
    }
    
    public void setSpare4(Date spare4) {
        this.spare4 = spare4;
    }
    public Date getSpare5() {
        return this.spare5;
    }
    
    public void setSpare5(Date spare5) {
        this.spare5 = spare5;
    }




}


