package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA



/**
 * LogmnrError generated by hbm2java
 */
public class LogmnrError  implements java.io.Serializable {


     private LogmnrErrorId id;

    

    
   
    public LogmnrErrorId getId() {
        return this.id;
    }
    
    public void setId(LogmnrErrorId id) {
        this.id = id;
    }




}


