package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * LogmnrLog generated by hbm2java
 */
public class LogmnrLog  implements java.io.Serializable {


     private LogmnrLogId id;
     private BigDecimal nextChange_;
     private Date firstTime;
     private Date nextTime;
     private String fileName;
     private BigDecimal status;
     private String info;
     private Date timestamp;
     private String dictBegin;
     private String dictEnd;
     private String statusInfo;
     private BigDecimal prevResetlogsChange_;
     private BigDecimal prevResetTimestamp;
     private BigDecimal blocks;
     private BigDecimal blockSize;
     private BigDecimal flags;
     private BigDecimal contents;
     private BigDecimal recid;
     private BigDecimal recstamp;
     private BigDecimal markDeleteTimestamp;
     private BigDecimal spare1;
     private BigDecimal spare2;
     private BigDecimal spare3;
     private BigDecimal spare4;
     private BigDecimal spare5;

    

	
    
    
   
    public LogmnrLogId getId() {
        return this.id;
    }
    
    public void setId(LogmnrLogId id) {
        this.id = id;
    }
    public BigDecimal getNextChange_() {
        return this.nextChange_;
    }
    
    public void setNextChange_(BigDecimal nextChange_) {
        this.nextChange_ = nextChange_;
    }
    public Date getFirstTime() {
        return this.firstTime;
    }
    
    public void setFirstTime(Date firstTime) {
        this.firstTime = firstTime;
    }
    public Date getNextTime() {
        return this.nextTime;
    }
    
    public void setNextTime(Date nextTime) {
        this.nextTime = nextTime;
    }
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    public BigDecimal getStatus() {
        return this.status;
    }
    
    public void setStatus(BigDecimal status) {
        this.status = status;
    }
    public String getInfo() {
        return this.info;
    }
    
    public void setInfo(String info) {
        this.info = info;
    }
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    public String getDictBegin() {
        return this.dictBegin;
    }
    
    public void setDictBegin(String dictBegin) {
        this.dictBegin = dictBegin;
    }
    public String getDictEnd() {
        return this.dictEnd;
    }
    
    public void setDictEnd(String dictEnd) {
        this.dictEnd = dictEnd;
    }
    public String getStatusInfo() {
        return this.statusInfo;
    }
    
    public void setStatusInfo(String statusInfo) {
        this.statusInfo = statusInfo;
    }
    public BigDecimal getPrevResetlogsChange_() {
        return this.prevResetlogsChange_;
    }
    
    public void setPrevResetlogsChange_(BigDecimal prevResetlogsChange_) {
        this.prevResetlogsChange_ = prevResetlogsChange_;
    }
    public BigDecimal getPrevResetTimestamp() {
        return this.prevResetTimestamp;
    }
    
    public void setPrevResetTimestamp(BigDecimal prevResetTimestamp) {
        this.prevResetTimestamp = prevResetTimestamp;
    }
    public BigDecimal getBlocks() {
        return this.blocks;
    }
    
    public void setBlocks(BigDecimal blocks) {
        this.blocks = blocks;
    }
    public BigDecimal getBlockSize() {
        return this.blockSize;
    }
    
    public void setBlockSize(BigDecimal blockSize) {
        this.blockSize = blockSize;
    }
    public BigDecimal getFlags() {
        return this.flags;
    }
    
    public void setFlags(BigDecimal flags) {
        this.flags = flags;
    }
    public BigDecimal getContents() {
        return this.contents;
    }
    
    public void setContents(BigDecimal contents) {
        this.contents = contents;
    }
    public BigDecimal getRecid() {
        return this.recid;
    }
    
    public void setRecid(BigDecimal recid) {
        this.recid = recid;
    }
    public BigDecimal getRecstamp() {
        return this.recstamp;
    }
    
    public void setRecstamp(BigDecimal recstamp) {
        this.recstamp = recstamp;
    }
    public BigDecimal getMarkDeleteTimestamp() {
        return this.markDeleteTimestamp;
    }
    
    public void setMarkDeleteTimestamp(BigDecimal markDeleteTimestamp) {
        this.markDeleteTimestamp = markDeleteTimestamp;
    }
    public BigDecimal getSpare1() {
        return this.spare1;
    }
    
    public void setSpare1(BigDecimal spare1) {
        this.spare1 = spare1;
    }
    public BigDecimal getSpare2() {
        return this.spare2;
    }
    
    public void setSpare2(BigDecimal spare2) {
        this.spare2 = spare2;
    }
    public BigDecimal getSpare3() {
        return this.spare3;
    }
    
    public void setSpare3(BigDecimal spare3) {
        this.spare3 = spare3;
    }
    public BigDecimal getSpare4() {
        return this.spare4;
    }
    
    public void setSpare4(BigDecimal spare4) {
        this.spare4 = spare4;
    }
    public BigDecimal getSpare5() {
        return this.spare5;
    }
    
    public void setSpare5(BigDecimal spare5) {
        this.spare5 = spare5;
    }




}


