package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * LogmnrDictionary generated by hbm2java
 */
public class LogmnrDictionary  implements java.io.Serializable {


     private BigDecimal logmnrUid;
     private String dbName;
     private BigDecimal dbId;
     private String dbCreated;
     private String dbDictCreated;
     private BigDecimal dbDictScn;
     private byte[] dbThreadMap;
     private BigDecimal dbTxnScnbas;
     private BigDecimal dbTxnScnwrp;
     private BigDecimal dbResetlogsChange_;
     private String dbResetlogsTime;
     private String dbVersionTime;
     private String dbRedoTypeId;
     private String dbRedoRelease;
     private String dbCharacterSet;
     private String dbVersion;
     private String dbStatus;
     private String dbGlobalName;
     private BigDecimal dbDictMaxobjects;
     private BigDecimal dbDictObjectcount;
     private BigDecimal logmnrFlags;

    

	
    
    
   
    public BigDecimal getLogmnrUid() {
        return this.logmnrUid;
    }
    
    public void setLogmnrUid(BigDecimal logmnrUid) {
        this.logmnrUid = logmnrUid;
    }
    public String getDbName() {
        return this.dbName;
    }
    
    public void setDbName(String dbName) {
        this.dbName = dbName;
    }
    public BigDecimal getDbId() {
        return this.dbId;
    }
    
    public void setDbId(BigDecimal dbId) {
        this.dbId = dbId;
    }
    public String getDbCreated() {
        return this.dbCreated;
    }
    
    public void setDbCreated(String dbCreated) {
        this.dbCreated = dbCreated;
    }
    public String getDbDictCreated() {
        return this.dbDictCreated;
    }
    
    public void setDbDictCreated(String dbDictCreated) {
        this.dbDictCreated = dbDictCreated;
    }
    public BigDecimal getDbDictScn() {
        return this.dbDictScn;
    }
    
    public void setDbDictScn(BigDecimal dbDictScn) {
        this.dbDictScn = dbDictScn;
    }
    public byte[] getDbThreadMap() {
        return this.dbThreadMap;
    }
    
    public void setDbThreadMap(byte[] dbThreadMap) {
        this.dbThreadMap = dbThreadMap;
    }
    public BigDecimal getDbTxnScnbas() {
        return this.dbTxnScnbas;
    }
    
    public void setDbTxnScnbas(BigDecimal dbTxnScnbas) {
        this.dbTxnScnbas = dbTxnScnbas;
    }
    public BigDecimal getDbTxnScnwrp() {
        return this.dbTxnScnwrp;
    }
    
    public void setDbTxnScnwrp(BigDecimal dbTxnScnwrp) {
        this.dbTxnScnwrp = dbTxnScnwrp;
    }
    public BigDecimal getDbResetlogsChange_() {
        return this.dbResetlogsChange_;
    }
    
    public void setDbResetlogsChange_(BigDecimal dbResetlogsChange_) {
        this.dbResetlogsChange_ = dbResetlogsChange_;
    }
    public String getDbResetlogsTime() {
        return this.dbResetlogsTime;
    }
    
    public void setDbResetlogsTime(String dbResetlogsTime) {
        this.dbResetlogsTime = dbResetlogsTime;
    }
    public String getDbVersionTime() {
        return this.dbVersionTime;
    }
    
    public void setDbVersionTime(String dbVersionTime) {
        this.dbVersionTime = dbVersionTime;
    }
    public String getDbRedoTypeId() {
        return this.dbRedoTypeId;
    }
    
    public void setDbRedoTypeId(String dbRedoTypeId) {
        this.dbRedoTypeId = dbRedoTypeId;
    }
    public String getDbRedoRelease() {
        return this.dbRedoRelease;
    }
    
    public void setDbRedoRelease(String dbRedoRelease) {
        this.dbRedoRelease = dbRedoRelease;
    }
    public String getDbCharacterSet() {
        return this.dbCharacterSet;
    }
    
    public void setDbCharacterSet(String dbCharacterSet) {
        this.dbCharacterSet = dbCharacterSet;
    }
    public String getDbVersion() {
        return this.dbVersion;
    }
    
    public void setDbVersion(String dbVersion) {
        this.dbVersion = dbVersion;
    }
    public String getDbStatus() {
        return this.dbStatus;
    }
    
    public void setDbStatus(String dbStatus) {
        this.dbStatus = dbStatus;
    }
    public String getDbGlobalName() {
        return this.dbGlobalName;
    }
    
    public void setDbGlobalName(String dbGlobalName) {
        this.dbGlobalName = dbGlobalName;
    }
    public BigDecimal getDbDictMaxobjects() {
        return this.dbDictMaxobjects;
    }
    
    public void setDbDictMaxobjects(BigDecimal dbDictMaxobjects) {
        this.dbDictMaxobjects = dbDictMaxobjects;
    }
    public BigDecimal getDbDictObjectcount() {
        return this.dbDictObjectcount;
    }
    
    public void setDbDictObjectcount(BigDecimal dbDictObjectcount) {
        this.dbDictObjectcount = dbDictObjectcount;
    }
    public BigDecimal getLogmnrFlags() {
        return this.logmnrFlags;
    }
    
    public void setLogmnrFlags(BigDecimal logmnrFlags) {
        this.logmnrFlags = logmnrFlags;
    }




}


