package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * LogmnrIndpart generated by hbm2java
 */
public class LogmnrIndpart  implements java.io.Serializable {


     private LogmnrIndpartId id;
     private BigDecimal part_;
     private BigDecimal ts_;
     private BigDecimal logmnrFlags;

    

	
    
    
   
    public LogmnrIndpartId getId() {
        return this.id;
    }
    
    public void setId(LogmnrIndpartId id) {
        this.id = id;
    }
    public BigDecimal getPart_() {
        return this.part_;
    }
    
    public void setPart_(BigDecimal part_) {
        this.part_ = part_;
    }
    public BigDecimal getTs_() {
        return this.ts_;
    }
    
    public void setTs_(BigDecimal ts_) {
        this.ts_ = ts_;
    }
    public BigDecimal getLogmnrFlags() {
        return this.logmnrFlags;
    }
    
    public void setLogmnrFlags(BigDecimal logmnrFlags) {
        this.logmnrFlags = logmnrFlags;
    }




}


