package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * LogmnrtMddlId generated by hbm2java
 */
public class LogmnrtMddlId  implements java.io.Serializable {


     private BigDecimal sourceObj_;
     private Date sourceRowid;

    

    
   
    public BigDecimal getSourceObj_() {
        return this.sourceObj_;
    }
    
    public void setSourceObj_(BigDecimal sourceObj_) {
        this.sourceObj_ = sourceObj_;
    }
    public Date getSourceRowid() {
        return this.sourceRowid;
    }
    
    public void setSourceRowid(Date sourceRowid) {
        this.sourceRowid = sourceRowid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LogmnrtMddlId) ) return false;
		 LogmnrtMddlId castOther = ( LogmnrtMddlId ) other; 
         
		 return ( (this.getSourceObj_()==castOther.getSourceObj_()) || ( this.getSourceObj_()!=null && castOther.getSourceObj_()!=null && this.getSourceObj_().equals(castOther.getSourceObj_()) ) )
 && ( (this.getSourceRowid()==castOther.getSourceRowid()) || ( this.getSourceRowid()!=null && castOther.getSourceRowid()!=null && this.getSourceRowid().equals(castOther.getSourceRowid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSourceObj_() == null ? 0 : this.getSourceObj_().hashCode() );
         result = 37 * result + ( getSourceRowid() == null ? 0 : this.getSourceRowid().hashCode() );
         return result;
   }   


}


