package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * LogmnrTab generated by hbm2java
 */
public class LogmnrTab  implements java.io.Serializable {


     private LogmnrTabId id;
     private BigDecimal ts_;
     private BigDecimal cols;
     private BigDecimal property;
     private BigDecimal intcols;
     private BigDecimal kernelcols;
     private BigDecimal bobj_;
     private BigDecimal trigflag;
     private BigDecimal flags;
     private BigDecimal logmnrFlags;

    

	
    
    
   
    public LogmnrTabId getId() {
        return this.id;
    }
    
    public void setId(LogmnrTabId id) {
        this.id = id;
    }
    public BigDecimal getTs_() {
        return this.ts_;
    }
    
    public void setTs_(BigDecimal ts_) {
        this.ts_ = ts_;
    }
    public BigDecimal getCols() {
        return this.cols;
    }
    
    public void setCols(BigDecimal cols) {
        this.cols = cols;
    }
    public BigDecimal getProperty() {
        return this.property;
    }
    
    public void setProperty(BigDecimal property) {
        this.property = property;
    }
    public BigDecimal getIntcols() {
        return this.intcols;
    }
    
    public void setIntcols(BigDecimal intcols) {
        this.intcols = intcols;
    }
    public BigDecimal getKernelcols() {
        return this.kernelcols;
    }
    
    public void setKernelcols(BigDecimal kernelcols) {
        this.kernelcols = kernelcols;
    }
    public BigDecimal getBobj_() {
        return this.bobj_;
    }
    
    public void setBobj_(BigDecimal bobj_) {
        this.bobj_ = bobj_;
    }
    public BigDecimal getTrigflag() {
        return this.trigflag;
    }
    
    public void setTrigflag(BigDecimal trigflag) {
        this.trigflag = trigflag;
    }
    public BigDecimal getFlags() {
        return this.flags;
    }
    
    public void setFlags(BigDecimal flags) {
        this.flags = flags;
    }
    public BigDecimal getLogmnrFlags() {
        return this.logmnrFlags;
    }
    
    public void setLogmnrFlags(BigDecimal logmnrFlags) {
        this.logmnrFlags = logmnrFlags;
    }




}


