package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA



/**
 * LogmnrGtTabIncludeId generated by hbm2java
 */
public class LogmnrGtTabIncludeId  implements java.io.Serializable {


     private String schemaName;
     private String tableName;

    

    
   
    public String getSchemaName() {
        return this.schemaName;
    }
    
    public void setSchemaName(String schemaName) {
        this.schemaName = schemaName;
    }
    public String getTableName() {
        return this.tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LogmnrGtTabIncludeId) ) return false;
		 LogmnrGtTabIncludeId castOther = ( LogmnrGtTabIncludeId ) other; 
         
		 return ( (this.getSchemaName()==castOther.getSchemaName()) || ( this.getSchemaName()!=null && castOther.getSchemaName()!=null && this.getSchemaName().equals(castOther.getSchemaName()) ) )
 && ( (this.getTableName()==castOther.getTableName()) || ( this.getTableName()!=null && castOther.getTableName()!=null && this.getTableName().equals(castOther.getTableName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSchemaName() == null ? 0 : this.getSchemaName().hashCode() );
         result = 37 * result + ( getTableName() == null ? 0 : this.getTableName().hashCode() );
         return result;
   }   


}


