package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * LogmnrCdefId generated by hbm2java
 */
public class LogmnrCdefId  implements java.io.Serializable {


     private BigDecimal logmnrUid;
     private BigDecimal con_;

    

    
   
    public BigDecimal getLogmnrUid() {
        return this.logmnrUid;
    }
    
    public void setLogmnrUid(BigDecimal logmnrUid) {
        this.logmnrUid = logmnrUid;
    }
    public BigDecimal getCon_() {
        return this.con_;
    }
    
    public void setCon_(BigDecimal con_) {
        this.con_ = con_;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LogmnrCdefId) ) return false;
		 LogmnrCdefId castOther = ( LogmnrCdefId ) other; 
         
		 return ( (this.getLogmnrUid()==castOther.getLogmnrUid()) || ( this.getLogmnrUid()!=null && castOther.getLogmnrUid()!=null && this.getLogmnrUid().equals(castOther.getLogmnrUid()) ) )
 && ( (this.getCon_()==castOther.getCon_()) || ( this.getCon_()!=null && castOther.getCon_()!=null && this.getCon_().equals(castOther.getCon_()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLogmnrUid() == null ? 0 : this.getLogmnrUid().hashCode() );
         result = 37 * result + ( getCon_() == null ? 0 : this.getCon_().hashCode() );
         return result;
   }   


}


