package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * LogmnrcGsbaId generated by hbm2java
 */
public class LogmnrcGsbaId  implements java.io.Serializable {


     private BigDecimal logmnrUid;
     private BigDecimal asOfScn;

    

    
   
    public BigDecimal getLogmnrUid() {
        return this.logmnrUid;
    }
    
    public void setLogmnrUid(BigDecimal logmnrUid) {
        this.logmnrUid = logmnrUid;
    }
    public BigDecimal getAsOfScn() {
        return this.asOfScn;
    }
    
    public void setAsOfScn(BigDecimal asOfScn) {
        this.asOfScn = asOfScn;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LogmnrcGsbaId) ) return false;
		 LogmnrcGsbaId castOther = ( LogmnrcGsbaId ) other; 
         
		 return ( (this.getLogmnrUid()==castOther.getLogmnrUid()) || ( this.getLogmnrUid()!=null && castOther.getLogmnrUid()!=null && this.getLogmnrUid().equals(castOther.getLogmnrUid()) ) )
 && ( (this.getAsOfScn()==castOther.getAsOfScn()) || ( this.getAsOfScn()!=null && castOther.getAsOfScn()!=null && this.getAsOfScn().equals(castOther.getAsOfScn()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLogmnrUid() == null ? 0 : this.getLogmnrUid().hashCode() );
         result = 37 * result + ( getAsOfScn() == null ? 0 : this.getAsOfScn().hashCode() );
         return result;
   }   


}


