package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.util.Date;

/**
 * LogmnrtMddl generated by hbm2java
 */
public class LogmnrtMddl  implements java.io.Serializable {


     private LogmnrtMddlId id;
     private Date destRowid;

    

    
   
    public LogmnrtMddlId getId() {
        return this.id;
    }
    
    public void setId(LogmnrtMddlId id) {
        this.id = id;
    }
    public Date getDestRowid() {
        return this.destRowid;
    }
    
    public void setDestRowid(Date destRowid) {
        this.destRowid = destRowid;
    }




}


