package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA



/**
 * LogmnrGtTabInclude generated by hbm2java
 */
public class LogmnrGtTabInclude  implements java.io.Serializable {


     private LogmnrGtTabIncludeId id;

    

    
   
    public LogmnrGtTabIncludeId getId() {
        return this.id;
    }
    
    public void setId(LogmnrGtTabIncludeId id) {
        this.id = id;
    }




}


