package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA



/**
 * LogmnrParameter generated by hbm2java
 */
public class LogmnrParameter  implements java.io.Serializable {


     private LogmnrParameterId id;

    

    
   
    public LogmnrParameterId getId() {
        return this.id;
    }
    
    public void setId(LogmnrParameterId id) {
        this.id = id;
    }




}


