package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * LogmnrProcessedLogId generated by hbm2java
 */
public class LogmnrProcessedLogId  implements java.io.Serializable {


     private BigDecimal session_;
     private BigDecimal thread_;

    

    
   
    public BigDecimal getSession_() {
        return this.session_;
    }
    
    public void setSession_(BigDecimal session_) {
        this.session_ = session_;
    }
    public BigDecimal getThread_() {
        return this.thread_;
    }
    
    public void setThread_(BigDecimal thread_) {
        this.thread_ = thread_;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LogmnrProcessedLogId) ) return false;
		 LogmnrProcessedLogId castOther = ( LogmnrProcessedLogId ) other; 
         
		 return ( (this.getSession_()==castOther.getSession_()) || ( this.getSession_()!=null && castOther.getSession_()!=null && this.getSession_().equals(castOther.getSession_()) ) )
 && ( (this.getThread_()==castOther.getThread_()) || ( this.getThread_()!=null && castOther.getThread_()!=null && this.getThread_().equals(castOther.getThread_()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSession_() == null ? 0 : this.getSession_().hashCode() );
         result = 37 * result + ( getThread_() == null ? 0 : this.getThread_().hashCode() );
         return result;
   }   


}


