package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * LogmnrLobfrag generated by hbm2java
 */
public class LogmnrLobfrag  implements java.io.Serializable {


     private LogmnrLobfragId id;
     private BigDecimal parentobj_;
     private BigDecimal tabfragobj_;
     private BigDecimal indfragobj_;
     private BigDecimal frag_;
     private BigDecimal logmnrFlags;

    

	
    
    
   
    public LogmnrLobfragId getId() {
        return this.id;
    }
    
    public void setId(LogmnrLobfragId id) {
        this.id = id;
    }
    public BigDecimal getParentobj_() {
        return this.parentobj_;
    }
    
    public void setParentobj_(BigDecimal parentobj_) {
        this.parentobj_ = parentobj_;
    }
    public BigDecimal getTabfragobj_() {
        return this.tabfragobj_;
    }
    
    public void setTabfragobj_(BigDecimal tabfragobj_) {
        this.tabfragobj_ = tabfragobj_;
    }
    public BigDecimal getIndfragobj_() {
        return this.indfragobj_;
    }
    
    public void setIndfragobj_(BigDecimal indfragobj_) {
        this.indfragobj_ = indfragobj_;
    }
    public BigDecimal getFrag_() {
        return this.frag_;
    }
    
    public void setFrag_(BigDecimal frag_) {
        this.frag_ = frag_;
    }
    public BigDecimal getLogmnrFlags() {
        return this.logmnrFlags;
    }
    
    public void setLogmnrFlags(BigDecimal logmnrFlags) {
        this.logmnrFlags = logmnrFlags;
    }




}


