package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * LogmnrSpillId generated by hbm2java
 */
public class LogmnrSpillId  implements java.io.Serializable {


     private BigDecimal session_;
     private BigDecimal xidusn;
     private BigDecimal xidslt;
     private BigDecimal xidsqn;
     private BigDecimal chunk;
     private BigDecimal startidx;
     private BigDecimal endidx;
     private BigDecimal flag;
     private BigDecimal sequence_;

    

    
   
    public BigDecimal getSession_() {
        return this.session_;
    }
    
    public void setSession_(BigDecimal session_) {
        this.session_ = session_;
    }
    public BigDecimal getXidusn() {
        return this.xidusn;
    }
    
    public void setXidusn(BigDecimal xidusn) {
        this.xidusn = xidusn;
    }
    public BigDecimal getXidslt() {
        return this.xidslt;
    }
    
    public void setXidslt(BigDecimal xidslt) {
        this.xidslt = xidslt;
    }
    public BigDecimal getXidsqn() {
        return this.xidsqn;
    }
    
    public void setXidsqn(BigDecimal xidsqn) {
        this.xidsqn = xidsqn;
    }
    public BigDecimal getChunk() {
        return this.chunk;
    }
    
    public void setChunk(BigDecimal chunk) {
        this.chunk = chunk;
    }
    public BigDecimal getStartidx() {
        return this.startidx;
    }
    
    public void setStartidx(BigDecimal startidx) {
        this.startidx = startidx;
    }
    public BigDecimal getEndidx() {
        return this.endidx;
    }
    
    public void setEndidx(BigDecimal endidx) {
        this.endidx = endidx;
    }
    public BigDecimal getFlag() {
        return this.flag;
    }
    
    public void setFlag(BigDecimal flag) {
        this.flag = flag;
    }
    public BigDecimal getSequence_() {
        return this.sequence_;
    }
    
    public void setSequence_(BigDecimal sequence_) {
        this.sequence_ = sequence_;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LogmnrSpillId) ) return false;
		 LogmnrSpillId castOther = ( LogmnrSpillId ) other; 
         
		 return ( (this.getSession_()==castOther.getSession_()) || ( this.getSession_()!=null && castOther.getSession_()!=null && this.getSession_().equals(castOther.getSession_()) ) )
 && ( (this.getXidusn()==castOther.getXidusn()) || ( this.getXidusn()!=null && castOther.getXidusn()!=null && this.getXidusn().equals(castOther.getXidusn()) ) )
 && ( (this.getXidslt()==castOther.getXidslt()) || ( this.getXidslt()!=null && castOther.getXidslt()!=null && this.getXidslt().equals(castOther.getXidslt()) ) )
 && ( (this.getXidsqn()==castOther.getXidsqn()) || ( this.getXidsqn()!=null && castOther.getXidsqn()!=null && this.getXidsqn().equals(castOther.getXidsqn()) ) )
 && ( (this.getChunk()==castOther.getChunk()) || ( this.getChunk()!=null && castOther.getChunk()!=null && this.getChunk().equals(castOther.getChunk()) ) )
 && ( (this.getStartidx()==castOther.getStartidx()) || ( this.getStartidx()!=null && castOther.getStartidx()!=null && this.getStartidx().equals(castOther.getStartidx()) ) )
 && ( (this.getEndidx()==castOther.getEndidx()) || ( this.getEndidx()!=null && castOther.getEndidx()!=null && this.getEndidx().equals(castOther.getEndidx()) ) )
 && ( (this.getFlag()==castOther.getFlag()) || ( this.getFlag()!=null && castOther.getFlag()!=null && this.getFlag().equals(castOther.getFlag()) ) )
 && ( (this.getSequence_()==castOther.getSequence_()) || ( this.getSequence_()!=null && castOther.getSequence_()!=null && this.getSequence_().equals(castOther.getSequence_()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSession_() == null ? 0 : this.getSession_().hashCode() );
         result = 37 * result + ( getXidusn() == null ? 0 : this.getXidusn().hashCode() );
         result = 37 * result + ( getXidslt() == null ? 0 : this.getXidslt().hashCode() );
         result = 37 * result + ( getXidsqn() == null ? 0 : this.getXidsqn().hashCode() );
         result = 37 * result + ( getChunk() == null ? 0 : this.getChunk().hashCode() );
         result = 37 * result + ( getStartidx() == null ? 0 : this.getStartidx().hashCode() );
         result = 37 * result + ( getEndidx() == null ? 0 : this.getEndidx().hashCode() );
         result = 37 * result + ( getFlag() == null ? 0 : this.getFlag().hashCode() );
         result = 37 * result + ( getSequence_() == null ? 0 : this.getSequence_().hashCode() );
         return result;
   }   


}


