package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * LogmnrUid generated by hbm2java
 */
public class LogmnrUid  implements java.io.Serializable {


     private BigDecimal session_;
     private BigDecimal logmnrUid;

    

	
    
    
   
    public BigDecimal getSession_() {
        return this.session_;
    }
    
    public void setSession_(BigDecimal session_) {
        this.session_ = session_;
    }
    public BigDecimal getLogmnrUid() {
        return this.logmnrUid;
    }
    
    public void setLogmnrUid(BigDecimal logmnrUid) {
        this.logmnrUid = logmnrUid;
    }




}


