package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * LogmnrTs generated by hbm2java
 */
public class LogmnrTs  implements java.io.Serializable {


     private LogmnrTsId id;
     private String name;
     private BigDecimal owner_;
     private BigDecimal blocksize;
     private BigDecimal logmnrFlags;

    

	
    
    
   
    public LogmnrTsId getId() {
        return this.id;
    }
    
    public void setId(LogmnrTsId id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public BigDecimal getOwner_() {
        return this.owner_;
    }
    
    public void setOwner_(BigDecimal owner_) {
        this.owner_ = owner_;
    }
    public BigDecimal getBlocksize() {
        return this.blocksize;
    }
    
    public void setBlocksize(BigDecimal blocksize) {
        this.blocksize = blocksize;
    }
    public BigDecimal getLogmnrFlags() {
        return this.logmnrFlags;
    }
    
    public void setLogmnrFlags(BigDecimal logmnrFlags) {
        this.logmnrFlags = logmnrFlags;
    }




}


