package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA



/**
 * LogmnrFilter generated by hbm2java
 */
public class LogmnrFilter  implements java.io.Serializable {


     private LogmnrFilterId id;

    

    
   
    public LogmnrFilterId getId() {
        return this.id;
    }
    
    public void setId(LogmnrFilterId id) {
        this.id = id;
    }




}


