package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * LogmnrCol generated by hbm2java
 */
public class LogmnrCol  implements java.io.Serializable {


     private LogmnrColId id;
     private BigDecimal col_;
     private BigDecimal segcol_;
     private String name;
     private BigDecimal type_;
     private BigDecimal length;
     private BigDecimal precision_;
     private BigDecimal scale;
     private BigDecimal null;
     private BigDecimal property;
     private BigDecimal charsetid;
     private BigDecimal charsetform;
     private BigDecimal spare1;
     private BigDecimal spare2;
     private BigDecimal logmnrFlags;

    

	
    
    
   
    public LogmnrColId getId() {
        return this.id;
    }
    
    public void setId(LogmnrColId id) {
        this.id = id;
    }
    public BigDecimal getCol_() {
        return this.col_;
    }
    
    public void setCol_(BigDecimal col_) {
        this.col_ = col_;
    }
    public BigDecimal getSegcol_() {
        return this.segcol_;
    }
    
    public void setSegcol_(BigDecimal segcol_) {
        this.segcol_ = segcol_;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public BigDecimal getType_() {
        return this.type_;
    }
    
    public void setType_(BigDecimal type_) {
        this.type_ = type_;
    }
    public BigDecimal getLength() {
        return this.length;
    }
    
    public void setLength(BigDecimal length) {
        this.length = length;
    }
    public BigDecimal getPrecision_() {
        return this.precision_;
    }
    
    public void setPrecision_(BigDecimal precision_) {
        this.precision_ = precision_;
    }
    public BigDecimal getScale() {
        return this.scale;
    }
    
    public void setScale(BigDecimal scale) {
        this.scale = scale;
    }
    public BigDecimal getNull() {
        return this.null;
    }
    
    public void setNull(BigDecimal null) {
        this.null = null;
    }
    public BigDecimal getProperty() {
        return this.property;
    }
    
    public void setProperty(BigDecimal property) {
        this.property = property;
    }
    public BigDecimal getCharsetid() {
        return this.charsetid;
    }
    
    public void setCharsetid(BigDecimal charsetid) {
        this.charsetid = charsetid;
    }
    public BigDecimal getCharsetform() {
        return this.charsetform;
    }
    
    public void setCharsetform(BigDecimal charsetform) {
        this.charsetform = charsetform;
    }
    public BigDecimal getSpare1() {
        return this.spare1;
    }
    
    public void setSpare1(BigDecimal spare1) {
        this.spare1 = spare1;
    }
    public BigDecimal getSpare2() {
        return this.spare2;
    }
    
    public void setSpare2(BigDecimal spare2) {
        this.spare2 = spare2;
    }
    public BigDecimal getLogmnrFlags() {
        return this.logmnrFlags;
    }
    
    public void setLogmnrFlags(BigDecimal logmnrFlags) {
        this.logmnrFlags = logmnrFlags;
    }




}


