package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * LogmnrType generated by hbm2java
 */
public class LogmnrType  implements java.io.Serializable {


     private LogmnrTypeId id;
     private String version;
     private byte[] tvoid;
     private BigDecimal typecode;
     private BigDecimal properties;
     private BigDecimal attributes;
     private BigDecimal methods;
     private BigDecimal hiddenmethods;
     private BigDecimal supertypes;
     private BigDecimal subtypes;
     private BigDecimal externtype;
     private String externname;
     private String helperclassname;
     private BigDecimal localAttrs;
     private BigDecimal localMethods;
     private byte[] typeid;
     private byte[] roottoid;
     private BigDecimal spare1;
     private BigDecimal spare2;
     private BigDecimal spare3;
     private byte[] supertoid;
     private byte[] hashcode;
     private BigDecimal logmnrFlags;

    

	
    
    
   
    public LogmnrTypeId getId() {
        return this.id;
    }
    
    public void setId(LogmnrTypeId id) {
        this.id = id;
    }
    public String getVersion() {
        return this.version;
    }
    
    public void setVersion(String version) {
        this.version = version;
    }
    public byte[] getTvoid() {
        return this.tvoid;
    }
    
    public void setTvoid(byte[] tvoid) {
        this.tvoid = tvoid;
    }
    public BigDecimal getTypecode() {
        return this.typecode;
    }
    
    public void setTypecode(BigDecimal typecode) {
        this.typecode = typecode;
    }
    public BigDecimal getProperties() {
        return this.properties;
    }
    
    public void setProperties(BigDecimal properties) {
        this.properties = properties;
    }
    public BigDecimal getAttributes() {
        return this.attributes;
    }
    
    public void setAttributes(BigDecimal attributes) {
        this.attributes = attributes;
    }
    public BigDecimal getMethods() {
        return this.methods;
    }
    
    public void setMethods(BigDecimal methods) {
        this.methods = methods;
    }
    public BigDecimal getHiddenmethods() {
        return this.hiddenmethods;
    }
    
    public void setHiddenmethods(BigDecimal hiddenmethods) {
        this.hiddenmethods = hiddenmethods;
    }
    public BigDecimal getSupertypes() {
        return this.supertypes;
    }
    
    public void setSupertypes(BigDecimal supertypes) {
        this.supertypes = supertypes;
    }
    public BigDecimal getSubtypes() {
        return this.subtypes;
    }
    
    public void setSubtypes(BigDecimal subtypes) {
        this.subtypes = subtypes;
    }
    public BigDecimal getExterntype() {
        return this.externtype;
    }
    
    public void setExterntype(BigDecimal externtype) {
        this.externtype = externtype;
    }
    public String getExternname() {
        return this.externname;
    }
    
    public void setExternname(String externname) {
        this.externname = externname;
    }
    public String getHelperclassname() {
        return this.helperclassname;
    }
    
    public void setHelperclassname(String helperclassname) {
        this.helperclassname = helperclassname;
    }
    public BigDecimal getLocalAttrs() {
        return this.localAttrs;
    }
    
    public void setLocalAttrs(BigDecimal localAttrs) {
        this.localAttrs = localAttrs;
    }
    public BigDecimal getLocalMethods() {
        return this.localMethods;
    }
    
    public void setLocalMethods(BigDecimal localMethods) {
        this.localMethods = localMethods;
    }
    public byte[] getTypeid() {
        return this.typeid;
    }
    
    public void setTypeid(byte[] typeid) {
        this.typeid = typeid;
    }
    public byte[] getRoottoid() {
        return this.roottoid;
    }
    
    public void setRoottoid(byte[] roottoid) {
        this.roottoid = roottoid;
    }
    public BigDecimal getSpare1() {
        return this.spare1;
    }
    
    public void setSpare1(BigDecimal spare1) {
        this.spare1 = spare1;
    }
    public BigDecimal getSpare2() {
        return this.spare2;
    }
    
    public void setSpare2(BigDecimal spare2) {
        this.spare2 = spare2;
    }
    public BigDecimal getSpare3() {
        return this.spare3;
    }
    
    public void setSpare3(BigDecimal spare3) {
        this.spare3 = spare3;
    }
    public byte[] getSupertoid() {
        return this.supertoid;
    }
    
    public void setSupertoid(byte[] supertoid) {
        this.supertoid = supertoid;
    }
    public byte[] getHashcode() {
        return this.hashcode;
    }
    
    public void setHashcode(byte[] hashcode) {
        this.hashcode = hashcode;
    }
    public BigDecimal getLogmnrFlags() {
        return this.logmnrFlags;
    }
    
    public void setLogmnrFlags(BigDecimal logmnrFlags) {
        this.logmnrFlags = logmnrFlags;
    }




}


