package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * LogmnrcGtloId generated by hbm2java
 */
public class LogmnrcGtloId  implements java.io.Serializable {


     private BigDecimal logmnrUid;
     private BigDecimal keyobj_;
     private BigDecimal baseobjv_;

    

    
   
    public BigDecimal getLogmnrUid() {
        return this.logmnrUid;
    }
    
    public void setLogmnrUid(BigDecimal logmnrUid) {
        this.logmnrUid = logmnrUid;
    }
    public BigDecimal getKeyobj_() {
        return this.keyobj_;
    }
    
    public void setKeyobj_(BigDecimal keyobj_) {
        this.keyobj_ = keyobj_;
    }
    public BigDecimal getBaseobjv_() {
        return this.baseobjv_;
    }
    
    public void setBaseobjv_(BigDecimal baseobjv_) {
        this.baseobjv_ = baseobjv_;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LogmnrcGtloId) ) return false;
		 LogmnrcGtloId castOther = ( LogmnrcGtloId ) other; 
         
		 return ( (this.getLogmnrUid()==castOther.getLogmnrUid()) || ( this.getLogmnrUid()!=null && castOther.getLogmnrUid()!=null && this.getLogmnrUid().equals(castOther.getLogmnrUid()) ) )
 && ( (this.getKeyobj_()==castOther.getKeyobj_()) || ( this.getKeyobj_()!=null && castOther.getKeyobj_()!=null && this.getKeyobj_().equals(castOther.getKeyobj_()) ) )
 && ( (this.getBaseobjv_()==castOther.getBaseobjv_()) || ( this.getBaseobjv_()!=null && castOther.getBaseobjv_()!=null && this.getBaseobjv_().equals(castOther.getBaseobjv_()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLogmnrUid() == null ? 0 : this.getLogmnrUid().hashCode() );
         result = 37 * result + ( getKeyobj_() == null ? 0 : this.getKeyobj_().hashCode() );
         result = 37 * result + ( getBaseobjv_() == null ? 0 : this.getBaseobjv_().hashCode() );
         return result;
   }   


}


