package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.Arrays;

/**
 * LogmnrSubcoltypeId generated by hbm2java
 */
public class LogmnrSubcoltypeId  implements java.io.Serializable {


     private BigDecimal logmnrUid;
     private BigDecimal obj_;
     private BigDecimal intcol_;
     private byte[] toid;

    

	
    
    
   
    public BigDecimal getLogmnrUid() {
        return this.logmnrUid;
    }
    
    public void setLogmnrUid(BigDecimal logmnrUid) {
        this.logmnrUid = logmnrUid;
    }
    public BigDecimal getObj_() {
        return this.obj_;
    }
    
    public void setObj_(BigDecimal obj_) {
        this.obj_ = obj_;
    }
    public BigDecimal getIntcol_() {
        return this.intcol_;
    }
    
    public void setIntcol_(BigDecimal intcol_) {
        this.intcol_ = intcol_;
    }
    public byte[] getToid() {
        return this.toid;
    }
    
    public void setToid(byte[] toid) {
        this.toid = toid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LogmnrSubcoltypeId) ) return false;
		 LogmnrSubcoltypeId castOther = ( LogmnrSubcoltypeId ) other; 
         
		 return ( (this.getLogmnrUid()==castOther.getLogmnrUid()) || ( this.getLogmnrUid()!=null && castOther.getLogmnrUid()!=null && this.getLogmnrUid().equals(castOther.getLogmnrUid()) ) )
 && ( (this.getObj_()==castOther.getObj_()) || ( this.getObj_()!=null && castOther.getObj_()!=null && this.getObj_().equals(castOther.getObj_()) ) )
 && ( (this.getIntcol_()==castOther.getIntcol_()) || ( this.getIntcol_()!=null && castOther.getIntcol_()!=null && this.getIntcol_().equals(castOther.getIntcol_()) ) )
 && ( (this.getToid()==castOther.getToid()) || ( this.getToid()!=null && castOther.getToid()!=null && Arrays.equals(this.getToid(), castOther.getToid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLogmnrUid() == null ? 0 : this.getLogmnrUid().hashCode() );
         result = 37 * result + ( getObj_() == null ? 0 : this.getObj_().hashCode() );
         result = 37 * result + ( getIntcol_() == null ? 0 : this.getIntcol_().hashCode() );
         int toidHashcode = 0;
         byte[] toidProperty = this.getToid();
         if(toidProperty != null) {
             toidHashcode = 1;
             for (int i=0; i<toidProperty.length; i++) {
                 toidHashcode = 37 * toidHashcode + toidProperty[i];
             }
         }

         result = 37 * result + toidHashcode;

         return result;
   }   


}


