package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA



/**
 * LogmnrGlobal generated by hbm2java
 */
public class LogmnrGlobal  implements java.io.Serializable {


     private LogmnrGlobalId id;

    

    
   
    public LogmnrGlobalId getId() {
        return this.id;
    }
    
    public void setId(LogmnrGlobalId id) {
        this.id = id;
    }




}


