package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * LogmnrpCtasPartMap generated by hbm2java
 */
public class LogmnrpCtasPartMap  implements java.io.Serializable {


     private LogmnrpCtasPartMapId id;
     private BigDecimal baseobj_;
     private BigDecimal part_;
     private BigDecimal spare1;
     private BigDecimal spare2;
     private String spare3;

    

	
    
    
   
    public LogmnrpCtasPartMapId getId() {
        return this.id;
    }
    
    public void setId(LogmnrpCtasPartMapId id) {
        this.id = id;
    }
    public BigDecimal getBaseobj_() {
        return this.baseobj_;
    }
    
    public void setBaseobj_(BigDecimal baseobj_) {
        this.baseobj_ = baseobj_;
    }
    public BigDecimal getPart_() {
        return this.part_;
    }
    
    public void setPart_(BigDecimal part_) {
        this.part_ = part_;
    }
    public BigDecimal getSpare1() {
        return this.spare1;
    }
    
    public void setSpare1(BigDecimal spare1) {
        this.spare1 = spare1;
    }
    public BigDecimal getSpare2() {
        return this.spare2;
    }
    
    public void setSpare2(BigDecimal spare2) {
        this.spare2 = spare2;
    }
    public String getSpare3() {
        return this.spare3;
    }
    
    public void setSpare3(String spare3) {
        this.spare3 = spare3;
    }




}


