package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * LogmnrCcol generated by hbm2java
 */
public class LogmnrCcol  implements java.io.Serializable {


     private LogmnrCcolId id;
     private BigDecimal obj_;
     private BigDecimal col_;
     private BigDecimal pos_;
     private BigDecimal logmnrFlags;

    

	
    
    
   
    public LogmnrCcolId getId() {
        return this.id;
    }
    
    public void setId(LogmnrCcolId id) {
        this.id = id;
    }
    public BigDecimal getObj_() {
        return this.obj_;
    }
    
    public void setObj_(BigDecimal obj_) {
        this.obj_ = obj_;
    }
    public BigDecimal getCol_() {
        return this.col_;
    }
    
    public void setCol_(BigDecimal col_) {
        this.col_ = col_;
    }
    public BigDecimal getPos_() {
        return this.pos_;
    }
    
    public void setPos_(BigDecimal pos_) {
        this.pos_ = pos_;
    }
    public BigDecimal getLogmnrFlags() {
        return this.logmnrFlags;
    }
    
    public void setLogmnrFlags(BigDecimal logmnrFlags) {
        this.logmnrFlags = logmnrFlags;
    }




}


