package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * LogmnrGlobalId generated by hbm2java
 */
public class LogmnrGlobalId  implements java.io.Serializable {


     private BigDecimal highRecidForeign;
     private BigDecimal highRecidDeleted;
     private BigDecimal localResetScn;
     private BigDecimal localResetTimestamp;
     private BigDecimal versionTimestamp;
     private BigDecimal spare1;
     private BigDecimal spare2;
     private BigDecimal spare3;
     private String spare4;
     private Date spare5;

    

    
   
    public BigDecimal getHighRecidForeign() {
        return this.highRecidForeign;
    }
    
    public void setHighRecidForeign(BigDecimal highRecidForeign) {
        this.highRecidForeign = highRecidForeign;
    }
    public BigDecimal getHighRecidDeleted() {
        return this.highRecidDeleted;
    }
    
    public void setHighRecidDeleted(BigDecimal highRecidDeleted) {
        this.highRecidDeleted = highRecidDeleted;
    }
    public BigDecimal getLocalResetScn() {
        return this.localResetScn;
    }
    
    public void setLocalResetScn(BigDecimal localResetScn) {
        this.localResetScn = localResetScn;
    }
    public BigDecimal getLocalResetTimestamp() {
        return this.localResetTimestamp;
    }
    
    public void setLocalResetTimestamp(BigDecimal localResetTimestamp) {
        this.localResetTimestamp = localResetTimestamp;
    }
    public BigDecimal getVersionTimestamp() {
        return this.versionTimestamp;
    }
    
    public void setVersionTimestamp(BigDecimal versionTimestamp) {
        this.versionTimestamp = versionTimestamp;
    }
    public BigDecimal getSpare1() {
        return this.spare1;
    }
    
    public void setSpare1(BigDecimal spare1) {
        this.spare1 = spare1;
    }
    public BigDecimal getSpare2() {
        return this.spare2;
    }
    
    public void setSpare2(BigDecimal spare2) {
        this.spare2 = spare2;
    }
    public BigDecimal getSpare3() {
        return this.spare3;
    }
    
    public void setSpare3(BigDecimal spare3) {
        this.spare3 = spare3;
    }
    public String getSpare4() {
        return this.spare4;
    }
    
    public void setSpare4(String spare4) {
        this.spare4 = spare4;
    }
    public Date getSpare5() {
        return this.spare5;
    }
    
    public void setSpare5(Date spare5) {
        this.spare5 = spare5;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LogmnrGlobalId) ) return false;
		 LogmnrGlobalId castOther = ( LogmnrGlobalId ) other; 
         
		 return ( (this.getHighRecidForeign()==castOther.getHighRecidForeign()) || ( this.getHighRecidForeign()!=null && castOther.getHighRecidForeign()!=null && this.getHighRecidForeign().equals(castOther.getHighRecidForeign()) ) )
 && ( (this.getHighRecidDeleted()==castOther.getHighRecidDeleted()) || ( this.getHighRecidDeleted()!=null && castOther.getHighRecidDeleted()!=null && this.getHighRecidDeleted().equals(castOther.getHighRecidDeleted()) ) )
 && ( (this.getLocalResetScn()==castOther.getLocalResetScn()) || ( this.getLocalResetScn()!=null && castOther.getLocalResetScn()!=null && this.getLocalResetScn().equals(castOther.getLocalResetScn()) ) )
 && ( (this.getLocalResetTimestamp()==castOther.getLocalResetTimestamp()) || ( this.getLocalResetTimestamp()!=null && castOther.getLocalResetTimestamp()!=null && this.getLocalResetTimestamp().equals(castOther.getLocalResetTimestamp()) ) )
 && ( (this.getVersionTimestamp()==castOther.getVersionTimestamp()) || ( this.getVersionTimestamp()!=null && castOther.getVersionTimestamp()!=null && this.getVersionTimestamp().equals(castOther.getVersionTimestamp()) ) )
 && ( (this.getSpare1()==castOther.getSpare1()) || ( this.getSpare1()!=null && castOther.getSpare1()!=null && this.getSpare1().equals(castOther.getSpare1()) ) )
 && ( (this.getSpare2()==castOther.getSpare2()) || ( this.getSpare2()!=null && castOther.getSpare2()!=null && this.getSpare2().equals(castOther.getSpare2()) ) )
 && ( (this.getSpare3()==castOther.getSpare3()) || ( this.getSpare3()!=null && castOther.getSpare3()!=null && this.getSpare3().equals(castOther.getSpare3()) ) )
 && ( (this.getSpare4()==castOther.getSpare4()) || ( this.getSpare4()!=null && castOther.getSpare4()!=null && this.getSpare4().equals(castOther.getSpare4()) ) )
 && ( (this.getSpare5()==castOther.getSpare5()) || ( this.getSpare5()!=null && castOther.getSpare5()!=null && this.getSpare5().equals(castOther.getSpare5()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getHighRecidForeign() == null ? 0 : this.getHighRecidForeign().hashCode() );
         result = 37 * result + ( getHighRecidDeleted() == null ? 0 : this.getHighRecidDeleted().hashCode() );
         result = 37 * result + ( getLocalResetScn() == null ? 0 : this.getLocalResetScn().hashCode() );
         result = 37 * result + ( getLocalResetTimestamp() == null ? 0 : this.getLocalResetTimestamp().hashCode() );
         result = 37 * result + ( getVersionTimestamp() == null ? 0 : this.getVersionTimestamp().hashCode() );
         result = 37 * result + ( getSpare1() == null ? 0 : this.getSpare1().hashCode() );
         result = 37 * result + ( getSpare2() == null ? 0 : this.getSpare2().hashCode() );
         result = 37 * result + ( getSpare3() == null ? 0 : this.getSpare3().hashCode() );
         result = 37 * result + ( getSpare4() == null ? 0 : this.getSpare4().hashCode() );
         result = 37 * result + ( getSpare5() == null ? 0 : this.getSpare5().hashCode() );
         return result;
   }   


}


