package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * LogmnrEnc generated by hbm2java
 */
public class LogmnrEnc  implements java.io.Serializable {


     private LogmnrEncId id;
     private BigDecimal encalg;
     private BigDecimal intalg;
     private byte[] colklc;
     private BigDecimal klclen;
     private BigDecimal flag;
     private String mkeyid;
     private BigDecimal logmnrFlags;

    

	
    
    
   
    public LogmnrEncId getId() {
        return this.id;
    }
    
    public void setId(LogmnrEncId id) {
        this.id = id;
    }
    public BigDecimal getEncalg() {
        return this.encalg;
    }
    
    public void setEncalg(BigDecimal encalg) {
        this.encalg = encalg;
    }
    public BigDecimal getIntalg() {
        return this.intalg;
    }
    
    public void setIntalg(BigDecimal intalg) {
        this.intalg = intalg;
    }
    public byte[] getColklc() {
        return this.colklc;
    }
    
    public void setColklc(byte[] colklc) {
        this.colklc = colklc;
    }
    public BigDecimal getKlclen() {
        return this.klclen;
    }
    
    public void setKlclen(BigDecimal klclen) {
        this.klclen = klclen;
    }
    public BigDecimal getFlag() {
        return this.flag;
    }
    
    public void setFlag(BigDecimal flag) {
        this.flag = flag;
    }
    public String getMkeyid() {
        return this.mkeyid;
    }
    
    public void setMkeyid(String mkeyid) {
        this.mkeyid = mkeyid;
    }
    public BigDecimal getLogmnrFlags() {
        return this.logmnrFlags;
    }
    
    public void setLogmnrFlags(BigDecimal logmnrFlags) {
        this.logmnrFlags = logmnrFlags;
    }




}


