package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * LogmnrSeed generated by hbm2java
 */
public class LogmnrSeed  implements java.io.Serializable {


     private LogmnrSeedId id;
     private BigDecimal seedVersion;
     private BigDecimal gatherVersion;
     private String schemaname;
     private BigDecimal objv_;
     private String tableName;
     private String colName;
     private BigDecimal col_;
     private BigDecimal segcol_;
     private BigDecimal type_;
     private BigDecimal length;
     private BigDecimal precision_;
     private BigDecimal scale;
     private BigDecimal null;
     private BigDecimal logmnrFlags;

    

	
    
    
   
    public LogmnrSeedId getId() {
        return this.id;
    }
    
    public void setId(LogmnrSeedId id) {
        this.id = id;
    }
    public BigDecimal getSeedVersion() {
        return this.seedVersion;
    }
    
    public void setSeedVersion(BigDecimal seedVersion) {
        this.seedVersion = seedVersion;
    }
    public BigDecimal getGatherVersion() {
        return this.gatherVersion;
    }
    
    public void setGatherVersion(BigDecimal gatherVersion) {
        this.gatherVersion = gatherVersion;
    }
    public String getSchemaname() {
        return this.schemaname;
    }
    
    public void setSchemaname(String schemaname) {
        this.schemaname = schemaname;
    }
    public BigDecimal getObjv_() {
        return this.objv_;
    }
    
    public void setObjv_(BigDecimal objv_) {
        this.objv_ = objv_;
    }
    public String getTableName() {
        return this.tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }
    public String getColName() {
        return this.colName;
    }
    
    public void setColName(String colName) {
        this.colName = colName;
    }
    public BigDecimal getCol_() {
        return this.col_;
    }
    
    public void setCol_(BigDecimal col_) {
        this.col_ = col_;
    }
    public BigDecimal getSegcol_() {
        return this.segcol_;
    }
    
    public void setSegcol_(BigDecimal segcol_) {
        this.segcol_ = segcol_;
    }
    public BigDecimal getType_() {
        return this.type_;
    }
    
    public void setType_(BigDecimal type_) {
        this.type_ = type_;
    }
    public BigDecimal getLength() {
        return this.length;
    }
    
    public void setLength(BigDecimal length) {
        this.length = length;
    }
    public BigDecimal getPrecision_() {
        return this.precision_;
    }
    
    public void setPrecision_(BigDecimal precision_) {
        this.precision_ = precision_;
    }
    public BigDecimal getScale() {
        return this.scale;
    }
    
    public void setScale(BigDecimal scale) {
        this.scale = scale;
    }
    public BigDecimal getNull() {
        return this.null;
    }
    
    public void setNull(BigDecimal null) {
        this.null = null;
    }
    public BigDecimal getLogmnrFlags() {
        return this.logmnrFlags;
    }
    
    public void setLogmnrFlags(BigDecimal logmnrFlags) {
        this.logmnrFlags = logmnrFlags;
    }




}


