package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * LogmnrRestartCkptTxinfoId generated by hbm2java
 */
public class LogmnrRestartCkptTxinfoId  implements java.io.Serializable {


     private BigDecimal session_;
     private BigDecimal xidusn;
     private BigDecimal xidslt;
     private BigDecimal xidsqn;
     private BigDecimal sessionNum;
     private BigDecimal serialNum;
     private BigDecimal effectiveScn;

    

    
   
    public BigDecimal getSession_() {
        return this.session_;
    }
    
    public void setSession_(BigDecimal session_) {
        this.session_ = session_;
    }
    public BigDecimal getXidusn() {
        return this.xidusn;
    }
    
    public void setXidusn(BigDecimal xidusn) {
        this.xidusn = xidusn;
    }
    public BigDecimal getXidslt() {
        return this.xidslt;
    }
    
    public void setXidslt(BigDecimal xidslt) {
        this.xidslt = xidslt;
    }
    public BigDecimal getXidsqn() {
        return this.xidsqn;
    }
    
    public void setXidsqn(BigDecimal xidsqn) {
        this.xidsqn = xidsqn;
    }
    public BigDecimal getSessionNum() {
        return this.sessionNum;
    }
    
    public void setSessionNum(BigDecimal sessionNum) {
        this.sessionNum = sessionNum;
    }
    public BigDecimal getSerialNum() {
        return this.serialNum;
    }
    
    public void setSerialNum(BigDecimal serialNum) {
        this.serialNum = serialNum;
    }
    public BigDecimal getEffectiveScn() {
        return this.effectiveScn;
    }
    
    public void setEffectiveScn(BigDecimal effectiveScn) {
        this.effectiveScn = effectiveScn;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LogmnrRestartCkptTxinfoId) ) return false;
		 LogmnrRestartCkptTxinfoId castOther = ( LogmnrRestartCkptTxinfoId ) other; 
         
		 return ( (this.getSession_()==castOther.getSession_()) || ( this.getSession_()!=null && castOther.getSession_()!=null && this.getSession_().equals(castOther.getSession_()) ) )
 && ( (this.getXidusn()==castOther.getXidusn()) || ( this.getXidusn()!=null && castOther.getXidusn()!=null && this.getXidusn().equals(castOther.getXidusn()) ) )
 && ( (this.getXidslt()==castOther.getXidslt()) || ( this.getXidslt()!=null && castOther.getXidslt()!=null && this.getXidslt().equals(castOther.getXidslt()) ) )
 && ( (this.getXidsqn()==castOther.getXidsqn()) || ( this.getXidsqn()!=null && castOther.getXidsqn()!=null && this.getXidsqn().equals(castOther.getXidsqn()) ) )
 && ( (this.getSessionNum()==castOther.getSessionNum()) || ( this.getSessionNum()!=null && castOther.getSessionNum()!=null && this.getSessionNum().equals(castOther.getSessionNum()) ) )
 && ( (this.getSerialNum()==castOther.getSerialNum()) || ( this.getSerialNum()!=null && castOther.getSerialNum()!=null && this.getSerialNum().equals(castOther.getSerialNum()) ) )
 && ( (this.getEffectiveScn()==castOther.getEffectiveScn()) || ( this.getEffectiveScn()!=null && castOther.getEffectiveScn()!=null && this.getEffectiveScn().equals(castOther.getEffectiveScn()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSession_() == null ? 0 : this.getSession_().hashCode() );
         result = 37 * result + ( getXidusn() == null ? 0 : this.getXidusn().hashCode() );
         result = 37 * result + ( getXidslt() == null ? 0 : this.getXidslt().hashCode() );
         result = 37 * result + ( getXidsqn() == null ? 0 : this.getXidsqn().hashCode() );
         result = 37 * result + ( getSessionNum() == null ? 0 : this.getSessionNum().hashCode() );
         result = 37 * result + ( getSerialNum() == null ? 0 : this.getSerialNum().hashCode() );
         result = 37 * result + ( getEffectiveScn() == null ? 0 : this.getEffectiveScn().hashCode() );
         return result;
   }   


}


