package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * LogmnrAttribute generated by hbm2java
 */
public class LogmnrAttribute  implements java.io.Serializable {


     private LogmnrAttributeId id;
     private String name;
     private byte[] attrToid;
     private BigDecimal attrVersion_;
     private BigDecimal synobj_;
     private BigDecimal properties;
     private BigDecimal charsetid;
     private BigDecimal charsetform;
     private BigDecimal length;
     private BigDecimal precision_;
     private BigDecimal scale;
     private String externname;
     private BigDecimal xflags;
     private BigDecimal spare1;
     private BigDecimal spare2;
     private BigDecimal spare3;
     private BigDecimal spare4;
     private BigDecimal spare5;
     private BigDecimal setter;
     private BigDecimal getter;
     private BigDecimal logmnrFlags;

    

	
    
    
   
    public LogmnrAttributeId getId() {
        return this.id;
    }
    
    public void setId(LogmnrAttributeId id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public byte[] getAttrToid() {
        return this.attrToid;
    }
    
    public void setAttrToid(byte[] attrToid) {
        this.attrToid = attrToid;
    }
    public BigDecimal getAttrVersion_() {
        return this.attrVersion_;
    }
    
    public void setAttrVersion_(BigDecimal attrVersion_) {
        this.attrVersion_ = attrVersion_;
    }
    public BigDecimal getSynobj_() {
        return this.synobj_;
    }
    
    public void setSynobj_(BigDecimal synobj_) {
        this.synobj_ = synobj_;
    }
    public BigDecimal getProperties() {
        return this.properties;
    }
    
    public void setProperties(BigDecimal properties) {
        this.properties = properties;
    }
    public BigDecimal getCharsetid() {
        return this.charsetid;
    }
    
    public void setCharsetid(BigDecimal charsetid) {
        this.charsetid = charsetid;
    }
    public BigDecimal getCharsetform() {
        return this.charsetform;
    }
    
    public void setCharsetform(BigDecimal charsetform) {
        this.charsetform = charsetform;
    }
    public BigDecimal getLength() {
        return this.length;
    }
    
    public void setLength(BigDecimal length) {
        this.length = length;
    }
    public BigDecimal getPrecision_() {
        return this.precision_;
    }
    
    public void setPrecision_(BigDecimal precision_) {
        this.precision_ = precision_;
    }
    public BigDecimal getScale() {
        return this.scale;
    }
    
    public void setScale(BigDecimal scale) {
        this.scale = scale;
    }
    public String getExternname() {
        return this.externname;
    }
    
    public void setExternname(String externname) {
        this.externname = externname;
    }
    public BigDecimal getXflags() {
        return this.xflags;
    }
    
    public void setXflags(BigDecimal xflags) {
        this.xflags = xflags;
    }
    public BigDecimal getSpare1() {
        return this.spare1;
    }
    
    public void setSpare1(BigDecimal spare1) {
        this.spare1 = spare1;
    }
    public BigDecimal getSpare2() {
        return this.spare2;
    }
    
    public void setSpare2(BigDecimal spare2) {
        this.spare2 = spare2;
    }
    public BigDecimal getSpare3() {
        return this.spare3;
    }
    
    public void setSpare3(BigDecimal spare3) {
        this.spare3 = spare3;
    }
    public BigDecimal getSpare4() {
        return this.spare4;
    }
    
    public void setSpare4(BigDecimal spare4) {
        this.spare4 = spare4;
    }
    public BigDecimal getSpare5() {
        return this.spare5;
    }
    
    public void setSpare5(BigDecimal spare5) {
        this.spare5 = spare5;
    }
    public BigDecimal getSetter() {
        return this.setter;
    }
    
    public void setSetter(BigDecimal setter) {
        this.setter = setter;
    }
    public BigDecimal getGetter() {
        return this.getter;
    }
    
    public void setGetter(BigDecimal getter) {
        this.getter = getter;
    }
    public BigDecimal getLogmnrFlags() {
        return this.logmnrFlags;
    }
    
    public void setLogmnrFlags(BigDecimal logmnrFlags) {
        this.logmnrFlags = logmnrFlags;
    }




}


