package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.sql.Blob;

/**
 * LogmnrRestartCkptTxinfo generated by hbm2java
 */
public class LogmnrRestartCkptTxinfo  implements java.io.Serializable {


     private LogmnrRestartCkptTxinfoId id;
     private BigDecimal flag;
     private BigDecimal startScn;
     private BigDecimal offset;
     private Blob txData;

    

	
    
    
   
    public LogmnrRestartCkptTxinfoId getId() {
        return this.id;
    }
    
    public void setId(LogmnrRestartCkptTxinfoId id) {
        this.id = id;
    }
    public BigDecimal getFlag() {
        return this.flag;
    }
    
    public void setFlag(BigDecimal flag) {
        this.flag = flag;
    }
    public BigDecimal getStartScn() {
        return this.startScn;
    }
    
    public void setStartScn(BigDecimal startScn) {
        this.startScn = startScn;
    }
    public BigDecimal getOffset() {
        return this.offset;
    }
    
    public void setOffset(BigDecimal offset) {
        this.offset = offset;
    }
    public Blob getTxData() {
        return this.txData;
    }
    
    public void setTxData(Blob txData) {
        this.txData = txData;
    }




}


