package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * LogmnrcGtcs generated by hbm2java
 */
public class LogmnrcGtcs  implements java.io.Serializable {


     private LogmnrcGtcsId id;
     private BigDecimal segcol_;
     private String colname;
     private BigDecimal type_;
     private BigDecimal length;
     private BigDecimal precision;
     private BigDecimal scale;
     private BigDecimal intervalLeadingPrecision;
     private BigDecimal intervalTrailingPrecision;
     private BigDecimal property;
     private byte[] toid;
     private BigDecimal charsetid;
     private BigDecimal charsetform;
     private String typename;
     private String fqcolname;
     private BigDecimal numintcols;
     private BigDecimal numattrs;
     private BigDecimal adtorder;
     private BigDecimal logmnrSpare1;
     private BigDecimal logmnrSpare2;
     private String logmnrSpare3;
     private Date logmnrSpare4;
     private BigDecimal logmnrSpare5;
     private BigDecimal logmnrSpare6;
     private BigDecimal logmnrSpare7;
     private BigDecimal logmnrSpare8;
     private BigDecimal logmnrSpare9;
     private BigDecimal col_;
     private String xtypeschemaname;
     private String xtypename;
     private String xfqcolname;
     private BigDecimal xtopintcol;
     private BigDecimal xreffedtableobjn;
     private BigDecimal xreffedtableobjv;
     private BigDecimal xcoltypeflags;
     private BigDecimal xopqtypetype;
     private BigDecimal xopqtypeflags;
     private BigDecimal xopqlobintcol;
     private BigDecimal xopqobjintcol;
     private BigDecimal xxmlintcol;
     private BigDecimal eaowner_;
     private String eamkeyid;
     private BigDecimal eaencalg;
     private BigDecimal eaintalg;
     private byte[] eacolklc;
     private BigDecimal eaklclen;
     private BigDecimal eaflags;

    

	
    
    
   
    public LogmnrcGtcsId getId() {
        return this.id;
    }
    
    public void setId(LogmnrcGtcsId id) {
        this.id = id;
    }
    public BigDecimal getSegcol_() {
        return this.segcol_;
    }
    
    public void setSegcol_(BigDecimal segcol_) {
        this.segcol_ = segcol_;
    }
    public String getColname() {
        return this.colname;
    }
    
    public void setColname(String colname) {
        this.colname = colname;
    }
    public BigDecimal getType_() {
        return this.type_;
    }
    
    public void setType_(BigDecimal type_) {
        this.type_ = type_;
    }
    public BigDecimal getLength() {
        return this.length;
    }
    
    public void setLength(BigDecimal length) {
        this.length = length;
    }
    public BigDecimal getPrecision() {
        return this.precision;
    }
    
    public void setPrecision(BigDecimal precision) {
        this.precision = precision;
    }
    public BigDecimal getScale() {
        return this.scale;
    }
    
    public void setScale(BigDecimal scale) {
        this.scale = scale;
    }
    public BigDecimal getIntervalLeadingPrecision() {
        return this.intervalLeadingPrecision;
    }
    
    public void setIntervalLeadingPrecision(BigDecimal intervalLeadingPrecision) {
        this.intervalLeadingPrecision = intervalLeadingPrecision;
    }
    public BigDecimal getIntervalTrailingPrecision() {
        return this.intervalTrailingPrecision;
    }
    
    public void setIntervalTrailingPrecision(BigDecimal intervalTrailingPrecision) {
        this.intervalTrailingPrecision = intervalTrailingPrecision;
    }
    public BigDecimal getProperty() {
        return this.property;
    }
    
    public void setProperty(BigDecimal property) {
        this.property = property;
    }
    public byte[] getToid() {
        return this.toid;
    }
    
    public void setToid(byte[] toid) {
        this.toid = toid;
    }
    public BigDecimal getCharsetid() {
        return this.charsetid;
    }
    
    public void setCharsetid(BigDecimal charsetid) {
        this.charsetid = charsetid;
    }
    public BigDecimal getCharsetform() {
        return this.charsetform;
    }
    
    public void setCharsetform(BigDecimal charsetform) {
        this.charsetform = charsetform;
    }
    public String getTypename() {
        return this.typename;
    }
    
    public void setTypename(String typename) {
        this.typename = typename;
    }
    public String getFqcolname() {
        return this.fqcolname;
    }
    
    public void setFqcolname(String fqcolname) {
        this.fqcolname = fqcolname;
    }
    public BigDecimal getNumintcols() {
        return this.numintcols;
    }
    
    public void setNumintcols(BigDecimal numintcols) {
        this.numintcols = numintcols;
    }
    public BigDecimal getNumattrs() {
        return this.numattrs;
    }
    
    public void setNumattrs(BigDecimal numattrs) {
        this.numattrs = numattrs;
    }
    public BigDecimal getAdtorder() {
        return this.adtorder;
    }
    
    public void setAdtorder(BigDecimal adtorder) {
        this.adtorder = adtorder;
    }
    public BigDecimal getLogmnrSpare1() {
        return this.logmnrSpare1;
    }
    
    public void setLogmnrSpare1(BigDecimal logmnrSpare1) {
        this.logmnrSpare1 = logmnrSpare1;
    }
    public BigDecimal getLogmnrSpare2() {
        return this.logmnrSpare2;
    }
    
    public void setLogmnrSpare2(BigDecimal logmnrSpare2) {
        this.logmnrSpare2 = logmnrSpare2;
    }
    public String getLogmnrSpare3() {
        return this.logmnrSpare3;
    }
    
    public void setLogmnrSpare3(String logmnrSpare3) {
        this.logmnrSpare3 = logmnrSpare3;
    }
    public Date getLogmnrSpare4() {
        return this.logmnrSpare4;
    }
    
    public void setLogmnrSpare4(Date logmnrSpare4) {
        this.logmnrSpare4 = logmnrSpare4;
    }
    public BigDecimal getLogmnrSpare5() {
        return this.logmnrSpare5;
    }
    
    public void setLogmnrSpare5(BigDecimal logmnrSpare5) {
        this.logmnrSpare5 = logmnrSpare5;
    }
    public BigDecimal getLogmnrSpare6() {
        return this.logmnrSpare6;
    }
    
    public void setLogmnrSpare6(BigDecimal logmnrSpare6) {
        this.logmnrSpare6 = logmnrSpare6;
    }
    public BigDecimal getLogmnrSpare7() {
        return this.logmnrSpare7;
    }
    
    public void setLogmnrSpare7(BigDecimal logmnrSpare7) {
        this.logmnrSpare7 = logmnrSpare7;
    }
    public BigDecimal getLogmnrSpare8() {
        return this.logmnrSpare8;
    }
    
    public void setLogmnrSpare8(BigDecimal logmnrSpare8) {
        this.logmnrSpare8 = logmnrSpare8;
    }
    public BigDecimal getLogmnrSpare9() {
        return this.logmnrSpare9;
    }
    
    public void setLogmnrSpare9(BigDecimal logmnrSpare9) {
        this.logmnrSpare9 = logmnrSpare9;
    }
    public BigDecimal getCol_() {
        return this.col_;
    }
    
    public void setCol_(BigDecimal col_) {
        this.col_ = col_;
    }
    public String getXtypeschemaname() {
        return this.xtypeschemaname;
    }
    
    public void setXtypeschemaname(String xtypeschemaname) {
        this.xtypeschemaname = xtypeschemaname;
    }
    public String getXtypename() {
        return this.xtypename;
    }
    
    public void setXtypename(String xtypename) {
        this.xtypename = xtypename;
    }
    public String getXfqcolname() {
        return this.xfqcolname;
    }
    
    public void setXfqcolname(String xfqcolname) {
        this.xfqcolname = xfqcolname;
    }
    public BigDecimal getXtopintcol() {
        return this.xtopintcol;
    }
    
    public void setXtopintcol(BigDecimal xtopintcol) {
        this.xtopintcol = xtopintcol;
    }
    public BigDecimal getXreffedtableobjn() {
        return this.xreffedtableobjn;
    }
    
    public void setXreffedtableobjn(BigDecimal xreffedtableobjn) {
        this.xreffedtableobjn = xreffedtableobjn;
    }
    public BigDecimal getXreffedtableobjv() {
        return this.xreffedtableobjv;
    }
    
    public void setXreffedtableobjv(BigDecimal xreffedtableobjv) {
        this.xreffedtableobjv = xreffedtableobjv;
    }
    public BigDecimal getXcoltypeflags() {
        return this.xcoltypeflags;
    }
    
    public void setXcoltypeflags(BigDecimal xcoltypeflags) {
        this.xcoltypeflags = xcoltypeflags;
    }
    public BigDecimal getXopqtypetype() {
        return this.xopqtypetype;
    }
    
    public void setXopqtypetype(BigDecimal xopqtypetype) {
        this.xopqtypetype = xopqtypetype;
    }
    public BigDecimal getXopqtypeflags() {
        return this.xopqtypeflags;
    }
    
    public void setXopqtypeflags(BigDecimal xopqtypeflags) {
        this.xopqtypeflags = xopqtypeflags;
    }
    public BigDecimal getXopqlobintcol() {
        return this.xopqlobintcol;
    }
    
    public void setXopqlobintcol(BigDecimal xopqlobintcol) {
        this.xopqlobintcol = xopqlobintcol;
    }
    public BigDecimal getXopqobjintcol() {
        return this.xopqobjintcol;
    }
    
    public void setXopqobjintcol(BigDecimal xopqobjintcol) {
        this.xopqobjintcol = xopqobjintcol;
    }
    public BigDecimal getXxmlintcol() {
        return this.xxmlintcol;
    }
    
    public void setXxmlintcol(BigDecimal xxmlintcol) {
        this.xxmlintcol = xxmlintcol;
    }
    public BigDecimal getEaowner_() {
        return this.eaowner_;
    }
    
    public void setEaowner_(BigDecimal eaowner_) {
        this.eaowner_ = eaowner_;
    }
    public String getEamkeyid() {
        return this.eamkeyid;
    }
    
    public void setEamkeyid(String eamkeyid) {
        this.eamkeyid = eamkeyid;
    }
    public BigDecimal getEaencalg() {
        return this.eaencalg;
    }
    
    public void setEaencalg(BigDecimal eaencalg) {
        this.eaencalg = eaencalg;
    }
    public BigDecimal getEaintalg() {
        return this.eaintalg;
    }
    
    public void setEaintalg(BigDecimal eaintalg) {
        this.eaintalg = eaintalg;
    }
    public byte[] getEacolklc() {
        return this.eacolklc;
    }
    
    public void setEacolklc(byte[] eacolklc) {
        this.eacolklc = eacolklc;
    }
    public BigDecimal getEaklclen() {
        return this.eaklclen;
    }
    
    public void setEaklclen(BigDecimal eaklclen) {
        this.eaklclen = eaklclen;
    }
    public BigDecimal getEaflags() {
        return this.eaflags;
    }
    
    public void setEaflags(BigDecimal eaflags) {
        this.eaflags = eaflags;
    }




}


