package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * LogmnrSessionActions generated by hbm2java
 */
public class LogmnrSessionActions  implements java.io.Serializable {


     private LogmnrSessionActionsId id;
     private BigDecimal flagsruntime;
     private BigDecimal dropscn;
     private Date modifytime;
     private Date dispatchtime;
     private Date droptime;
     private BigDecimal lcrcount;
     private BigDecimal processrole_;
     private BigDecimal actiontype_;
     private BigDecimal flagsdefinetime;
     private Date createtime;
     private BigDecimal xidusn;
     private BigDecimal xidslt;
     private BigDecimal xidsqn;
     private BigDecimal thread_;
     private BigDecimal startscn;
     private BigDecimal startsubscn;
     private BigDecimal endscn;
     private BigDecimal endsubscn;
     private BigDecimal rbasqn;
     private BigDecimal rbablk;
     private BigDecimal rbabyte;
     private BigDecimal session_;
     private BigDecimal obj_;
     private BigDecimal attr1;
     private BigDecimal attr2;
     private BigDecimal attr3;
     private BigDecimal spare1;
     private BigDecimal spare2;
     private Date spare3;
     private String spare4;

    

	
    
    
   
    public LogmnrSessionActionsId getId() {
        return this.id;
    }
    
    public void setId(LogmnrSessionActionsId id) {
        this.id = id;
    }
    public BigDecimal getFlagsruntime() {
        return this.flagsruntime;
    }
    
    public void setFlagsruntime(BigDecimal flagsruntime) {
        this.flagsruntime = flagsruntime;
    }
    public BigDecimal getDropscn() {
        return this.dropscn;
    }
    
    public void setDropscn(BigDecimal dropscn) {
        this.dropscn = dropscn;
    }
    public Date getModifytime() {
        return this.modifytime;
    }
    
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }
    public Date getDispatchtime() {
        return this.dispatchtime;
    }
    
    public void setDispatchtime(Date dispatchtime) {
        this.dispatchtime = dispatchtime;
    }
    public Date getDroptime() {
        return this.droptime;
    }
    
    public void setDroptime(Date droptime) {
        this.droptime = droptime;
    }
    public BigDecimal getLcrcount() {
        return this.lcrcount;
    }
    
    public void setLcrcount(BigDecimal lcrcount) {
        this.lcrcount = lcrcount;
    }
    public BigDecimal getProcessrole_() {
        return this.processrole_;
    }
    
    public void setProcessrole_(BigDecimal processrole_) {
        this.processrole_ = processrole_;
    }
    public BigDecimal getActiontype_() {
        return this.actiontype_;
    }
    
    public void setActiontype_(BigDecimal actiontype_) {
        this.actiontype_ = actiontype_;
    }
    public BigDecimal getFlagsdefinetime() {
        return this.flagsdefinetime;
    }
    
    public void setFlagsdefinetime(BigDecimal flagsdefinetime) {
        this.flagsdefinetime = flagsdefinetime;
    }
    public Date getCreatetime() {
        return this.createtime;
    }
    
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
    public BigDecimal getXidusn() {
        return this.xidusn;
    }
    
    public void setXidusn(BigDecimal xidusn) {
        this.xidusn = xidusn;
    }
    public BigDecimal getXidslt() {
        return this.xidslt;
    }
    
    public void setXidslt(BigDecimal xidslt) {
        this.xidslt = xidslt;
    }
    public BigDecimal getXidsqn() {
        return this.xidsqn;
    }
    
    public void setXidsqn(BigDecimal xidsqn) {
        this.xidsqn = xidsqn;
    }
    public BigDecimal getThread_() {
        return this.thread_;
    }
    
    public void setThread_(BigDecimal thread_) {
        this.thread_ = thread_;
    }
    public BigDecimal getStartscn() {
        return this.startscn;
    }
    
    public void setStartscn(BigDecimal startscn) {
        this.startscn = startscn;
    }
    public BigDecimal getStartsubscn() {
        return this.startsubscn;
    }
    
    public void setStartsubscn(BigDecimal startsubscn) {
        this.startsubscn = startsubscn;
    }
    public BigDecimal getEndscn() {
        return this.endscn;
    }
    
    public void setEndscn(BigDecimal endscn) {
        this.endscn = endscn;
    }
    public BigDecimal getEndsubscn() {
        return this.endsubscn;
    }
    
    public void setEndsubscn(BigDecimal endsubscn) {
        this.endsubscn = endsubscn;
    }
    public BigDecimal getRbasqn() {
        return this.rbasqn;
    }
    
    public void setRbasqn(BigDecimal rbasqn) {
        this.rbasqn = rbasqn;
    }
    public BigDecimal getRbablk() {
        return this.rbablk;
    }
    
    public void setRbablk(BigDecimal rbablk) {
        this.rbablk = rbablk;
    }
    public BigDecimal getRbabyte() {
        return this.rbabyte;
    }
    
    public void setRbabyte(BigDecimal rbabyte) {
        this.rbabyte = rbabyte;
    }
    public BigDecimal getSession_() {
        return this.session_;
    }
    
    public void setSession_(BigDecimal session_) {
        this.session_ = session_;
    }
    public BigDecimal getObj_() {
        return this.obj_;
    }
    
    public void setObj_(BigDecimal obj_) {
        this.obj_ = obj_;
    }
    public BigDecimal getAttr1() {
        return this.attr1;
    }
    
    public void setAttr1(BigDecimal attr1) {
        this.attr1 = attr1;
    }
    public BigDecimal getAttr2() {
        return this.attr2;
    }
    
    public void setAttr2(BigDecimal attr2) {
        this.attr2 = attr2;
    }
    public BigDecimal getAttr3() {
        return this.attr3;
    }
    
    public void setAttr3(BigDecimal attr3) {
        this.attr3 = attr3;
    }
    public BigDecimal getSpare1() {
        return this.spare1;
    }
    
    public void setSpare1(BigDecimal spare1) {
        this.spare1 = spare1;
    }
    public BigDecimal getSpare2() {
        return this.spare2;
    }
    
    public void setSpare2(BigDecimal spare2) {
        this.spare2 = spare2;
    }
    public Date getSpare3() {
        return this.spare3;
    }
    
    public void setSpare3(Date spare3) {
        this.spare3 = spare3;
    }
    public String getSpare4() {
        return this.spare4;
    }
    
    public void setSpare4(String spare4) {
        this.spare4 = spare4;
    }




}


