package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * LogmnrLogmnrBuildlogId generated by hbm2java
 */
public class LogmnrLogmnrBuildlogId  implements java.io.Serializable {


     private BigDecimal logmnrUid;
     private String initialXid;

    

	
    
    
   
    public BigDecimal getLogmnrUid() {
        return this.logmnrUid;
    }
    
    public void setLogmnrUid(BigDecimal logmnrUid) {
        this.logmnrUid = logmnrUid;
    }
    public String getInitialXid() {
        return this.initialXid;
    }
    
    public void setInitialXid(String initialXid) {
        this.initialXid = initialXid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LogmnrLogmnrBuildlogId) ) return false;
		 LogmnrLogmnrBuildlogId castOther = ( LogmnrLogmnrBuildlogId ) other; 
         
		 return ( (this.getLogmnrUid()==castOther.getLogmnrUid()) || ( this.getLogmnrUid()!=null && castOther.getLogmnrUid()!=null && this.getLogmnrUid().equals(castOther.getLogmnrUid()) ) )
 && ( (this.getInitialXid()==castOther.getInitialXid()) || ( this.getInitialXid()!=null && castOther.getInitialXid()!=null && this.getInitialXid().equals(castOther.getInitialXid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLogmnrUid() == null ? 0 : this.getLogmnrUid().hashCode() );
         result = 37 * result + ( getInitialXid() == null ? 0 : this.getInitialXid().hashCode() );
         return result;
   }   


}


