package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * LogmnrIcol generated by hbm2java
 */
public class LogmnrIcol  implements java.io.Serializable {


     private LogmnrIcolId id;
     private BigDecimal bo_;
     private BigDecimal col_;
     private BigDecimal pos_;
     private BigDecimal segcol_;
     private BigDecimal logmnrFlags;

    

	
    
    
   
    public LogmnrIcolId getId() {
        return this.id;
    }
    
    public void setId(LogmnrIcolId id) {
        this.id = id;
    }
    public BigDecimal getBo_() {
        return this.bo_;
    }
    
    public void setBo_(BigDecimal bo_) {
        this.bo_ = bo_;
    }
    public BigDecimal getCol_() {
        return this.col_;
    }
    
    public void setCol_(BigDecimal col_) {
        this.col_ = col_;
    }
    public BigDecimal getPos_() {
        return this.pos_;
    }
    
    public void setPos_(BigDecimal pos_) {
        this.pos_ = pos_;
    }
    public BigDecimal getSegcol_() {
        return this.segcol_;
    }
    
    public void setSegcol_(BigDecimal segcol_) {
        this.segcol_ = segcol_;
    }
    public BigDecimal getLogmnrFlags() {
        return this.logmnrFlags;
    }
    
    public void setLogmnrFlags(BigDecimal logmnrFlags) {
        this.logmnrFlags = logmnrFlags;
    }




}


