package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * LogmnrCdef generated by hbm2java
 */
public class LogmnrCdef  implements java.io.Serializable {


     private LogmnrCdefId id;
     private BigDecimal cols;
     private BigDecimal type_;
     private BigDecimal robj_;
     private BigDecimal rcon_;
     private BigDecimal enabled;
     private BigDecimal defer;
     private BigDecimal obj_;
     private BigDecimal logmnrFlags;

    

	
    
    
   
    public LogmnrCdefId getId() {
        return this.id;
    }
    
    public void setId(LogmnrCdefId id) {
        this.id = id;
    }
    public BigDecimal getCols() {
        return this.cols;
    }
    
    public void setCols(BigDecimal cols) {
        this.cols = cols;
    }
    public BigDecimal getType_() {
        return this.type_;
    }
    
    public void setType_(BigDecimal type_) {
        this.type_ = type_;
    }
    public BigDecimal getRobj_() {
        return this.robj_;
    }
    
    public void setRobj_(BigDecimal robj_) {
        this.robj_ = robj_;
    }
    public BigDecimal getRcon_() {
        return this.rcon_;
    }
    
    public void setRcon_(BigDecimal rcon_) {
        this.rcon_ = rcon_;
    }
    public BigDecimal getEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(BigDecimal enabled) {
        this.enabled = enabled;
    }
    public BigDecimal getDefer() {
        return this.defer;
    }
    
    public void setDefer(BigDecimal defer) {
        this.defer = defer;
    }
    public BigDecimal getObj_() {
        return this.obj_;
    }
    
    public void setObj_(BigDecimal obj_) {
        this.obj_ = obj_;
    }
    public BigDecimal getLogmnrFlags() {
        return this.logmnrFlags;
    }
    
    public void setLogmnrFlags(BigDecimal logmnrFlags) {
        this.logmnrFlags = logmnrFlags;
    }




}


