package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.sql.Clob;

/**
 * LogstdbyplsqlId generated by hbm2java
 */
public class LogstdbyplsqlId  implements java.io.Serializable {


     private BigDecimal sessionId;
     private BigDecimal startFinish;
     private Clob callText;
     private BigDecimal spare1;
     private BigDecimal spare2;
     private String spare3;

    

    
   
    public BigDecimal getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(BigDecimal sessionId) {
        this.sessionId = sessionId;
    }
    public BigDecimal getStartFinish() {
        return this.startFinish;
    }
    
    public void setStartFinish(BigDecimal startFinish) {
        this.startFinish = startFinish;
    }
    public Clob getCallText() {
        return this.callText;
    }
    
    public void setCallText(Clob callText) {
        this.callText = callText;
    }
    public BigDecimal getSpare1() {
        return this.spare1;
    }
    
    public void setSpare1(BigDecimal spare1) {
        this.spare1 = spare1;
    }
    public BigDecimal getSpare2() {
        return this.spare2;
    }
    
    public void setSpare2(BigDecimal spare2) {
        this.spare2 = spare2;
    }
    public String getSpare3() {
        return this.spare3;
    }
    
    public void setSpare3(String spare3) {
        this.spare3 = spare3;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LogstdbyplsqlId) ) return false;
		 LogstdbyplsqlId castOther = ( LogstdbyplsqlId ) other; 
         
		 return ( (this.getSessionId()==castOther.getSessionId()) || ( this.getSessionId()!=null && castOther.getSessionId()!=null && this.getSessionId().equals(castOther.getSessionId()) ) )
 && ( (this.getStartFinish()==castOther.getStartFinish()) || ( this.getStartFinish()!=null && castOther.getStartFinish()!=null && this.getStartFinish().equals(castOther.getStartFinish()) ) )
 && ( (this.getCallText()==castOther.getCallText()) || ( this.getCallText()!=null && castOther.getCallText()!=null && this.getCallText().equals(castOther.getCallText()) ) )
 && ( (this.getSpare1()==castOther.getSpare1()) || ( this.getSpare1()!=null && castOther.getSpare1()!=null && this.getSpare1().equals(castOther.getSpare1()) ) )
 && ( (this.getSpare2()==castOther.getSpare2()) || ( this.getSpare2()!=null && castOther.getSpare2()!=null && this.getSpare2().equals(castOther.getSpare2()) ) )
 && ( (this.getSpare3()==castOther.getSpare3()) || ( this.getSpare3()!=null && castOther.getSpare3()!=null && this.getSpare3().equals(castOther.getSpare3()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSessionId() == null ? 0 : this.getSessionId().hashCode() );
         result = 37 * result + ( getStartFinish() == null ? 0 : this.getStartFinish().hashCode() );
         result = 37 * result + ( getCallText() == null ? 0 : this.getCallText().hashCode() );
         result = 37 * result + ( getSpare1() == null ? 0 : this.getSpare1().hashCode() );
         result = 37 * result + ( getSpare2() == null ? 0 : this.getSpare2().hashCode() );
         result = 37 * result + ( getSpare3() == null ? 0 : this.getSpare3().hashCode() );
         return result;
   }   


}


