package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * LogstdbyhistoryId generated by hbm2java
 */
public class LogstdbyhistoryId  implements java.io.Serializable {


     private BigDecimal streamSequence_;
     private BigDecimal lmnrSid;
     private BigDecimal dbid;
     private BigDecimal firstChange_;
     private BigDecimal lastChange_;
     private BigDecimal source;
     private BigDecimal status;
     private Date firstTime;
     private Date lastTime;
     private String dgname;
     private BigDecimal spare1;
     private BigDecimal spare2;
     private String spare3;

    

    
   
    public BigDecimal getStreamSequence_() {
        return this.streamSequence_;
    }
    
    public void setStreamSequence_(BigDecimal streamSequence_) {
        this.streamSequence_ = streamSequence_;
    }
    public BigDecimal getLmnrSid() {
        return this.lmnrSid;
    }
    
    public void setLmnrSid(BigDecimal lmnrSid) {
        this.lmnrSid = lmnrSid;
    }
    public BigDecimal getDbid() {
        return this.dbid;
    }
    
    public void setDbid(BigDecimal dbid) {
        this.dbid = dbid;
    }
    public BigDecimal getFirstChange_() {
        return this.firstChange_;
    }
    
    public void setFirstChange_(BigDecimal firstChange_) {
        this.firstChange_ = firstChange_;
    }
    public BigDecimal getLastChange_() {
        return this.lastChange_;
    }
    
    public void setLastChange_(BigDecimal lastChange_) {
        this.lastChange_ = lastChange_;
    }
    public BigDecimal getSource() {
        return this.source;
    }
    
    public void setSource(BigDecimal source) {
        this.source = source;
    }
    public BigDecimal getStatus() {
        return this.status;
    }
    
    public void setStatus(BigDecimal status) {
        this.status = status;
    }
    public Date getFirstTime() {
        return this.firstTime;
    }
    
    public void setFirstTime(Date firstTime) {
        this.firstTime = firstTime;
    }
    public Date getLastTime() {
        return this.lastTime;
    }
    
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }
    public String getDgname() {
        return this.dgname;
    }
    
    public void setDgname(String dgname) {
        this.dgname = dgname;
    }
    public BigDecimal getSpare1() {
        return this.spare1;
    }
    
    public void setSpare1(BigDecimal spare1) {
        this.spare1 = spare1;
    }
    public BigDecimal getSpare2() {
        return this.spare2;
    }
    
    public void setSpare2(BigDecimal spare2) {
        this.spare2 = spare2;
    }
    public String getSpare3() {
        return this.spare3;
    }
    
    public void setSpare3(String spare3) {
        this.spare3 = spare3;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LogstdbyhistoryId) ) return false;
		 LogstdbyhistoryId castOther = ( LogstdbyhistoryId ) other; 
         
		 return ( (this.getStreamSequence_()==castOther.getStreamSequence_()) || ( this.getStreamSequence_()!=null && castOther.getStreamSequence_()!=null && this.getStreamSequence_().equals(castOther.getStreamSequence_()) ) )
 && ( (this.getLmnrSid()==castOther.getLmnrSid()) || ( this.getLmnrSid()!=null && castOther.getLmnrSid()!=null && this.getLmnrSid().equals(castOther.getLmnrSid()) ) )
 && ( (this.getDbid()==castOther.getDbid()) || ( this.getDbid()!=null && castOther.getDbid()!=null && this.getDbid().equals(castOther.getDbid()) ) )
 && ( (this.getFirstChange_()==castOther.getFirstChange_()) || ( this.getFirstChange_()!=null && castOther.getFirstChange_()!=null && this.getFirstChange_().equals(castOther.getFirstChange_()) ) )
 && ( (this.getLastChange_()==castOther.getLastChange_()) || ( this.getLastChange_()!=null && castOther.getLastChange_()!=null && this.getLastChange_().equals(castOther.getLastChange_()) ) )
 && ( (this.getSource()==castOther.getSource()) || ( this.getSource()!=null && castOther.getSource()!=null && this.getSource().equals(castOther.getSource()) ) )
 && ( (this.getStatus()==castOther.getStatus()) || ( this.getStatus()!=null && castOther.getStatus()!=null && this.getStatus().equals(castOther.getStatus()) ) )
 && ( (this.getFirstTime()==castOther.getFirstTime()) || ( this.getFirstTime()!=null && castOther.getFirstTime()!=null && this.getFirstTime().equals(castOther.getFirstTime()) ) )
 && ( (this.getLastTime()==castOther.getLastTime()) || ( this.getLastTime()!=null && castOther.getLastTime()!=null && this.getLastTime().equals(castOther.getLastTime()) ) )
 && ( (this.getDgname()==castOther.getDgname()) || ( this.getDgname()!=null && castOther.getDgname()!=null && this.getDgname().equals(castOther.getDgname()) ) )
 && ( (this.getSpare1()==castOther.getSpare1()) || ( this.getSpare1()!=null && castOther.getSpare1()!=null && this.getSpare1().equals(castOther.getSpare1()) ) )
 && ( (this.getSpare2()==castOther.getSpare2()) || ( this.getSpare2()!=null && castOther.getSpare2()!=null && this.getSpare2().equals(castOther.getSpare2()) ) )
 && ( (this.getSpare3()==castOther.getSpare3()) || ( this.getSpare3()!=null && castOther.getSpare3()!=null && this.getSpare3().equals(castOther.getSpare3()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getStreamSequence_() == null ? 0 : this.getStreamSequence_().hashCode() );
         result = 37 * result + ( getLmnrSid() == null ? 0 : this.getLmnrSid().hashCode() );
         result = 37 * result + ( getDbid() == null ? 0 : this.getDbid().hashCode() );
         result = 37 * result + ( getFirstChange_() == null ? 0 : this.getFirstChange_().hashCode() );
         result = 37 * result + ( getLastChange_() == null ? 0 : this.getLastChange_().hashCode() );
         result = 37 * result + ( getSource() == null ? 0 : this.getSource().hashCode() );
         result = 37 * result + ( getStatus() == null ? 0 : this.getStatus().hashCode() );
         result = 37 * result + ( getFirstTime() == null ? 0 : this.getFirstTime().hashCode() );
         result = 37 * result + ( getLastTime() == null ? 0 : this.getLastTime().hashCode() );
         result = 37 * result + ( getDgname() == null ? 0 : this.getDgname().hashCode() );
         result = 37 * result + ( getSpare1() == null ? 0 : this.getSpare1().hashCode() );
         result = 37 * result + ( getSpare2() == null ? 0 : this.getSpare2().hashCode() );
         result = 37 * result + ( getSpare3() == null ? 0 : this.getSpare3().hashCode() );
         return result;
   }   


}


