package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA



/**
 * LogstdbyapplyMilestone generated by hbm2java
 */
public class LogstdbyapplyMilestone  implements java.io.Serializable {


     private LogstdbyapplyMilestoneId id;

    

    
   
    public LogstdbyapplyMilestoneId getId() {
        return this.id;
    }
    
    public void setId(LogstdbyapplyMilestoneId id) {
        this.id = id;
    }




}


