package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA



/**
 * LogstdbyskipSupport generated by hbm2java
 */
public class LogstdbyskipSupport  implements java.io.Serializable {


     private LogstdbyskipSupportId id;

    

    
   
    public LogstdbyskipSupportId getId() {
        return this.id;
    }
    
    public void setId(LogstdbyskipSupportId id) {
        this.id = id;
    }




}


