package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA



/**
 * LogstdbyapplyProgress generated by hbm2java
 */
public class LogstdbyapplyProgress  implements java.io.Serializable {


     private LogstdbyapplyProgressId id;

    

    
   
    public LogstdbyapplyProgressId getId() {
        return this.id;
    }
    
    public void setId(LogstdbyapplyProgressId id) {
        this.id = id;
    }




}


