package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA



/**
 * Logstdbyhistory generated by hbm2java
 */
public class Logstdbyhistory  implements java.io.Serializable {


     private LogstdbyhistoryId id;

    

    
   
    public LogstdbyhistoryId getId() {
        return this.id;
    }
    
    public void setId(LogstdbyhistoryId id) {
        this.id = id;
    }




}


