package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA



/**
 * Logstdbyplsql generated by hbm2java
 */
public class Logstdbyplsql  implements java.io.Serializable {


     private LogstdbyplsqlId id;

    

    
   
    public LogstdbyplsqlId getId() {
        return this.id;
    }
    
    public void setId(LogstdbyplsqlId id) {
        this.id = id;
    }




}


