package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA



/**
 * Logstdbyskip generated by hbm2java
 */
public class Logstdbyskip  implements java.io.Serializable {


     private LogstdbyskipId id;

    

    
   
    public LogstdbyskipId getId() {
        return this.id;
    }
    
    public void setId(LogstdbyskipId id) {
        this.id = id;
    }




}


