package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA



/**
 * LogstdbyskipTransaction generated by hbm2java
 */
public class LogstdbyskipTransaction  implements java.io.Serializable {


     private LogstdbyskipTransactionId id;

    

    
   
    public LogstdbyskipTransactionId getId() {
        return this.id;
    }
    
    public void setId(LogstdbyskipTransactionId id) {
        this.id = id;
    }




}


