package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * LogstdbyapplyMilestoneId generated by hbm2java
 */
public class LogstdbyapplyMilestoneId  implements java.io.Serializable {


     private BigDecimal sessionId;
     private BigDecimal commitScn;
     private Date commitTime;
     private BigDecimal synchScn;
     private BigDecimal epoch;
     private BigDecimal processedScn;
     private Date processedTime;
     private BigDecimal fetchlwmScn;
     private BigDecimal spare1;
     private BigDecimal spare2;
     private String spare3;

    

	
    
    
   
    public BigDecimal getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(BigDecimal sessionId) {
        this.sessionId = sessionId;
    }
    public BigDecimal getCommitScn() {
        return this.commitScn;
    }
    
    public void setCommitScn(BigDecimal commitScn) {
        this.commitScn = commitScn;
    }
    public Date getCommitTime() {
        return this.commitTime;
    }
    
    public void setCommitTime(Date commitTime) {
        this.commitTime = commitTime;
    }
    public BigDecimal getSynchScn() {
        return this.synchScn;
    }
    
    public void setSynchScn(BigDecimal synchScn) {
        this.synchScn = synchScn;
    }
    public BigDecimal getEpoch() {
        return this.epoch;
    }
    
    public void setEpoch(BigDecimal epoch) {
        this.epoch = epoch;
    }
    public BigDecimal getProcessedScn() {
        return this.processedScn;
    }
    
    public void setProcessedScn(BigDecimal processedScn) {
        this.processedScn = processedScn;
    }
    public Date getProcessedTime() {
        return this.processedTime;
    }
    
    public void setProcessedTime(Date processedTime) {
        this.processedTime = processedTime;
    }
    public BigDecimal getFetchlwmScn() {
        return this.fetchlwmScn;
    }
    
    public void setFetchlwmScn(BigDecimal fetchlwmScn) {
        this.fetchlwmScn = fetchlwmScn;
    }
    public BigDecimal getSpare1() {
        return this.spare1;
    }
    
    public void setSpare1(BigDecimal spare1) {
        this.spare1 = spare1;
    }
    public BigDecimal getSpare2() {
        return this.spare2;
    }
    
    public void setSpare2(BigDecimal spare2) {
        this.spare2 = spare2;
    }
    public String getSpare3() {
        return this.spare3;
    }
    
    public void setSpare3(String spare3) {
        this.spare3 = spare3;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LogstdbyapplyMilestoneId) ) return false;
		 LogstdbyapplyMilestoneId castOther = ( LogstdbyapplyMilestoneId ) other; 
         
		 return ( (this.getSessionId()==castOther.getSessionId()) || ( this.getSessionId()!=null && castOther.getSessionId()!=null && this.getSessionId().equals(castOther.getSessionId()) ) )
 && ( (this.getCommitScn()==castOther.getCommitScn()) || ( this.getCommitScn()!=null && castOther.getCommitScn()!=null && this.getCommitScn().equals(castOther.getCommitScn()) ) )
 && ( (this.getCommitTime()==castOther.getCommitTime()) || ( this.getCommitTime()!=null && castOther.getCommitTime()!=null && this.getCommitTime().equals(castOther.getCommitTime()) ) )
 && ( (this.getSynchScn()==castOther.getSynchScn()) || ( this.getSynchScn()!=null && castOther.getSynchScn()!=null && this.getSynchScn().equals(castOther.getSynchScn()) ) )
 && ( (this.getEpoch()==castOther.getEpoch()) || ( this.getEpoch()!=null && castOther.getEpoch()!=null && this.getEpoch().equals(castOther.getEpoch()) ) )
 && ( (this.getProcessedScn()==castOther.getProcessedScn()) || ( this.getProcessedScn()!=null && castOther.getProcessedScn()!=null && this.getProcessedScn().equals(castOther.getProcessedScn()) ) )
 && ( (this.getProcessedTime()==castOther.getProcessedTime()) || ( this.getProcessedTime()!=null && castOther.getProcessedTime()!=null && this.getProcessedTime().equals(castOther.getProcessedTime()) ) )
 && ( (this.getFetchlwmScn()==castOther.getFetchlwmScn()) || ( this.getFetchlwmScn()!=null && castOther.getFetchlwmScn()!=null && this.getFetchlwmScn().equals(castOther.getFetchlwmScn()) ) )
 && ( (this.getSpare1()==castOther.getSpare1()) || ( this.getSpare1()!=null && castOther.getSpare1()!=null && this.getSpare1().equals(castOther.getSpare1()) ) )
 && ( (this.getSpare2()==castOther.getSpare2()) || ( this.getSpare2()!=null && castOther.getSpare2()!=null && this.getSpare2().equals(castOther.getSpare2()) ) )
 && ( (this.getSpare3()==castOther.getSpare3()) || ( this.getSpare3()!=null && castOther.getSpare3()!=null && this.getSpare3().equals(castOther.getSpare3()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSessionId() == null ? 0 : this.getSessionId().hashCode() );
         result = 37 * result + ( getCommitScn() == null ? 0 : this.getCommitScn().hashCode() );
         result = 37 * result + ( getCommitTime() == null ? 0 : this.getCommitTime().hashCode() );
         result = 37 * result + ( getSynchScn() == null ? 0 : this.getSynchScn().hashCode() );
         result = 37 * result + ( getEpoch() == null ? 0 : this.getEpoch().hashCode() );
         result = 37 * result + ( getProcessedScn() == null ? 0 : this.getProcessedScn().hashCode() );
         result = 37 * result + ( getProcessedTime() == null ? 0 : this.getProcessedTime().hashCode() );
         result = 37 * result + ( getFetchlwmScn() == null ? 0 : this.getFetchlwmScn().hashCode() );
         result = 37 * result + ( getSpare1() == null ? 0 : this.getSpare1().hashCode() );
         result = 37 * result + ( getSpare2() == null ? 0 : this.getSpare2().hashCode() );
         result = 37 * result + ( getSpare3() == null ? 0 : this.getSpare3().hashCode() );
         return result;
   }   


}


