package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * LogstdbyflashbackScn generated by hbm2java
 */
public class LogstdbyflashbackScn  implements java.io.Serializable {


     private BigDecimal primaryScn;
     private Date primaryTime;
     private BigDecimal standbyScn;
     private Date standbyTime;
     private BigDecimal spare1;
     private BigDecimal spare2;
     private Date spare3;

    

	
    
    
   
    public BigDecimal getPrimaryScn() {
        return this.primaryScn;
    }
    
    public void setPrimaryScn(BigDecimal primaryScn) {
        this.primaryScn = primaryScn;
    }
    public Date getPrimaryTime() {
        return this.primaryTime;
    }
    
    public void setPrimaryTime(Date primaryTime) {
        this.primaryTime = primaryTime;
    }
    public BigDecimal getStandbyScn() {
        return this.standbyScn;
    }
    
    public void setStandbyScn(BigDecimal standbyScn) {
        this.standbyScn = standbyScn;
    }
    public Date getStandbyTime() {
        return this.standbyTime;
    }
    
    public void setStandbyTime(Date standbyTime) {
        this.standbyTime = standbyTime;
    }
    public BigDecimal getSpare1() {
        return this.spare1;
    }
    
    public void setSpare1(BigDecimal spare1) {
        this.spare1 = spare1;
    }
    public BigDecimal getSpare2() {
        return this.spare2;
    }
    
    public void setSpare2(BigDecimal spare2) {
        this.spare2 = spare2;
    }
    public Date getSpare3() {
        return this.spare3;
    }
    
    public void setSpare3(Date spare3) {
        this.spare3 = spare3;
    }




}


