package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * LogstdbyscnId generated by hbm2java
 */
public class LogstdbyscnId  implements java.io.Serializable {


     private BigDecimal obj_;
     private String objname;
     private String schema;
     private String type;
     private BigDecimal scn;
     private BigDecimal spare1;
     private BigDecimal spare2;
     private String spare3;

    

    
   
    public BigDecimal getObj_() {
        return this.obj_;
    }
    
    public void setObj_(BigDecimal obj_) {
        this.obj_ = obj_;
    }
    public String getObjname() {
        return this.objname;
    }
    
    public void setObjname(String objname) {
        this.objname = objname;
    }
    public String getSchema() {
        return this.schema;
    }
    
    public void setSchema(String schema) {
        this.schema = schema;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public BigDecimal getScn() {
        return this.scn;
    }
    
    public void setScn(BigDecimal scn) {
        this.scn = scn;
    }
    public BigDecimal getSpare1() {
        return this.spare1;
    }
    
    public void setSpare1(BigDecimal spare1) {
        this.spare1 = spare1;
    }
    public BigDecimal getSpare2() {
        return this.spare2;
    }
    
    public void setSpare2(BigDecimal spare2) {
        this.spare2 = spare2;
    }
    public String getSpare3() {
        return this.spare3;
    }
    
    public void setSpare3(String spare3) {
        this.spare3 = spare3;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LogstdbyscnId) ) return false;
		 LogstdbyscnId castOther = ( LogstdbyscnId ) other; 
         
		 return ( (this.getObj_()==castOther.getObj_()) || ( this.getObj_()!=null && castOther.getObj_()!=null && this.getObj_().equals(castOther.getObj_()) ) )
 && ( (this.getObjname()==castOther.getObjname()) || ( this.getObjname()!=null && castOther.getObjname()!=null && this.getObjname().equals(castOther.getObjname()) ) )
 && ( (this.getSchema()==castOther.getSchema()) || ( this.getSchema()!=null && castOther.getSchema()!=null && this.getSchema().equals(castOther.getSchema()) ) )
 && ( (this.getType()==castOther.getType()) || ( this.getType()!=null && castOther.getType()!=null && this.getType().equals(castOther.getType()) ) )
 && ( (this.getScn()==castOther.getScn()) || ( this.getScn()!=null && castOther.getScn()!=null && this.getScn().equals(castOther.getScn()) ) )
 && ( (this.getSpare1()==castOther.getSpare1()) || ( this.getSpare1()!=null && castOther.getSpare1()!=null && this.getSpare1().equals(castOther.getSpare1()) ) )
 && ( (this.getSpare2()==castOther.getSpare2()) || ( this.getSpare2()!=null && castOther.getSpare2()!=null && this.getSpare2().equals(castOther.getSpare2()) ) )
 && ( (this.getSpare3()==castOther.getSpare3()) || ( this.getSpare3()!=null && castOther.getSpare3()!=null && this.getSpare3().equals(castOther.getSpare3()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getObj_() == null ? 0 : this.getObj_().hashCode() );
         result = 37 * result + ( getObjname() == null ? 0 : this.getObjname().hashCode() );
         result = 37 * result + ( getSchema() == null ? 0 : this.getSchema().hashCode() );
         result = 37 * result + ( getType() == null ? 0 : this.getType().hashCode() );
         result = 37 * result + ( getScn() == null ? 0 : this.getScn().hashCode() );
         result = 37 * result + ( getSpare1() == null ? 0 : this.getSpare1().hashCode() );
         result = 37 * result + ( getSpare2() == null ? 0 : this.getSpare2().hashCode() );
         result = 37 * result + ( getSpare3() == null ? 0 : this.getSpare3().hashCode() );
         return result;
   }   


}


