package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA



/**
 * Logstdbyevents generated by hbm2java
 */
public class Logstdbyevents  implements java.io.Serializable {


     private LogstdbyeventsId id;

    

    
   
    public LogstdbyeventsId getId() {
        return this.id;
    }
    
    public void setId(LogstdbyeventsId id) {
        this.id = id;
    }




}


