package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MviewAdvLog generated by hbm2java
 */
public class MviewAdvLog  implements java.io.Serializable {


     private BigDecimal runid_;
     private BigDecimal filterid_;
     private Date runBegin;
     private Date runEnd;
     private BigDecimal runType;
     private String uname;
     private BigDecimal status;
     private String message;
     private BigDecimal completed;
     private BigDecimal total;
     private String errorCode;
     private Set mviewAdvExceptionses = new HashSet(0);
     private Set mviewAdvEligibles = new HashSet(0);
     private Set mviewAdvOutputs = new HashSet(0);
     private Set mviewAdvRollups = new HashSet(0);
     private Set mviewAdvAjgs = new HashSet(0);
     private Set mviewAdvInfos = new HashSet(0);
     private Set mviewAdvCliques = new HashSet(0);
     private Set mviewAdvFilterinstances = new HashSet(0);
     private Set mviewAdvLevels = new HashSet(0);
     private Set mviewAdvJournals = new HashSet(0);

    

	
    
    
   
    public BigDecimal getRunid_() {
        return this.runid_;
    }
    
    public void setRunid_(BigDecimal runid_) {
        this.runid_ = runid_;
    }
    public BigDecimal getFilterid_() {
        return this.filterid_;
    }
    
    public void setFilterid_(BigDecimal filterid_) {
        this.filterid_ = filterid_;
    }
    public Date getRunBegin() {
        return this.runBegin;
    }
    
    public void setRunBegin(Date runBegin) {
        this.runBegin = runBegin;
    }
    public Date getRunEnd() {
        return this.runEnd;
    }
    
    public void setRunEnd(Date runEnd) {
        this.runEnd = runEnd;
    }
    public BigDecimal getRunType() {
        return this.runType;
    }
    
    public void setRunType(BigDecimal runType) {
        this.runType = runType;
    }
    public String getUname() {
        return this.uname;
    }
    
    public void setUname(String uname) {
        this.uname = uname;
    }
    public BigDecimal getStatus() {
        return this.status;
    }
    
    public void setStatus(BigDecimal status) {
        this.status = status;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public BigDecimal getCompleted() {
        return this.completed;
    }
    
    public void setCompleted(BigDecimal completed) {
        this.completed = completed;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
    public String getErrorCode() {
        return this.errorCode;
    }
    
    public void setErrorCode(String errorCode) {
        this.errorCode = errorCode;
    }
    public Set getMviewAdvExceptionses() {
        return this.mviewAdvExceptionses;
    }
    
    public void setMviewAdvExceptionses(Set mviewAdvExceptionses) {
        this.mviewAdvExceptionses = mviewAdvExceptionses;
    }
    public Set getMviewAdvEligibles() {
        return this.mviewAdvEligibles;
    }
    
    public void setMviewAdvEligibles(Set mviewAdvEligibles) {
        this.mviewAdvEligibles = mviewAdvEligibles;
    }
    public Set getMviewAdvOutputs() {
        return this.mviewAdvOutputs;
    }
    
    public void setMviewAdvOutputs(Set mviewAdvOutputs) {
        this.mviewAdvOutputs = mviewAdvOutputs;
    }
    public Set getMviewAdvRollups() {
        return this.mviewAdvRollups;
    }
    
    public void setMviewAdvRollups(Set mviewAdvRollups) {
        this.mviewAdvRollups = mviewAdvRollups;
    }
    public Set getMviewAdvAjgs() {
        return this.mviewAdvAjgs;
    }
    
    public void setMviewAdvAjgs(Set mviewAdvAjgs) {
        this.mviewAdvAjgs = mviewAdvAjgs;
    }
    public Set getMviewAdvInfos() {
        return this.mviewAdvInfos;
    }
    
    public void setMviewAdvInfos(Set mviewAdvInfos) {
        this.mviewAdvInfos = mviewAdvInfos;
    }
    public Set getMviewAdvCliques() {
        return this.mviewAdvCliques;
    }
    
    public void setMviewAdvCliques(Set mviewAdvCliques) {
        this.mviewAdvCliques = mviewAdvCliques;
    }
    public Set getMviewAdvFilterinstances() {
        return this.mviewAdvFilterinstances;
    }
    
    public void setMviewAdvFilterinstances(Set mviewAdvFilterinstances) {
        this.mviewAdvFilterinstances = mviewAdvFilterinstances;
    }
    public Set getMviewAdvLevels() {
        return this.mviewAdvLevels;
    }
    
    public void setMviewAdvLevels(Set mviewAdvLevels) {
        this.mviewAdvLevels = mviewAdvLevels;
    }
    public Set getMviewAdvJournals() {
        return this.mviewAdvJournals;
    }
    
    public void setMviewAdvJournals(Set mviewAdvJournals) {
        this.mviewAdvJournals = mviewAdvJournals;
    }




}


