package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * MviewAdvParameters generated by hbm2java
 */
public class MviewAdvParameters  implements java.io.Serializable {


     private String parameterName;
     private BigDecimal parameterType;
     private String stringValue;
     private Date dateValue;
     private BigDecimal numericalValue;

    

	
    
    
   
    public String getParameterName() {
        return this.parameterName;
    }
    
    public void setParameterName(String parameterName) {
        this.parameterName = parameterName;
    }
    public BigDecimal getParameterType() {
        return this.parameterType;
    }
    
    public void setParameterType(BigDecimal parameterType) {
        this.parameterType = parameterType;
    }
    public String getStringValue() {
        return this.stringValue;
    }
    
    public void setStringValue(String stringValue) {
        this.stringValue = stringValue;
    }
    public Date getDateValue() {
        return this.dateValue;
    }
    
    public void setDateValue(Date dateValue) {
        this.dateValue = dateValue;
    }
    public BigDecimal getNumericalValue() {
        return this.numericalValue;
    }
    
    public void setNumericalValue(BigDecimal numericalValue) {
        this.numericalValue = numericalValue;
    }




}


