package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA



/**
 * MviewFilterinstance generated by hbm2java
 */
public class MviewFilterinstance  implements java.io.Serializable {


     private MviewFilterinstanceId id;

    

    
   
    public MviewFilterinstanceId getId() {
        return this.id;
    }
    
    public void setId(MviewFilterinstanceId id) {
        this.id = id;
    }




}


