package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * MviewAdvOutputId generated by hbm2java
 */
public class MviewAdvOutputId  implements java.io.Serializable {


     private BigDecimal runid_;
     private BigDecimal rank_;

    

    
   
    public BigDecimal getRunid_() {
        return this.runid_;
    }
    
    public void setRunid_(BigDecimal runid_) {
        this.runid_ = runid_;
    }
    public BigDecimal getRank_() {
        return this.rank_;
    }
    
    public void setRank_(BigDecimal rank_) {
        this.rank_ = rank_;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MviewAdvOutputId) ) return false;
		 MviewAdvOutputId castOther = ( MviewAdvOutputId ) other; 
         
		 return ( (this.getRunid_()==castOther.getRunid_()) || ( this.getRunid_()!=null && castOther.getRunid_()!=null && this.getRunid_().equals(castOther.getRunid_()) ) )
 && ( (this.getRank_()==castOther.getRank_()) || ( this.getRank_()!=null && castOther.getRank_()!=null && this.getRank_().equals(castOther.getRank_()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRunid_() == null ? 0 : this.getRunid_().hashCode() );
         result = 37 * result + ( getRank_() == null ? 0 : this.getRank_().hashCode() );
         return result;
   }   


}


