package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * MviewLogId generated by hbm2java
 */
public class MviewLogId  implements java.io.Serializable {


     private BigDecimal id;
     private BigDecimal filterid;
     private Date runBegin;
     private Date runEnd;
     private String type;
     private String status;
     private String message;
     private BigDecimal completed;
     private BigDecimal total;
     private String errorCode;

    

	
    
    
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public BigDecimal getFilterid() {
        return this.filterid;
    }
    
    public void setFilterid(BigDecimal filterid) {
        this.filterid = filterid;
    }
    public Date getRunBegin() {
        return this.runBegin;
    }
    
    public void setRunBegin(Date runBegin) {
        this.runBegin = runBegin;
    }
    public Date getRunEnd() {
        return this.runEnd;
    }
    
    public void setRunEnd(Date runEnd) {
        this.runEnd = runEnd;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public BigDecimal getCompleted() {
        return this.completed;
    }
    
    public void setCompleted(BigDecimal completed) {
        this.completed = completed;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
    public String getErrorCode() {
        return this.errorCode;
    }
    
    public void setErrorCode(String errorCode) {
        this.errorCode = errorCode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MviewLogId) ) return false;
		 MviewLogId castOther = ( MviewLogId ) other; 
         
		 return ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && ( (this.getFilterid()==castOther.getFilterid()) || ( this.getFilterid()!=null && castOther.getFilterid()!=null && this.getFilterid().equals(castOther.getFilterid()) ) )
 && ( (this.getRunBegin()==castOther.getRunBegin()) || ( this.getRunBegin()!=null && castOther.getRunBegin()!=null && this.getRunBegin().equals(castOther.getRunBegin()) ) )
 && ( (this.getRunEnd()==castOther.getRunEnd()) || ( this.getRunEnd()!=null && castOther.getRunEnd()!=null && this.getRunEnd().equals(castOther.getRunEnd()) ) )
 && ( (this.getType()==castOther.getType()) || ( this.getType()!=null && castOther.getType()!=null && this.getType().equals(castOther.getType()) ) )
 && ( (this.getStatus()==castOther.getStatus()) || ( this.getStatus()!=null && castOther.getStatus()!=null && this.getStatus().equals(castOther.getStatus()) ) )
 && ( (this.getMessage()==castOther.getMessage()) || ( this.getMessage()!=null && castOther.getMessage()!=null && this.getMessage().equals(castOther.getMessage()) ) )
 && ( (this.getCompleted()==castOther.getCompleted()) || ( this.getCompleted()!=null && castOther.getCompleted()!=null && this.getCompleted().equals(castOther.getCompleted()) ) )
 && ( (this.getTotal()==castOther.getTotal()) || ( this.getTotal()!=null && castOther.getTotal()!=null && this.getTotal().equals(castOther.getTotal()) ) )
 && ( (this.getErrorCode()==castOther.getErrorCode()) || ( this.getErrorCode()!=null && castOther.getErrorCode()!=null && this.getErrorCode().equals(castOther.getErrorCode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + ( getFilterid() == null ? 0 : this.getFilterid().hashCode() );
         result = 37 * result + ( getRunBegin() == null ? 0 : this.getRunBegin().hashCode() );
         result = 37 * result + ( getRunEnd() == null ? 0 : this.getRunEnd().hashCode() );
         result = 37 * result + ( getType() == null ? 0 : this.getType().hashCode() );
         result = 37 * result + ( getStatus() == null ? 0 : this.getStatus().hashCode() );
         result = 37 * result + ( getMessage() == null ? 0 : this.getMessage().hashCode() );
         result = 37 * result + ( getCompleted() == null ? 0 : this.getCompleted().hashCode() );
         result = 37 * result + ( getTotal() == null ? 0 : this.getTotal().hashCode() );
         result = 37 * result + ( getErrorCode() == null ? 0 : this.getErrorCode().hashCode() );
         return result;
   }   


}


