package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * MviewAdvPrettyId generated by hbm2java
 */
public class MviewAdvPrettyId  implements java.io.Serializable {


     private BigDecimal queryid_;
     private String sqlText;

    

    
   
    public BigDecimal getQueryid_() {
        return this.queryid_;
    }
    
    public void setQueryid_(BigDecimal queryid_) {
        this.queryid_ = queryid_;
    }
    public String getSqlText() {
        return this.sqlText;
    }
    
    public void setSqlText(String sqlText) {
        this.sqlText = sqlText;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MviewAdvPrettyId) ) return false;
		 MviewAdvPrettyId castOther = ( MviewAdvPrettyId ) other; 
         
		 return ( (this.getQueryid_()==castOther.getQueryid_()) || ( this.getQueryid_()!=null && castOther.getQueryid_()!=null && this.getQueryid_().equals(castOther.getQueryid_()) ) )
 && ( (this.getSqlText()==castOther.getSqlText()) || ( this.getSqlText()!=null && castOther.getSqlText()!=null && this.getSqlText().equals(castOther.getSqlText()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getQueryid_() == null ? 0 : this.getQueryid_().hashCode() );
         result = 37 * result + ( getSqlText() == null ? 0 : this.getSqlText().hashCode() );
         return result;
   }   


}


