package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA



/**
 * MviewExceptions generated by hbm2java
 */
public class MviewExceptions  implements java.io.Serializable {


     private MviewExceptionsId id;

    

    
   
    public MviewExceptionsId getId() {
        return this.id;
    }
    
    public void setId(MviewExceptionsId id) {
        this.id = id;
    }




}


