package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * MviewAdvRollupId generated by hbm2java
 */
public class MviewAdvRollupId  implements java.io.Serializable {


     private BigDecimal runid_;
     private BigDecimal clevelid_;
     private BigDecimal plevelid_;

    

    
   
    public BigDecimal getRunid_() {
        return this.runid_;
    }
    
    public void setRunid_(BigDecimal runid_) {
        this.runid_ = runid_;
    }
    public BigDecimal getClevelid_() {
        return this.clevelid_;
    }
    
    public void setClevelid_(BigDecimal clevelid_) {
        this.clevelid_ = clevelid_;
    }
    public BigDecimal getPlevelid_() {
        return this.plevelid_;
    }
    
    public void setPlevelid_(BigDecimal plevelid_) {
        this.plevelid_ = plevelid_;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MviewAdvRollupId) ) return false;
		 MviewAdvRollupId castOther = ( MviewAdvRollupId ) other; 
         
		 return ( (this.getRunid_()==castOther.getRunid_()) || ( this.getRunid_()!=null && castOther.getRunid_()!=null && this.getRunid_().equals(castOther.getRunid_()) ) )
 && ( (this.getClevelid_()==castOther.getClevelid_()) || ( this.getClevelid_()!=null && castOther.getClevelid_()!=null && this.getClevelid_().equals(castOther.getClevelid_()) ) )
 && ( (this.getPlevelid_()==castOther.getPlevelid_()) || ( this.getPlevelid_()!=null && castOther.getPlevelid_()!=null && this.getPlevelid_().equals(castOther.getPlevelid_()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRunid_() == null ? 0 : this.getRunid_().hashCode() );
         result = 37 * result + ( getClevelid_() == null ? 0 : this.getClevelid_().hashCode() );
         result = 37 * result + ( getPlevelid_() == null ? 0 : this.getPlevelid_().hashCode() );
         return result;
   }   


}


