package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * MviewAdvBasetableId generated by hbm2java
 */
public class MviewAdvBasetableId  implements java.io.Serializable {


     private BigDecimal collectionid_;
     private BigDecimal queryid_;
     private String owner;
     private String tableName;
     private BigDecimal tableType;

    

	
    
    
   
    public BigDecimal getCollectionid_() {
        return this.collectionid_;
    }
    
    public void setCollectionid_(BigDecimal collectionid_) {
        this.collectionid_ = collectionid_;
    }
    public BigDecimal getQueryid_() {
        return this.queryid_;
    }
    
    public void setQueryid_(BigDecimal queryid_) {
        this.queryid_ = queryid_;
    }
    public String getOwner() {
        return this.owner;
    }
    
    public void setOwner(String owner) {
        this.owner = owner;
    }
    public String getTableName() {
        return this.tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }
    public BigDecimal getTableType() {
        return this.tableType;
    }
    
    public void setTableType(BigDecimal tableType) {
        this.tableType = tableType;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MviewAdvBasetableId) ) return false;
		 MviewAdvBasetableId castOther = ( MviewAdvBasetableId ) other; 
         
		 return ( (this.getCollectionid_()==castOther.getCollectionid_()) || ( this.getCollectionid_()!=null && castOther.getCollectionid_()!=null && this.getCollectionid_().equals(castOther.getCollectionid_()) ) )
 && ( (this.getQueryid_()==castOther.getQueryid_()) || ( this.getQueryid_()!=null && castOther.getQueryid_()!=null && this.getQueryid_().equals(castOther.getQueryid_()) ) )
 && ( (this.getOwner()==castOther.getOwner()) || ( this.getOwner()!=null && castOther.getOwner()!=null && this.getOwner().equals(castOther.getOwner()) ) )
 && ( (this.getTableName()==castOther.getTableName()) || ( this.getTableName()!=null && castOther.getTableName()!=null && this.getTableName().equals(castOther.getTableName()) ) )
 && ( (this.getTableType()==castOther.getTableType()) || ( this.getTableType()!=null && castOther.getTableType()!=null && this.getTableType().equals(castOther.getTableType()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCollectionid_() == null ? 0 : this.getCollectionid_().hashCode() );
         result = 37 * result + ( getQueryid_() == null ? 0 : this.getQueryid_().hashCode() );
         result = 37 * result + ( getOwner() == null ? 0 : this.getOwner().hashCode() );
         result = 37 * result + ( getTableName() == null ? 0 : this.getTableName().hashCode() );
         result = 37 * result + ( getTableType() == null ? 0 : this.getTableType().hashCode() );
         return result;
   }   


}


