package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA



/**
 * MviewAdvTemp generated by hbm2java
 */
public class MviewAdvTemp  implements java.io.Serializable {


     private MviewAdvTempId id;

    

    
   
    public MviewAdvTempId getId() {
        return this.id;
    }
    
    public void setId(MviewAdvTempId id) {
        this.id = id;
    }




}


