package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA



/**
 * MviewAdvPretty generated by hbm2java
 */
public class MviewAdvPretty  implements java.io.Serializable {


     private MviewAdvPrettyId id;

    

    
   
    public MviewAdvPrettyId getId() {
        return this.id;
    }
    
    public void setId(MviewAdvPrettyId id) {
        this.id = id;
    }




}


