package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * MviewAdvAjg generated by hbm2java
 */
public class MviewAdvAjg  implements java.io.Serializable {


     private BigDecimal ajgid_;
     private MviewAdvLog mviewAdvLog;
     private BigDecimal ajgdeslen;
     private byte[] ajgdes;
     private BigDecimal hashvalue;
     private BigDecimal frequency;
     private Set mviewAdvFjgs = new HashSet(0);

    

	
    
    
   
    public BigDecimal getAjgid_() {
        return this.ajgid_;
    }
    
    public void setAjgid_(BigDecimal ajgid_) {
        this.ajgid_ = ajgid_;
    }
    public MviewAdvLog getMviewAdvLog() {
        return this.mviewAdvLog;
    }
    
    public void setMviewAdvLog(MviewAdvLog mviewAdvLog) {
        this.mviewAdvLog = mviewAdvLog;
    }
    public BigDecimal getAjgdeslen() {
        return this.ajgdeslen;
    }
    
    public void setAjgdeslen(BigDecimal ajgdeslen) {
        this.ajgdeslen = ajgdeslen;
    }
    public byte[] getAjgdes() {
        return this.ajgdes;
    }
    
    public void setAjgdes(byte[] ajgdes) {
        this.ajgdes = ajgdes;
    }
    public BigDecimal getHashvalue() {
        return this.hashvalue;
    }
    
    public void setHashvalue(BigDecimal hashvalue) {
        this.hashvalue = hashvalue;
    }
    public BigDecimal getFrequency() {
        return this.frequency;
    }
    
    public void setFrequency(BigDecimal frequency) {
        this.frequency = frequency;
    }
    public Set getMviewAdvFjgs() {
        return this.mviewAdvFjgs;
    }
    
    public void setMviewAdvFjgs(Set mviewAdvFjgs) {
        this.mviewAdvFjgs = mviewAdvFjgs;
    }




}


