package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * MviewRecommendationsId generated by hbm2java
 */
public class MviewRecommendationsId  implements java.io.Serializable {


     private BigDecimal runid;
     private String allTables;
     private String factTables;
     private String groupingLevels;
     private String queryText;
     private BigDecimal recommendationNumber;
     private String recommendedAction;
     private String mviewOwner;
     private String mviewName;
     private BigDecimal storageInBytes;
     private BigDecimal pctPerformanceGain;
     private BigDecimal benefitToCostRatio;

    

	
    
    
   
    public BigDecimal getRunid() {
        return this.runid;
    }
    
    public void setRunid(BigDecimal runid) {
        this.runid = runid;
    }
    public String getAllTables() {
        return this.allTables;
    }
    
    public void setAllTables(String allTables) {
        this.allTables = allTables;
    }
    public String getFactTables() {
        return this.factTables;
    }
    
    public void setFactTables(String factTables) {
        this.factTables = factTables;
    }
    public String getGroupingLevels() {
        return this.groupingLevels;
    }
    
    public void setGroupingLevels(String groupingLevels) {
        this.groupingLevels = groupingLevels;
    }
    public String getQueryText() {
        return this.queryText;
    }
    
    public void setQueryText(String queryText) {
        this.queryText = queryText;
    }
    public BigDecimal getRecommendationNumber() {
        return this.recommendationNumber;
    }
    
    public void setRecommendationNumber(BigDecimal recommendationNumber) {
        this.recommendationNumber = recommendationNumber;
    }
    public String getRecommendedAction() {
        return this.recommendedAction;
    }
    
    public void setRecommendedAction(String recommendedAction) {
        this.recommendedAction = recommendedAction;
    }
    public String getMviewOwner() {
        return this.mviewOwner;
    }
    
    public void setMviewOwner(String mviewOwner) {
        this.mviewOwner = mviewOwner;
    }
    public String getMviewName() {
        return this.mviewName;
    }
    
    public void setMviewName(String mviewName) {
        this.mviewName = mviewName;
    }
    public BigDecimal getStorageInBytes() {
        return this.storageInBytes;
    }
    
    public void setStorageInBytes(BigDecimal storageInBytes) {
        this.storageInBytes = storageInBytes;
    }
    public BigDecimal getPctPerformanceGain() {
        return this.pctPerformanceGain;
    }
    
    public void setPctPerformanceGain(BigDecimal pctPerformanceGain) {
        this.pctPerformanceGain = pctPerformanceGain;
    }
    public BigDecimal getBenefitToCostRatio() {
        return this.benefitToCostRatio;
    }
    
    public void setBenefitToCostRatio(BigDecimal benefitToCostRatio) {
        this.benefitToCostRatio = benefitToCostRatio;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MviewRecommendationsId) ) return false;
		 MviewRecommendationsId castOther = ( MviewRecommendationsId ) other; 
         
		 return ( (this.getRunid()==castOther.getRunid()) || ( this.getRunid()!=null && castOther.getRunid()!=null && this.getRunid().equals(castOther.getRunid()) ) )
 && ( (this.getAllTables()==castOther.getAllTables()) || ( this.getAllTables()!=null && castOther.getAllTables()!=null && this.getAllTables().equals(castOther.getAllTables()) ) )
 && ( (this.getFactTables()==castOther.getFactTables()) || ( this.getFactTables()!=null && castOther.getFactTables()!=null && this.getFactTables().equals(castOther.getFactTables()) ) )
 && ( (this.getGroupingLevels()==castOther.getGroupingLevels()) || ( this.getGroupingLevels()!=null && castOther.getGroupingLevels()!=null && this.getGroupingLevels().equals(castOther.getGroupingLevels()) ) )
 && ( (this.getQueryText()==castOther.getQueryText()) || ( this.getQueryText()!=null && castOther.getQueryText()!=null && this.getQueryText().equals(castOther.getQueryText()) ) )
 && ( (this.getRecommendationNumber()==castOther.getRecommendationNumber()) || ( this.getRecommendationNumber()!=null && castOther.getRecommendationNumber()!=null && this.getRecommendationNumber().equals(castOther.getRecommendationNumber()) ) )
 && ( (this.getRecommendedAction()==castOther.getRecommendedAction()) || ( this.getRecommendedAction()!=null && castOther.getRecommendedAction()!=null && this.getRecommendedAction().equals(castOther.getRecommendedAction()) ) )
 && ( (this.getMviewOwner()==castOther.getMviewOwner()) || ( this.getMviewOwner()!=null && castOther.getMviewOwner()!=null && this.getMviewOwner().equals(castOther.getMviewOwner()) ) )
 && ( (this.getMviewName()==castOther.getMviewName()) || ( this.getMviewName()!=null && castOther.getMviewName()!=null && this.getMviewName().equals(castOther.getMviewName()) ) )
 && ( (this.getStorageInBytes()==castOther.getStorageInBytes()) || ( this.getStorageInBytes()!=null && castOther.getStorageInBytes()!=null && this.getStorageInBytes().equals(castOther.getStorageInBytes()) ) )
 && ( (this.getPctPerformanceGain()==castOther.getPctPerformanceGain()) || ( this.getPctPerformanceGain()!=null && castOther.getPctPerformanceGain()!=null && this.getPctPerformanceGain().equals(castOther.getPctPerformanceGain()) ) )
 && ( (this.getBenefitToCostRatio()==castOther.getBenefitToCostRatio()) || ( this.getBenefitToCostRatio()!=null && castOther.getBenefitToCostRatio()!=null && this.getBenefitToCostRatio().equals(castOther.getBenefitToCostRatio()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRunid() == null ? 0 : this.getRunid().hashCode() );
         result = 37 * result + ( getAllTables() == null ? 0 : this.getAllTables().hashCode() );
         result = 37 * result + ( getFactTables() == null ? 0 : this.getFactTables().hashCode() );
         result = 37 * result + ( getGroupingLevels() == null ? 0 : this.getGroupingLevels().hashCode() );
         result = 37 * result + ( getQueryText() == null ? 0 : this.getQueryText().hashCode() );
         result = 37 * result + ( getRecommendationNumber() == null ? 0 : this.getRecommendationNumber().hashCode() );
         result = 37 * result + ( getRecommendedAction() == null ? 0 : this.getRecommendedAction().hashCode() );
         result = 37 * result + ( getMviewOwner() == null ? 0 : this.getMviewOwner().hashCode() );
         result = 37 * result + ( getMviewName() == null ? 0 : this.getMviewName().hashCode() );
         result = 37 * result + ( getStorageInBytes() == null ? 0 : this.getStorageInBytes().hashCode() );
         result = 37 * result + ( getPctPerformanceGain() == null ? 0 : this.getPctPerformanceGain().hashCode() );
         result = 37 * result + ( getBenefitToCostRatio() == null ? 0 : this.getBenefitToCostRatio().hashCode() );
         return result;
   }   


}


