package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * MviewEvaluationsId generated by hbm2java
 */
public class MviewEvaluationsId  implements java.io.Serializable {


     private BigDecimal runid;
     private String mviewOwner;
     private String mviewName;
     private BigDecimal rank;
     private BigDecimal storageInBytes;
     private BigDecimal frequency;
     private BigDecimal cumulativeBenefit;
     private BigDecimal benefitToCostRatio;

    

	
    
    
   
    public BigDecimal getRunid() {
        return this.runid;
    }
    
    public void setRunid(BigDecimal runid) {
        this.runid = runid;
    }
    public String getMviewOwner() {
        return this.mviewOwner;
    }
    
    public void setMviewOwner(String mviewOwner) {
        this.mviewOwner = mviewOwner;
    }
    public String getMviewName() {
        return this.mviewName;
    }
    
    public void setMviewName(String mviewName) {
        this.mviewName = mviewName;
    }
    public BigDecimal getRank() {
        return this.rank;
    }
    
    public void setRank(BigDecimal rank) {
        this.rank = rank;
    }
    public BigDecimal getStorageInBytes() {
        return this.storageInBytes;
    }
    
    public void setStorageInBytes(BigDecimal storageInBytes) {
        this.storageInBytes = storageInBytes;
    }
    public BigDecimal getFrequency() {
        return this.frequency;
    }
    
    public void setFrequency(BigDecimal frequency) {
        this.frequency = frequency;
    }
    public BigDecimal getCumulativeBenefit() {
        return this.cumulativeBenefit;
    }
    
    public void setCumulativeBenefit(BigDecimal cumulativeBenefit) {
        this.cumulativeBenefit = cumulativeBenefit;
    }
    public BigDecimal getBenefitToCostRatio() {
        return this.benefitToCostRatio;
    }
    
    public void setBenefitToCostRatio(BigDecimal benefitToCostRatio) {
        this.benefitToCostRatio = benefitToCostRatio;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MviewEvaluationsId) ) return false;
		 MviewEvaluationsId castOther = ( MviewEvaluationsId ) other; 
         
		 return ( (this.getRunid()==castOther.getRunid()) || ( this.getRunid()!=null && castOther.getRunid()!=null && this.getRunid().equals(castOther.getRunid()) ) )
 && ( (this.getMviewOwner()==castOther.getMviewOwner()) || ( this.getMviewOwner()!=null && castOther.getMviewOwner()!=null && this.getMviewOwner().equals(castOther.getMviewOwner()) ) )
 && ( (this.getMviewName()==castOther.getMviewName()) || ( this.getMviewName()!=null && castOther.getMviewName()!=null && this.getMviewName().equals(castOther.getMviewName()) ) )
 && ( (this.getRank()==castOther.getRank()) || ( this.getRank()!=null && castOther.getRank()!=null && this.getRank().equals(castOther.getRank()) ) )
 && ( (this.getStorageInBytes()==castOther.getStorageInBytes()) || ( this.getStorageInBytes()!=null && castOther.getStorageInBytes()!=null && this.getStorageInBytes().equals(castOther.getStorageInBytes()) ) )
 && ( (this.getFrequency()==castOther.getFrequency()) || ( this.getFrequency()!=null && castOther.getFrequency()!=null && this.getFrequency().equals(castOther.getFrequency()) ) )
 && ( (this.getCumulativeBenefit()==castOther.getCumulativeBenefit()) || ( this.getCumulativeBenefit()!=null && castOther.getCumulativeBenefit()!=null && this.getCumulativeBenefit().equals(castOther.getCumulativeBenefit()) ) )
 && ( (this.getBenefitToCostRatio()==castOther.getBenefitToCostRatio()) || ( this.getBenefitToCostRatio()!=null && castOther.getBenefitToCostRatio()!=null && this.getBenefitToCostRatio().equals(castOther.getBenefitToCostRatio()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRunid() == null ? 0 : this.getRunid().hashCode() );
         result = 37 * result + ( getMviewOwner() == null ? 0 : this.getMviewOwner().hashCode() );
         result = 37 * result + ( getMviewName() == null ? 0 : this.getMviewName().hashCode() );
         result = 37 * result + ( getRank() == null ? 0 : this.getRank().hashCode() );
         result = 37 * result + ( getStorageInBytes() == null ? 0 : this.getStorageInBytes().hashCode() );
         result = 37 * result + ( getFrequency() == null ? 0 : this.getFrequency().hashCode() );
         result = 37 * result + ( getCumulativeBenefit() == null ? 0 : this.getCumulativeBenefit().hashCode() );
         result = 37 * result + ( getBenefitToCostRatio() == null ? 0 : this.getBenefitToCostRatio().hashCode() );
         return result;
   }   


}


