package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA



/**
 * MviewAdvExceptions generated by hbm2java
 */
public class MviewAdvExceptions  implements java.io.Serializable {


     private MviewAdvExceptionsId id;
     private MviewAdvLog mviewAdvLog;

    

	
    
    
   
    public MviewAdvExceptionsId getId() {
        return this.id;
    }
    
    public void setId(MviewAdvExceptionsId id) {
        this.id = id;
    }
    public MviewAdvLog getMviewAdvLog() {
        return this.mviewAdvLog;
    }
    
    public void setMviewAdvLog(MviewAdvLog mviewAdvLog) {
        this.mviewAdvLog = mviewAdvLog;
    }




}


