package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * MviewAdvExceptionsId generated by hbm2java
 */
public class MviewAdvExceptionsId  implements java.io.Serializable {


     private BigDecimal runid_;
     private String owner;
     private String tableName;
     private String dimensionName;
     private String relationship;
     private Date badRowid;

    

    
   
    public BigDecimal getRunid_() {
        return this.runid_;
    }
    
    public void setRunid_(BigDecimal runid_) {
        this.runid_ = runid_;
    }
    public String getOwner() {
        return this.owner;
    }
    
    public void setOwner(String owner) {
        this.owner = owner;
    }
    public String getTableName() {
        return this.tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }
    public String getDimensionName() {
        return this.dimensionName;
    }
    
    public void setDimensionName(String dimensionName) {
        this.dimensionName = dimensionName;
    }
    public String getRelationship() {
        return this.relationship;
    }
    
    public void setRelationship(String relationship) {
        this.relationship = relationship;
    }
    public Date getBadRowid() {
        return this.badRowid;
    }
    
    public void setBadRowid(Date badRowid) {
        this.badRowid = badRowid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MviewAdvExceptionsId) ) return false;
		 MviewAdvExceptionsId castOther = ( MviewAdvExceptionsId ) other; 
         
		 return ( (this.getRunid_()==castOther.getRunid_()) || ( this.getRunid_()!=null && castOther.getRunid_()!=null && this.getRunid_().equals(castOther.getRunid_()) ) )
 && ( (this.getOwner()==castOther.getOwner()) || ( this.getOwner()!=null && castOther.getOwner()!=null && this.getOwner().equals(castOther.getOwner()) ) )
 && ( (this.getTableName()==castOther.getTableName()) || ( this.getTableName()!=null && castOther.getTableName()!=null && this.getTableName().equals(castOther.getTableName()) ) )
 && ( (this.getDimensionName()==castOther.getDimensionName()) || ( this.getDimensionName()!=null && castOther.getDimensionName()!=null && this.getDimensionName().equals(castOther.getDimensionName()) ) )
 && ( (this.getRelationship()==castOther.getRelationship()) || ( this.getRelationship()!=null && castOther.getRelationship()!=null && this.getRelationship().equals(castOther.getRelationship()) ) )
 && ( (this.getBadRowid()==castOther.getBadRowid()) || ( this.getBadRowid()!=null && castOther.getBadRowid()!=null && this.getBadRowid().equals(castOther.getBadRowid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRunid_() == null ? 0 : this.getRunid_().hashCode() );
         result = 37 * result + ( getOwner() == null ? 0 : this.getOwner().hashCode() );
         result = 37 * result + ( getTableName() == null ? 0 : this.getTableName().hashCode() );
         result = 37 * result + ( getDimensionName() == null ? 0 : this.getDimensionName().hashCode() );
         result = 37 * result + ( getRelationship() == null ? 0 : this.getRelationship().hashCode() );
         result = 37 * result + ( getBadRowid() == null ? 0 : this.getBadRowid().hashCode() );
         return result;
   }   


}


