package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MviewAdvWorkload generated by hbm2java
 */
public class MviewAdvWorkload  implements java.io.Serializable {


     private BigDecimal queryid_;
     private BigDecimal collectionid_;
     private Date collecttime;
     private String application;
     private BigDecimal cardinality;
     private BigDecimal resultsize;
     private String uname;
     private Date qdate;
     private BigDecimal priority;
     private BigDecimal execTime;
     private String sqlText;
     private BigDecimal sqlTextlen;
     private BigDecimal sqlHash;
     private byte[] sqlAddr;
     private BigDecimal frequency;
     private Set mviewAdvBasetables = new HashSet(0);

    

	
    
    
   
    public BigDecimal getQueryid_() {
        return this.queryid_;
    }
    
    public void setQueryid_(BigDecimal queryid_) {
        this.queryid_ = queryid_;
    }
    public BigDecimal getCollectionid_() {
        return this.collectionid_;
    }
    
    public void setCollectionid_(BigDecimal collectionid_) {
        this.collectionid_ = collectionid_;
    }
    public Date getCollecttime() {
        return this.collecttime;
    }
    
    public void setCollecttime(Date collecttime) {
        this.collecttime = collecttime;
    }
    public String getApplication() {
        return this.application;
    }
    
    public void setApplication(String application) {
        this.application = application;
    }
    public BigDecimal getCardinality() {
        return this.cardinality;
    }
    
    public void setCardinality(BigDecimal cardinality) {
        this.cardinality = cardinality;
    }
    public BigDecimal getResultsize() {
        return this.resultsize;
    }
    
    public void setResultsize(BigDecimal resultsize) {
        this.resultsize = resultsize;
    }
    public String getUname() {
        return this.uname;
    }
    
    public void setUname(String uname) {
        this.uname = uname;
    }
    public Date getQdate() {
        return this.qdate;
    }
    
    public void setQdate(Date qdate) {
        this.qdate = qdate;
    }
    public BigDecimal getPriority() {
        return this.priority;
    }
    
    public void setPriority(BigDecimal priority) {
        this.priority = priority;
    }
    public BigDecimal getExecTime() {
        return this.execTime;
    }
    
    public void setExecTime(BigDecimal execTime) {
        this.execTime = execTime;
    }
    public String getSqlText() {
        return this.sqlText;
    }
    
    public void setSqlText(String sqlText) {
        this.sqlText = sqlText;
    }
    public BigDecimal getSqlTextlen() {
        return this.sqlTextlen;
    }
    
    public void setSqlTextlen(BigDecimal sqlTextlen) {
        this.sqlTextlen = sqlTextlen;
    }
    public BigDecimal getSqlHash() {
        return this.sqlHash;
    }
    
    public void setSqlHash(BigDecimal sqlHash) {
        this.sqlHash = sqlHash;
    }
    public byte[] getSqlAddr() {
        return this.sqlAddr;
    }
    
    public void setSqlAddr(byte[] sqlAddr) {
        this.sqlAddr = sqlAddr;
    }
    public BigDecimal getFrequency() {
        return this.frequency;
    }
    
    public void setFrequency(BigDecimal frequency) {
        this.frequency = frequency;
    }
    public Set getMviewAdvBasetables() {
        return this.mviewAdvBasetables;
    }
    
    public void setMviewAdvBasetables(Set mviewAdvBasetables) {
        this.mviewAdvBasetables = mviewAdvBasetables;
    }




}


