package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * MviewAdvTempId generated by hbm2java
 */
public class MviewAdvTempId  implements java.io.Serializable {


     private BigDecimal id_;
     private BigDecimal seq_;
     private String text;

    

    
   
    public BigDecimal getId_() {
        return this.id_;
    }
    
    public void setId_(BigDecimal id_) {
        this.id_ = id_;
    }
    public BigDecimal getSeq_() {
        return this.seq_;
    }
    
    public void setSeq_(BigDecimal seq_) {
        this.seq_ = seq_;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MviewAdvTempId) ) return false;
		 MviewAdvTempId castOther = ( MviewAdvTempId ) other; 
         
		 return ( (this.getId_()==castOther.getId_()) || ( this.getId_()!=null && castOther.getId_()!=null && this.getId_().equals(castOther.getId_()) ) )
 && ( (this.getSeq_()==castOther.getSeq_()) || ( this.getSeq_()!=null && castOther.getSeq_()!=null && this.getSeq_().equals(castOther.getSeq_()) ) )
 && ( (this.getText()==castOther.getText()) || ( this.getText()!=null && castOther.getText()!=null && this.getText().equals(castOther.getText()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId_() == null ? 0 : this.getId_().hashCode() );
         result = 37 * result + ( getSeq_() == null ? 0 : this.getSeq_().hashCode() );
         result = 37 * result + ( getText() == null ? 0 : this.getText().hashCode() );
         return result;
   }   


}


