package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA



/**
 * MviewFilter generated by hbm2java
 */
public class MviewFilter  implements java.io.Serializable {


     private MviewFilterId id;

    

    
   
    public MviewFilterId getId() {
        return this.id;
    }
    
    public void setId(MviewFilterId id) {
        this.id = id;
    }




}


