package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * MviewAdvFilterId generated by hbm2java
 */
public class MviewAdvFilterId  implements java.io.Serializable {


     private BigDecimal filterid_;
     private BigDecimal subfilternum_;

    

    
   
    public BigDecimal getFilterid_() {
        return this.filterid_;
    }
    
    public void setFilterid_(BigDecimal filterid_) {
        this.filterid_ = filterid_;
    }
    public BigDecimal getSubfilternum_() {
        return this.subfilternum_;
    }
    
    public void setSubfilternum_(BigDecimal subfilternum_) {
        this.subfilternum_ = subfilternum_;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MviewAdvFilterId) ) return false;
		 MviewAdvFilterId castOther = ( MviewAdvFilterId ) other; 
         
		 return ( (this.getFilterid_()==castOther.getFilterid_()) || ( this.getFilterid_()!=null && castOther.getFilterid_()!=null && this.getFilterid_().equals(castOther.getFilterid_()) ) )
 && ( (this.getSubfilternum_()==castOther.getSubfilternum_()) || ( this.getSubfilternum_()!=null && castOther.getSubfilternum_()!=null && this.getSubfilternum_().equals(castOther.getSubfilternum_()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getFilterid_() == null ? 0 : this.getFilterid_().hashCode() );
         result = 37 * result + ( getSubfilternum_() == null ? 0 : this.getSubfilternum_().hashCode() );
         return result;
   }   


}


