package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA



/**
 * MviewRecommendations generated by hbm2java
 */
public class MviewRecommendations  implements java.io.Serializable {


     private MviewRecommendationsId id;

    

    
   
    public MviewRecommendationsId getId() {
        return this.id;
    }
    
    public void setId(MviewRecommendationsId id) {
        this.id = id;
    }




}


