package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA



/**
 * Ol generated by hbm2java
 */
public class Ol  implements java.io.Serializable {


     private OlId id;

    

    
   
    public OlId getId() {
        return this.id;
    }
    
    public void setId(OlId id) {
        this.id = id;
    }




}


