package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.sql.Clob;

/**
 * OlhintsId generated by hbm2java
 */
public class OlhintsId  implements java.io.Serializable {


     private String olName;
     private BigDecimal hint_;
     private String category;
     private BigDecimal hintType;
     private String hintText;
     private BigDecimal stage_;
     private BigDecimal node_;
     private String tableName;
     private BigDecimal tableTin;
     private BigDecimal tablePos;
     private BigDecimal refId;
     private String userTableName;
     private Double cost;
     private Double cardinality;
     private Double bytes;
     private BigDecimal hintTextoff;
     private BigDecimal hintTextlen;
     private String joinPred;
     private BigDecimal spare1;
     private BigDecimal spare2;
     private Clob hintString;

    

    
   
    public String getOlName() {
        return this.olName;
    }
    
    public void setOlName(String olName) {
        this.olName = olName;
    }
    public BigDecimal getHint_() {
        return this.hint_;
    }
    
    public void setHint_(BigDecimal hint_) {
        this.hint_ = hint_;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public BigDecimal getHintType() {
        return this.hintType;
    }
    
    public void setHintType(BigDecimal hintType) {
        this.hintType = hintType;
    }
    public String getHintText() {
        return this.hintText;
    }
    
    public void setHintText(String hintText) {
        this.hintText = hintText;
    }
    public BigDecimal getStage_() {
        return this.stage_;
    }
    
    public void setStage_(BigDecimal stage_) {
        this.stage_ = stage_;
    }
    public BigDecimal getNode_() {
        return this.node_;
    }
    
    public void setNode_(BigDecimal node_) {
        this.node_ = node_;
    }
    public String getTableName() {
        return this.tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }
    public BigDecimal getTableTin() {
        return this.tableTin;
    }
    
    public void setTableTin(BigDecimal tableTin) {
        this.tableTin = tableTin;
    }
    public BigDecimal getTablePos() {
        return this.tablePos;
    }
    
    public void setTablePos(BigDecimal tablePos) {
        this.tablePos = tablePos;
    }
    public BigDecimal getRefId() {
        return this.refId;
    }
    
    public void setRefId(BigDecimal refId) {
        this.refId = refId;
    }
    public String getUserTableName() {
        return this.userTableName;
    }
    
    public void setUserTableName(String userTableName) {
        this.userTableName = userTableName;
    }
    public Double getCost() {
        return this.cost;
    }
    
    public void setCost(Double cost) {
        this.cost = cost;
    }
    public Double getCardinality() {
        return this.cardinality;
    }
    
    public void setCardinality(Double cardinality) {
        this.cardinality = cardinality;
    }
    public Double getBytes() {
        return this.bytes;
    }
    
    public void setBytes(Double bytes) {
        this.bytes = bytes;
    }
    public BigDecimal getHintTextoff() {
        return this.hintTextoff;
    }
    
    public void setHintTextoff(BigDecimal hintTextoff) {
        this.hintTextoff = hintTextoff;
    }
    public BigDecimal getHintTextlen() {
        return this.hintTextlen;
    }
    
    public void setHintTextlen(BigDecimal hintTextlen) {
        this.hintTextlen = hintTextlen;
    }
    public String getJoinPred() {
        return this.joinPred;
    }
    
    public void setJoinPred(String joinPred) {
        this.joinPred = joinPred;
    }
    public BigDecimal getSpare1() {
        return this.spare1;
    }
    
    public void setSpare1(BigDecimal spare1) {
        this.spare1 = spare1;
    }
    public BigDecimal getSpare2() {
        return this.spare2;
    }
    
    public void setSpare2(BigDecimal spare2) {
        this.spare2 = spare2;
    }
    public Clob getHintString() {
        return this.hintString;
    }
    
    public void setHintString(Clob hintString) {
        this.hintString = hintString;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OlhintsId) ) return false;
		 OlhintsId castOther = ( OlhintsId ) other; 
         
		 return ( (this.getOlName()==castOther.getOlName()) || ( this.getOlName()!=null && castOther.getOlName()!=null && this.getOlName().equals(castOther.getOlName()) ) )
 && ( (this.getHint_()==castOther.getHint_()) || ( this.getHint_()!=null && castOther.getHint_()!=null && this.getHint_().equals(castOther.getHint_()) ) )
 && ( (this.getCategory()==castOther.getCategory()) || ( this.getCategory()!=null && castOther.getCategory()!=null && this.getCategory().equals(castOther.getCategory()) ) )
 && ( (this.getHintType()==castOther.getHintType()) || ( this.getHintType()!=null && castOther.getHintType()!=null && this.getHintType().equals(castOther.getHintType()) ) )
 && ( (this.getHintText()==castOther.getHintText()) || ( this.getHintText()!=null && castOther.getHintText()!=null && this.getHintText().equals(castOther.getHintText()) ) )
 && ( (this.getStage_()==castOther.getStage_()) || ( this.getStage_()!=null && castOther.getStage_()!=null && this.getStage_().equals(castOther.getStage_()) ) )
 && ( (this.getNode_()==castOther.getNode_()) || ( this.getNode_()!=null && castOther.getNode_()!=null && this.getNode_().equals(castOther.getNode_()) ) )
 && ( (this.getTableName()==castOther.getTableName()) || ( this.getTableName()!=null && castOther.getTableName()!=null && this.getTableName().equals(castOther.getTableName()) ) )
 && ( (this.getTableTin()==castOther.getTableTin()) || ( this.getTableTin()!=null && castOther.getTableTin()!=null && this.getTableTin().equals(castOther.getTableTin()) ) )
 && ( (this.getTablePos()==castOther.getTablePos()) || ( this.getTablePos()!=null && castOther.getTablePos()!=null && this.getTablePos().equals(castOther.getTablePos()) ) )
 && ( (this.getRefId()==castOther.getRefId()) || ( this.getRefId()!=null && castOther.getRefId()!=null && this.getRefId().equals(castOther.getRefId()) ) )
 && ( (this.getUserTableName()==castOther.getUserTableName()) || ( this.getUserTableName()!=null && castOther.getUserTableName()!=null && this.getUserTableName().equals(castOther.getUserTableName()) ) )
 && ( (this.getCost()==castOther.getCost()) || ( this.getCost()!=null && castOther.getCost()!=null && this.getCost().equals(castOther.getCost()) ) )
 && ( (this.getCardinality()==castOther.getCardinality()) || ( this.getCardinality()!=null && castOther.getCardinality()!=null && this.getCardinality().equals(castOther.getCardinality()) ) )
 && ( (this.getBytes()==castOther.getBytes()) || ( this.getBytes()!=null && castOther.getBytes()!=null && this.getBytes().equals(castOther.getBytes()) ) )
 && ( (this.getHintTextoff()==castOther.getHintTextoff()) || ( this.getHintTextoff()!=null && castOther.getHintTextoff()!=null && this.getHintTextoff().equals(castOther.getHintTextoff()) ) )
 && ( (this.getHintTextlen()==castOther.getHintTextlen()) || ( this.getHintTextlen()!=null && castOther.getHintTextlen()!=null && this.getHintTextlen().equals(castOther.getHintTextlen()) ) )
 && ( (this.getJoinPred()==castOther.getJoinPred()) || ( this.getJoinPred()!=null && castOther.getJoinPred()!=null && this.getJoinPred().equals(castOther.getJoinPred()) ) )
 && ( (this.getSpare1()==castOther.getSpare1()) || ( this.getSpare1()!=null && castOther.getSpare1()!=null && this.getSpare1().equals(castOther.getSpare1()) ) )
 && ( (this.getSpare2()==castOther.getSpare2()) || ( this.getSpare2()!=null && castOther.getSpare2()!=null && this.getSpare2().equals(castOther.getSpare2()) ) )
 && ( (this.getHintString()==castOther.getHintString()) || ( this.getHintString()!=null && castOther.getHintString()!=null && this.getHintString().equals(castOther.getHintString()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getOlName() == null ? 0 : this.getOlName().hashCode() );
         result = 37 * result + ( getHint_() == null ? 0 : this.getHint_().hashCode() );
         result = 37 * result + ( getCategory() == null ? 0 : this.getCategory().hashCode() );
         result = 37 * result + ( getHintType() == null ? 0 : this.getHintType().hashCode() );
         result = 37 * result + ( getHintText() == null ? 0 : this.getHintText().hashCode() );
         result = 37 * result + ( getStage_() == null ? 0 : this.getStage_().hashCode() );
         result = 37 * result + ( getNode_() == null ? 0 : this.getNode_().hashCode() );
         result = 37 * result + ( getTableName() == null ? 0 : this.getTableName().hashCode() );
         result = 37 * result + ( getTableTin() == null ? 0 : this.getTableTin().hashCode() );
         result = 37 * result + ( getTablePos() == null ? 0 : this.getTablePos().hashCode() );
         result = 37 * result + ( getRefId() == null ? 0 : this.getRefId().hashCode() );
         result = 37 * result + ( getUserTableName() == null ? 0 : this.getUserTableName().hashCode() );
         result = 37 * result + ( getCost() == null ? 0 : this.getCost().hashCode() );
         result = 37 * result + ( getCardinality() == null ? 0 : this.getCardinality().hashCode() );
         result = 37 * result + ( getBytes() == null ? 0 : this.getBytes().hashCode() );
         result = 37 * result + ( getHintTextoff() == null ? 0 : this.getHintTextoff().hashCode() );
         result = 37 * result + ( getHintTextlen() == null ? 0 : this.getHintTextlen().hashCode() );
         result = 37 * result + ( getJoinPred() == null ? 0 : this.getJoinPred().hashCode() );
         result = 37 * result + ( getSpare1() == null ? 0 : this.getSpare1().hashCode() );
         result = 37 * result + ( getSpare2() == null ? 0 : this.getSpare2().hashCode() );
         result = 37 * result + ( getHintString() == null ? 0 : this.getHintString().hashCode() );
         return result;
   }   


}


