package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Date;

/**
 * OlId generated by hbm2java
 */
public class OlId  implements java.io.Serializable {


     private String olName;
     private String sqlText;
     private BigDecimal textlen;
     private byte[] signature;
     private BigDecimal hashValue;
     private BigDecimal hashValue2;
     private String category;
     private String version;
     private String creator;
     private Date timestamp;
     private BigDecimal flags;
     private BigDecimal hintcount;
     private BigDecimal spare1;
     private String spare2;

    

    
   
    public String getOlName() {
        return this.olName;
    }
    
    public void setOlName(String olName) {
        this.olName = olName;
    }
    public String getSqlText() {
        return this.sqlText;
    }
    
    public void setSqlText(String sqlText) {
        this.sqlText = sqlText;
    }
    public BigDecimal getTextlen() {
        return this.textlen;
    }
    
    public void setTextlen(BigDecimal textlen) {
        this.textlen = textlen;
    }
    public byte[] getSignature() {
        return this.signature;
    }
    
    public void setSignature(byte[] signature) {
        this.signature = signature;
    }
    public BigDecimal getHashValue() {
        return this.hashValue;
    }
    
    public void setHashValue(BigDecimal hashValue) {
        this.hashValue = hashValue;
    }
    public BigDecimal getHashValue2() {
        return this.hashValue2;
    }
    
    public void setHashValue2(BigDecimal hashValue2) {
        this.hashValue2 = hashValue2;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public String getVersion() {
        return this.version;
    }
    
    public void setVersion(String version) {
        this.version = version;
    }
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    public BigDecimal getFlags() {
        return this.flags;
    }
    
    public void setFlags(BigDecimal flags) {
        this.flags = flags;
    }
    public BigDecimal getHintcount() {
        return this.hintcount;
    }
    
    public void setHintcount(BigDecimal hintcount) {
        this.hintcount = hintcount;
    }
    public BigDecimal getSpare1() {
        return this.spare1;
    }
    
    public void setSpare1(BigDecimal spare1) {
        this.spare1 = spare1;
    }
    public String getSpare2() {
        return this.spare2;
    }
    
    public void setSpare2(String spare2) {
        this.spare2 = spare2;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OlId) ) return false;
		 OlId castOther = ( OlId ) other; 
         
		 return ( (this.getOlName()==castOther.getOlName()) || ( this.getOlName()!=null && castOther.getOlName()!=null && this.getOlName().equals(castOther.getOlName()) ) )
 && ( (this.getSqlText()==castOther.getSqlText()) || ( this.getSqlText()!=null && castOther.getSqlText()!=null && this.getSqlText().equals(castOther.getSqlText()) ) )
 && ( (this.getTextlen()==castOther.getTextlen()) || ( this.getTextlen()!=null && castOther.getTextlen()!=null && this.getTextlen().equals(castOther.getTextlen()) ) )
 && ( (this.getSignature()==castOther.getSignature()) || ( this.getSignature()!=null && castOther.getSignature()!=null && Arrays.equals(this.getSignature(), castOther.getSignature()) ) )
 && ( (this.getHashValue()==castOther.getHashValue()) || ( this.getHashValue()!=null && castOther.getHashValue()!=null && this.getHashValue().equals(castOther.getHashValue()) ) )
 && ( (this.getHashValue2()==castOther.getHashValue2()) || ( this.getHashValue2()!=null && castOther.getHashValue2()!=null && this.getHashValue2().equals(castOther.getHashValue2()) ) )
 && ( (this.getCategory()==castOther.getCategory()) || ( this.getCategory()!=null && castOther.getCategory()!=null && this.getCategory().equals(castOther.getCategory()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
 && ( (this.getCreator()==castOther.getCreator()) || ( this.getCreator()!=null && castOther.getCreator()!=null && this.getCreator().equals(castOther.getCreator()) ) )
 && ( (this.getTimestamp()==castOther.getTimestamp()) || ( this.getTimestamp()!=null && castOther.getTimestamp()!=null && this.getTimestamp().equals(castOther.getTimestamp()) ) )
 && ( (this.getFlags()==castOther.getFlags()) || ( this.getFlags()!=null && castOther.getFlags()!=null && this.getFlags().equals(castOther.getFlags()) ) )
 && ( (this.getHintcount()==castOther.getHintcount()) || ( this.getHintcount()!=null && castOther.getHintcount()!=null && this.getHintcount().equals(castOther.getHintcount()) ) )
 && ( (this.getSpare1()==castOther.getSpare1()) || ( this.getSpare1()!=null && castOther.getSpare1()!=null && this.getSpare1().equals(castOther.getSpare1()) ) )
 && ( (this.getSpare2()==castOther.getSpare2()) || ( this.getSpare2()!=null && castOther.getSpare2()!=null && this.getSpare2().equals(castOther.getSpare2()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getOlName() == null ? 0 : this.getOlName().hashCode() );
         result = 37 * result + ( getSqlText() == null ? 0 : this.getSqlText().hashCode() );
         result = 37 * result + ( getTextlen() == null ? 0 : this.getTextlen().hashCode() );
         int signatureHashcode = 0;
         byte[] signatureProperty = this.getSignature();
         if(signatureProperty != null) {
             signatureHashcode = 1;
             for (int i=0; i<signatureProperty.length; i++) {
                 signatureHashcode = 37 * signatureHashcode + signatureProperty[i];
             }
         }

         result = 37 * result + signatureHashcode;

         result = 37 * result + ( getHashValue() == null ? 0 : this.getHashValue().hashCode() );
         result = 37 * result + ( getHashValue2() == null ? 0 : this.getHashValue2().hashCode() );
         result = 37 * result + ( getCategory() == null ? 0 : this.getCategory().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         result = 37 * result + ( getCreator() == null ? 0 : this.getCreator().hashCode() );
         result = 37 * result + ( getTimestamp() == null ? 0 : this.getTimestamp().hashCode() );
         result = 37 * result + ( getFlags() == null ? 0 : this.getFlags().hashCode() );
         result = 37 * result + ( getHintcount() == null ? 0 : this.getHintcount().hashCode() );
         result = 37 * result + ( getSpare1() == null ? 0 : this.getSpare1().hashCode() );
         result = 37 * result + ( getSpare2() == null ? 0 : this.getSpare2().hashCode() );
         return result;
   }   


}


