package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA



/**
 * Olnodes generated by hbm2java
 */
public class Olnodes  implements java.io.Serializable {


     private OlnodesId id;

    

    
   
    public OlnodesId getId() {
        return this.id;
    }
    
    public void setId(OlnodesId id) {
        this.id = id;
    }




}


