package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * ProductPrivsId generated by hbm2java
 */
public class ProductPrivsId  implements java.io.Serializable {


     private String product;
     private String userid;
     private String attribute;
     private String scope;
     private BigDecimal numericValue;
     private String charValue;
     private Date dateValue;
     private String longValue;

    

	
    
    
   
    public String getProduct() {
        return this.product;
    }
    
    public void setProduct(String product) {
        this.product = product;
    }
    public String getUserid() {
        return this.userid;
    }
    
    public void setUserid(String userid) {
        this.userid = userid;
    }
    public String getAttribute() {
        return this.attribute;
    }
    
    public void setAttribute(String attribute) {
        this.attribute = attribute;
    }
    public String getScope() {
        return this.scope;
    }
    
    public void setScope(String scope) {
        this.scope = scope;
    }
    public BigDecimal getNumericValue() {
        return this.numericValue;
    }
    
    public void setNumericValue(BigDecimal numericValue) {
        this.numericValue = numericValue;
    }
    public String getCharValue() {
        return this.charValue;
    }
    
    public void setCharValue(String charValue) {
        this.charValue = charValue;
    }
    public Date getDateValue() {
        return this.dateValue;
    }
    
    public void setDateValue(Date dateValue) {
        this.dateValue = dateValue;
    }
    public String getLongValue() {
        return this.longValue;
    }
    
    public void setLongValue(String longValue) {
        this.longValue = longValue;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProductPrivsId) ) return false;
		 ProductPrivsId castOther = ( ProductPrivsId ) other; 
         
		 return ( (this.getProduct()==castOther.getProduct()) || ( this.getProduct()!=null && castOther.getProduct()!=null && this.getProduct().equals(castOther.getProduct()) ) )
 && ( (this.getUserid()==castOther.getUserid()) || ( this.getUserid()!=null && castOther.getUserid()!=null && this.getUserid().equals(castOther.getUserid()) ) )
 && ( (this.getAttribute()==castOther.getAttribute()) || ( this.getAttribute()!=null && castOther.getAttribute()!=null && this.getAttribute().equals(castOther.getAttribute()) ) )
 && ( (this.getScope()==castOther.getScope()) || ( this.getScope()!=null && castOther.getScope()!=null && this.getScope().equals(castOther.getScope()) ) )
 && ( (this.getNumericValue()==castOther.getNumericValue()) || ( this.getNumericValue()!=null && castOther.getNumericValue()!=null && this.getNumericValue().equals(castOther.getNumericValue()) ) )
 && ( (this.getCharValue()==castOther.getCharValue()) || ( this.getCharValue()!=null && castOther.getCharValue()!=null && this.getCharValue().equals(castOther.getCharValue()) ) )
 && ( (this.getDateValue()==castOther.getDateValue()) || ( this.getDateValue()!=null && castOther.getDateValue()!=null && this.getDateValue().equals(castOther.getDateValue()) ) )
 && ( (this.getLongValue()==castOther.getLongValue()) || ( this.getLongValue()!=null && castOther.getLongValue()!=null && this.getLongValue().equals(castOther.getLongValue()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getProduct() == null ? 0 : this.getProduct().hashCode() );
         result = 37 * result + ( getUserid() == null ? 0 : this.getUserid().hashCode() );
         result = 37 * result + ( getAttribute() == null ? 0 : this.getAttribute().hashCode() );
         result = 37 * result + ( getScope() == null ? 0 : this.getScope().hashCode() );
         result = 37 * result + ( getNumericValue() == null ? 0 : this.getNumericValue().hashCode() );
         result = 37 * result + ( getCharValue() == null ? 0 : this.getCharValue().hashCode() );
         result = 37 * result + ( getDateValue() == null ? 0 : this.getDateValue().hashCode() );
         result = 37 * result + ( getLongValue() == null ? 0 : this.getLongValue().hashCode() );
         return result;
   }   


}


