package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.sql.Clob;
import java.util.HashSet;
import java.util.Set;

/**
 * RepcatTemplateParms generated by hbm2java
 */
public class RepcatTemplateParms  implements java.io.Serializable {


     private BigDecimal templateParameterId;
     private RepcatRefreshTemplates repcatRefreshTemplates;
     private String parameterName;
     private Clob defaultParmValue;
     private String promptString;
     private String userOverride;
     private Set repcatObjectParmses = new HashSet(0);
     private Set repcatUserParmValueses = new HashSet(0);

    

	
    
    
   
    public BigDecimal getTemplateParameterId() {
        return this.templateParameterId;
    }
    
    public void setTemplateParameterId(BigDecimal templateParameterId) {
        this.templateParameterId = templateParameterId;
    }
    public RepcatRefreshTemplates getRepcatRefreshTemplates() {
        return this.repcatRefreshTemplates;
    }
    
    public void setRepcatRefreshTemplates(RepcatRefreshTemplates repcatRefreshTemplates) {
        this.repcatRefreshTemplates = repcatRefreshTemplates;
    }
    public String getParameterName() {
        return this.parameterName;
    }
    
    public void setParameterName(String parameterName) {
        this.parameterName = parameterName;
    }
    public Clob getDefaultParmValue() {
        return this.defaultParmValue;
    }
    
    public void setDefaultParmValue(Clob defaultParmValue) {
        this.defaultParmValue = defaultParmValue;
    }
    public String getPromptString() {
        return this.promptString;
    }
    
    public void setPromptString(String promptString) {
        this.promptString = promptString;
    }
    public String getUserOverride() {
        return this.userOverride;
    }
    
    public void setUserOverride(String userOverride) {
        this.userOverride = userOverride;
    }
    public Set getRepcatObjectParmses() {
        return this.repcatObjectParmses;
    }
    
    public void setRepcatObjectParmses(Set repcatObjectParmses) {
        this.repcatObjectParmses = repcatObjectParmses;
    }
    public Set getRepcatUserParmValueses() {
        return this.repcatUserParmValueses;
    }
    
    public void setRepcatUserParmValueses(Set repcatUserParmValueses) {
        this.repcatUserParmValueses = repcatUserParmValueses;
    }




}


