package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA



/**
 * RepcatRuntimeParms generated by hbm2java
 */
public class RepcatRuntimeParms  implements java.io.Serializable {


     private RepcatRuntimeParmsId id;

    

    
   
    public RepcatRuntimeParmsId getId() {
        return this.id;
    }
    
    public void setId(RepcatRuntimeParmsId id) {
        this.id = id;
    }




}


