package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * RepcatGeneratedId generated by hbm2java
 */
public class RepcatGeneratedId  implements java.io.Serializable {


     private String sname;
     private String oname;
     private BigDecimal type;
     private String baseSname;
     private String baseOname;
     private BigDecimal baseType;

    

    
   
    public String getSname() {
        return this.sname;
    }
    
    public void setSname(String sname) {
        this.sname = sname;
    }
    public String getOname() {
        return this.oname;
    }
    
    public void setOname(String oname) {
        this.oname = oname;
    }
    public BigDecimal getType() {
        return this.type;
    }
    
    public void setType(BigDecimal type) {
        this.type = type;
    }
    public String getBaseSname() {
        return this.baseSname;
    }
    
    public void setBaseSname(String baseSname) {
        this.baseSname = baseSname;
    }
    public String getBaseOname() {
        return this.baseOname;
    }
    
    public void setBaseOname(String baseOname) {
        this.baseOname = baseOname;
    }
    public BigDecimal getBaseType() {
        return this.baseType;
    }
    
    public void setBaseType(BigDecimal baseType) {
        this.baseType = baseType;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RepcatGeneratedId) ) return false;
		 RepcatGeneratedId castOther = ( RepcatGeneratedId ) other; 
         
		 return ( (this.getSname()==castOther.getSname()) || ( this.getSname()!=null && castOther.getSname()!=null && this.getSname().equals(castOther.getSname()) ) )
 && ( (this.getOname()==castOther.getOname()) || ( this.getOname()!=null && castOther.getOname()!=null && this.getOname().equals(castOther.getOname()) ) )
 && ( (this.getType()==castOther.getType()) || ( this.getType()!=null && castOther.getType()!=null && this.getType().equals(castOther.getType()) ) )
 && ( (this.getBaseSname()==castOther.getBaseSname()) || ( this.getBaseSname()!=null && castOther.getBaseSname()!=null && this.getBaseSname().equals(castOther.getBaseSname()) ) )
 && ( (this.getBaseOname()==castOther.getBaseOname()) || ( this.getBaseOname()!=null && castOther.getBaseOname()!=null && this.getBaseOname().equals(castOther.getBaseOname()) ) )
 && ( (this.getBaseType()==castOther.getBaseType()) || ( this.getBaseType()!=null && castOther.getBaseType()!=null && this.getBaseType().equals(castOther.getBaseType()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSname() == null ? 0 : this.getSname().hashCode() );
         result = 37 * result + ( getOname() == null ? 0 : this.getOname().hashCode() );
         result = 37 * result + ( getType() == null ? 0 : this.getType().hashCode() );
         result = 37 * result + ( getBaseSname() == null ? 0 : this.getBaseSname().hashCode() );
         result = 37 * result + ( getBaseOname() == null ? 0 : this.getBaseOname().hashCode() );
         result = 37 * result + ( getBaseType() == null ? 0 : this.getBaseType().hashCode() );
         return result;
   }   


}


