package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.util.Arrays;

/**
 * RepcatSitesNewId generated by hbm2java
 */
public class RepcatSitesNewId  implements java.io.Serializable {


     private byte[] extensionId;
     private String gowner;
     private String gname;
     private String dblink;

    

    
   
    public byte[] getExtensionId() {
        return this.extensionId;
    }
    
    public void setExtensionId(byte[] extensionId) {
        this.extensionId = extensionId;
    }
    public String getGowner() {
        return this.gowner;
    }
    
    public void setGowner(String gowner) {
        this.gowner = gowner;
    }
    public String getGname() {
        return this.gname;
    }
    
    public void setGname(String gname) {
        this.gname = gname;
    }
    public String getDblink() {
        return this.dblink;
    }
    
    public void setDblink(String dblink) {
        this.dblink = dblink;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RepcatSitesNewId) ) return false;
		 RepcatSitesNewId castOther = ( RepcatSitesNewId ) other; 
         
		 return ( (this.getExtensionId()==castOther.getExtensionId()) || ( this.getExtensionId()!=null && castOther.getExtensionId()!=null && Arrays.equals(this.getExtensionId(), castOther.getExtensionId()) ) )
 && ( (this.getGowner()==castOther.getGowner()) || ( this.getGowner()!=null && castOther.getGowner()!=null && this.getGowner().equals(castOther.getGowner()) ) )
 && ( (this.getGname()==castOther.getGname()) || ( this.getGname()!=null && castOther.getGname()!=null && this.getGname().equals(castOther.getGname()) ) )
 && ( (this.getDblink()==castOther.getDblink()) || ( this.getDblink()!=null && castOther.getDblink()!=null && this.getDblink().equals(castOther.getDblink()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         int extensionIdHashcode = 0;
         byte[] extensionIdProperty = this.getExtensionId();
         if(extensionIdProperty != null) {
             extensionIdHashcode = 1;
             for (int i=0; i<extensionIdProperty.length; i++) {
                 extensionIdHashcode = 37 * extensionIdHashcode + extensionIdProperty[i];
             }
         }

         result = 37 * result + extensionIdHashcode;

         result = 37 * result + ( getGowner() == null ? 0 : this.getGowner().hashCode() );
         result = 37 * result + ( getGname() == null ? 0 : this.getGname().hashCode() );
         result = 37 * result + ( getDblink() == null ? 0 : this.getDblink().hashCode() );
         return result;
   }   


}


