package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * RepcatFlavorObjects generated by hbm2java
 */
public class RepcatFlavorObjects  implements java.io.Serializable {


     private RepcatFlavorObjectsId id;
     private RepcatRepcat repcatRepcat;
     private BigDecimal version_;
     private byte[] hashcode;
     private byte[] columnsPresent;

    

	
    
    
   
    public RepcatFlavorObjectsId getId() {
        return this.id;
    }
    
    public void setId(RepcatFlavorObjectsId id) {
        this.id = id;
    }
    public RepcatRepcat getRepcatRepcat() {
        return this.repcatRepcat;
    }
    
    public void setRepcatRepcat(RepcatRepcat repcatRepcat) {
        this.repcatRepcat = repcatRepcat;
    }
    public BigDecimal getVersion_() {
        return this.version_;
    }
    
    public void setVersion_(BigDecimal version_) {
        this.version_ = version_;
    }
    public byte[] getHashcode() {
        return this.hashcode;
    }
    
    public void setHashcode(byte[] hashcode) {
        this.hashcode = hashcode;
    }
    public byte[] getColumnsPresent() {
        return this.columnsPresent;
    }
    
    public void setColumnsPresent(byte[] columnsPresent) {
        this.columnsPresent = columnsPresent;
    }




}


