package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;

/**
 * RepcatConflict generated by hbm2java
 */
public class RepcatConflict  implements java.io.Serializable {


     private RepcatConflictId id;
     private Set repcatResolutions = new HashSet(0);
     private Set repcatAuditColumns = new HashSet(0);

    

	
    
    
   
    public RepcatConflictId getId() {
        return this.id;
    }
    
    public void setId(RepcatConflictId id) {
        this.id = id;
    }
    public Set getRepcatResolutions() {
        return this.repcatResolutions;
    }
    
    public void setRepcatResolutions(Set repcatResolutions) {
        this.repcatResolutions = repcatResolutions;
    }
    public Set getRepcatAuditColumns() {
        return this.repcatAuditColumns;
    }
    
    public void setRepcatAuditColumns(Set repcatAuditColumns) {
        this.repcatAuditColumns = repcatAuditColumns;
    }




}


