package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * RepcatAuditAttribute generated by hbm2java
 */
public class RepcatAuditAttribute  implements java.io.Serializable {


     private String attribute;
     private BigDecimal dataTypeId;
     private BigDecimal dataLength;
     private String source;
     private Set repcatAuditColumns = new HashSet(0);

    

	
    
    
   
    public String getAttribute() {
        return this.attribute;
    }
    
    public void setAttribute(String attribute) {
        this.attribute = attribute;
    }
    public BigDecimal getDataTypeId() {
        return this.dataTypeId;
    }
    
    public void setDataTypeId(BigDecimal dataTypeId) {
        this.dataTypeId = dataTypeId;
    }
    public BigDecimal getDataLength() {
        return this.dataLength;
    }
    
    public void setDataLength(BigDecimal dataLength) {
        this.dataLength = dataLength;
    }
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }
    public Set getRepcatAuditColumns() {
        return this.repcatAuditColumns;
    }
    
    public void setRepcatAuditColumns(Set repcatAuditColumns) {
        this.repcatAuditColumns = repcatAuditColumns;
    }




}


