package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * RepcatFlavorObjectsId generated by hbm2java
 */
public class RepcatFlavorObjectsId  implements java.io.Serializable {


     private String sname;
     private String oname;
     private BigDecimal type;
     private String gname;
     private BigDecimal flavorId;
     private String gowner;

    

    
   
    public String getSname() {
        return this.sname;
    }
    
    public void setSname(String sname) {
        this.sname = sname;
    }
    public String getOname() {
        return this.oname;
    }
    
    public void setOname(String oname) {
        this.oname = oname;
    }
    public BigDecimal getType() {
        return this.type;
    }
    
    public void setType(BigDecimal type) {
        this.type = type;
    }
    public String getGname() {
        return this.gname;
    }
    
    public void setGname(String gname) {
        this.gname = gname;
    }
    public BigDecimal getFlavorId() {
        return this.flavorId;
    }
    
    public void setFlavorId(BigDecimal flavorId) {
        this.flavorId = flavorId;
    }
    public String getGowner() {
        return this.gowner;
    }
    
    public void setGowner(String gowner) {
        this.gowner = gowner;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RepcatFlavorObjectsId) ) return false;
		 RepcatFlavorObjectsId castOther = ( RepcatFlavorObjectsId ) other; 
         
		 return ( (this.getSname()==castOther.getSname()) || ( this.getSname()!=null && castOther.getSname()!=null && this.getSname().equals(castOther.getSname()) ) )
 && ( (this.getOname()==castOther.getOname()) || ( this.getOname()!=null && castOther.getOname()!=null && this.getOname().equals(castOther.getOname()) ) )
 && ( (this.getType()==castOther.getType()) || ( this.getType()!=null && castOther.getType()!=null && this.getType().equals(castOther.getType()) ) )
 && ( (this.getGname()==castOther.getGname()) || ( this.getGname()!=null && castOther.getGname()!=null && this.getGname().equals(castOther.getGname()) ) )
 && ( (this.getFlavorId()==castOther.getFlavorId()) || ( this.getFlavorId()!=null && castOther.getFlavorId()!=null && this.getFlavorId().equals(castOther.getFlavorId()) ) )
 && ( (this.getGowner()==castOther.getGowner()) || ( this.getGowner()!=null && castOther.getGowner()!=null && this.getGowner().equals(castOther.getGowner()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSname() == null ? 0 : this.getSname().hashCode() );
         result = 37 * result + ( getOname() == null ? 0 : this.getOname().hashCode() );
         result = 37 * result + ( getType() == null ? 0 : this.getType().hashCode() );
         result = 37 * result + ( getGname() == null ? 0 : this.getGname().hashCode() );
         result = 37 * result + ( getFlavorId() == null ? 0 : this.getFlavorId().hashCode() );
         result = 37 * result + ( getGowner() == null ? 0 : this.getGowner().hashCode() );
         return result;
   }   


}


