package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.sql.Clob;
import java.util.Date;

/**
 * RepcatExceptions generated by hbm2java
 */
public class RepcatExceptions  implements java.io.Serializable {


     private BigDecimal exceptionId;
     private String userName;
     private Clob request;
     private BigDecimal job;
     private Date errorDate;
     private BigDecimal errorNumber;
     private String errorMessage;
     private BigDecimal lineNumber;

    

	
    
    
   
    public BigDecimal getExceptionId() {
        return this.exceptionId;
    }
    
    public void setExceptionId(BigDecimal exceptionId) {
        this.exceptionId = exceptionId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public Clob getRequest() {
        return this.request;
    }
    
    public void setRequest(Clob request) {
        this.request = request;
    }
    public BigDecimal getJob() {
        return this.job;
    }
    
    public void setJob(BigDecimal job) {
        this.job = job;
    }
    public Date getErrorDate() {
        return this.errorDate;
    }
    
    public void setErrorDate(Date errorDate) {
        this.errorDate = errorDate;
    }
    public BigDecimal getErrorNumber() {
        return this.errorNumber;
    }
    
    public void setErrorNumber(BigDecimal errorNumber) {
        this.errorNumber = errorNumber;
    }
    public String getErrorMessage() {
        return this.errorMessage;
    }
    
    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }
    public BigDecimal getLineNumber() {
        return this.lineNumber;
    }
    
    public void setLineNumber(BigDecimal lineNumber) {
        this.lineNumber = lineNumber;
    }




}


