package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.sql.Clob;

/**
 * RepcatInstantiationDdl generated by hbm2java
 */
public class RepcatInstantiationDdl  implements java.io.Serializable {


     private RepcatInstantiationDdlId id;
     private RepcatRefreshTemplates repcatRefreshTemplates;
     private Clob ddlText;

    

	
    
    
   
    public RepcatInstantiationDdlId getId() {
        return this.id;
    }
    
    public void setId(RepcatInstantiationDdlId id) {
        this.id = id;
    }
    public RepcatRefreshTemplates getRepcatRefreshTemplates() {
        return this.repcatRefreshTemplates;
    }
    
    public void setRepcatRefreshTemplates(RepcatRefreshTemplates repcatRefreshTemplates) {
        this.repcatRefreshTemplates = repcatRefreshTemplates;
    }
    public Clob getDdlText() {
        return this.ddlText;
    }
    
    public void setDdlText(Clob ddlText) {
        this.ddlText = ddlText;
    }




}


