package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * RepcatRepcat generated by hbm2java
 */
public class RepcatRepcat  implements java.io.Serializable {


     private RepcatRepcatId id;
     private String master;
     private BigDecimal status;
     private String schemaComment;
     private BigDecimal flavorId;
     private byte[] flag;
     private Set repcatSitesNews = new HashSet(0);
     private Set repcatFlavorObjectses = new HashSet(0);
     private Set repcatRepgroupPrivses = new HashSet(0);
     private Set repcatRepschemas = new HashSet(0);
     private Set repcatRepobjects = new HashSet(0);
     private Set repcatFlavorses = new HashSet(0);

    

	
    
    
   
    public RepcatRepcatId getId() {
        return this.id;
    }
    
    public void setId(RepcatRepcatId id) {
        this.id = id;
    }
    public String getMaster() {
        return this.master;
    }
    
    public void setMaster(String master) {
        this.master = master;
    }
    public BigDecimal getStatus() {
        return this.status;
    }
    
    public void setStatus(BigDecimal status) {
        this.status = status;
    }
    public String getSchemaComment() {
        return this.schemaComment;
    }
    
    public void setSchemaComment(String schemaComment) {
        this.schemaComment = schemaComment;
    }
    public BigDecimal getFlavorId() {
        return this.flavorId;
    }
    
    public void setFlavorId(BigDecimal flavorId) {
        this.flavorId = flavorId;
    }
    public byte[] getFlag() {
        return this.flag;
    }
    
    public void setFlag(byte[] flag) {
        this.flag = flag;
    }
    public Set getRepcatSitesNews() {
        return this.repcatSitesNews;
    }
    
    public void setRepcatSitesNews(Set repcatSitesNews) {
        this.repcatSitesNews = repcatSitesNews;
    }
    public Set getRepcatFlavorObjectses() {
        return this.repcatFlavorObjectses;
    }
    
    public void setRepcatFlavorObjectses(Set repcatFlavorObjectses) {
        this.repcatFlavorObjectses = repcatFlavorObjectses;
    }
    public Set getRepcatRepgroupPrivses() {
        return this.repcatRepgroupPrivses;
    }
    
    public void setRepcatRepgroupPrivses(Set repcatRepgroupPrivses) {
        this.repcatRepgroupPrivses = repcatRepgroupPrivses;
    }
    public Set getRepcatRepschemas() {
        return this.repcatRepschemas;
    }
    
    public void setRepcatRepschemas(Set repcatRepschemas) {
        this.repcatRepschemas = repcatRepschemas;
    }
    public Set getRepcatRepobjects() {
        return this.repcatRepobjects;
    }
    
    public void setRepcatRepobjects(Set repcatRepobjects) {
        this.repcatRepobjects = repcatRepobjects;
    }
    public Set getRepcatFlavorses() {
        return this.repcatFlavorses;
    }
    
    public void setRepcatFlavorses(Set repcatFlavorses) {
        this.repcatFlavorses = repcatFlavorses;
    }




}


