package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * RepcatTemplateRefgroups generated by hbm2java
 */
public class RepcatTemplateRefgroups  implements java.io.Serializable {


     private BigDecimal refreshGroupId;
     private RepcatRefreshTemplates repcatRefreshTemplates;
     private String refreshGroupName;
     private String rollbackSeg;
     private String startDate;
     private String interval;

    

	
    
    
   
    public BigDecimal getRefreshGroupId() {
        return this.refreshGroupId;
    }
    
    public void setRefreshGroupId(BigDecimal refreshGroupId) {
        this.refreshGroupId = refreshGroupId;
    }
    public RepcatRefreshTemplates getRepcatRefreshTemplates() {
        return this.repcatRefreshTemplates;
    }
    
    public void setRepcatRefreshTemplates(RepcatRefreshTemplates repcatRefreshTemplates) {
        this.repcatRefreshTemplates = repcatRefreshTemplates;
    }
    public String getRefreshGroupName() {
        return this.refreshGroupName;
    }
    
    public void setRefreshGroupName(String refreshGroupName) {
        this.refreshGroupName = refreshGroupName;
    }
    public String getRollbackSeg() {
        return this.rollbackSeg;
    }
    
    public void setRollbackSeg(String rollbackSeg) {
        this.rollbackSeg = rollbackSeg;
    }
    public String getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }
    public String getInterval() {
        return this.interval;
    }
    
    public void setInterval(String interval) {
        this.interval = interval;
    }




}


