package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;

/**
 * RepcatColumnGroup generated by hbm2java
 */
public class RepcatColumnGroup  implements java.io.Serializable {


     private RepcatColumnGroupId id;
     private String groupComment;
     private Set repcatGroupedColumns = new HashSet(0);

    

	
    
    
   
    public RepcatColumnGroupId getId() {
        return this.id;
    }
    
    public void setId(RepcatColumnGroupId id) {
        this.id = id;
    }
    public String getGroupComment() {
        return this.groupComment;
    }
    
    public void setGroupComment(String groupComment) {
        this.groupComment = groupComment;
    }
    public Set getRepcatGroupedColumns() {
        return this.repcatGroupedColumns;
    }
    
    public void setRepcatGroupedColumns(Set repcatGroupedColumns) {
        this.repcatGroupedColumns = repcatGroupedColumns;
    }




}


