package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * RepcatExtension generated by hbm2java
 */
public class RepcatExtension  implements java.io.Serializable {


     private byte[] extensionId;
     private BigDecimal extensionCode;
     private String masterdef;
     private String exportRequired;
     private BigDecimal repcatlogId;
     private BigDecimal extensionStatus;
     private BigDecimal flashbackScn;
     private String pushToMdef;
     private String pushToNew;
     private BigDecimal percentageForCatchupMdef;
     private BigDecimal cycleSecondsMdef;
     private BigDecimal percentageForCatchupNew;
     private BigDecimal cycleSecondsNew;
     private Set repcatSitesNews = new HashSet(0);

    

	
    
    
   
    public byte[] getExtensionId() {
        return this.extensionId;
    }
    
    public void setExtensionId(byte[] extensionId) {
        this.extensionId = extensionId;
    }
    public BigDecimal getExtensionCode() {
        return this.extensionCode;
    }
    
    public void setExtensionCode(BigDecimal extensionCode) {
        this.extensionCode = extensionCode;
    }
    public String getMasterdef() {
        return this.masterdef;
    }
    
    public void setMasterdef(String masterdef) {
        this.masterdef = masterdef;
    }
    public String getExportRequired() {
        return this.exportRequired;
    }
    
    public void setExportRequired(String exportRequired) {
        this.exportRequired = exportRequired;
    }
    public BigDecimal getRepcatlogId() {
        return this.repcatlogId;
    }
    
    public void setRepcatlogId(BigDecimal repcatlogId) {
        this.repcatlogId = repcatlogId;
    }
    public BigDecimal getExtensionStatus() {
        return this.extensionStatus;
    }
    
    public void setExtensionStatus(BigDecimal extensionStatus) {
        this.extensionStatus = extensionStatus;
    }
    public BigDecimal getFlashbackScn() {
        return this.flashbackScn;
    }
    
    public void setFlashbackScn(BigDecimal flashbackScn) {
        this.flashbackScn = flashbackScn;
    }
    public String getPushToMdef() {
        return this.pushToMdef;
    }
    
    public void setPushToMdef(String pushToMdef) {
        this.pushToMdef = pushToMdef;
    }
    public String getPushToNew() {
        return this.pushToNew;
    }
    
    public void setPushToNew(String pushToNew) {
        this.pushToNew = pushToNew;
    }
    public BigDecimal getPercentageForCatchupMdef() {
        return this.percentageForCatchupMdef;
    }
    
    public void setPercentageForCatchupMdef(BigDecimal percentageForCatchupMdef) {
        this.percentageForCatchupMdef = percentageForCatchupMdef;
    }
    public BigDecimal getCycleSecondsMdef() {
        return this.cycleSecondsMdef;
    }
    
    public void setCycleSecondsMdef(BigDecimal cycleSecondsMdef) {
        this.cycleSecondsMdef = cycleSecondsMdef;
    }
    public BigDecimal getPercentageForCatchupNew() {
        return this.percentageForCatchupNew;
    }
    
    public void setPercentageForCatchupNew(BigDecimal percentageForCatchupNew) {
        this.percentageForCatchupNew = percentageForCatchupNew;
    }
    public BigDecimal getCycleSecondsNew() {
        return this.cycleSecondsNew;
    }
    
    public void setCycleSecondsNew(BigDecimal cycleSecondsNew) {
        this.cycleSecondsNew = cycleSecondsNew;
    }
    public Set getRepcatSitesNews() {
        return this.repcatSitesNews;
    }
    
    public void setRepcatSitesNews(Set repcatSitesNews) {
        this.repcatSitesNews = repcatSitesNews;
    }




}


