package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * RepcatRefreshTemplates generated by hbm2java
 */
public class RepcatRefreshTemplates  implements java.io.Serializable {


     private BigDecimal refreshTemplateId;
     private RepcatTemplateTypes repcatTemplateTypes;
     private RepcatTemplateStatus repcatTemplateStatus;
     private String owner;
     private String refreshGroupName;
     private String refreshTemplateName;
     private String templateComment;
     private String publicTemplate;
     private Date lastModified;
     private BigDecimal modifiedBy;
     private Date creationDate;
     private BigDecimal createdBy;
     private BigDecimal refreshGroupId;
     private byte[] flags;
     private String spare1;
     private Set repcatInstantiationDdls = new HashSet(0);
     private Set repcatTemplateRefgroupses = new HashSet(0);
     private Set repcatTemplateParmses = new HashSet(0);
     private Set repcatUserAuthorizationses = new HashSet(0);
     private Set repcatTemplateObjectses = new HashSet(0);

    

	
    
    
   
    public BigDecimal getRefreshTemplateId() {
        return this.refreshTemplateId;
    }
    
    public void setRefreshTemplateId(BigDecimal refreshTemplateId) {
        this.refreshTemplateId = refreshTemplateId;
    }
    public RepcatTemplateTypes getRepcatTemplateTypes() {
        return this.repcatTemplateTypes;
    }
    
    public void setRepcatTemplateTypes(RepcatTemplateTypes repcatTemplateTypes) {
        this.repcatTemplateTypes = repcatTemplateTypes;
    }
    public RepcatTemplateStatus getRepcatTemplateStatus() {
        return this.repcatTemplateStatus;
    }
    
    public void setRepcatTemplateStatus(RepcatTemplateStatus repcatTemplateStatus) {
        this.repcatTemplateStatus = repcatTemplateStatus;
    }
    public String getOwner() {
        return this.owner;
    }
    
    public void setOwner(String owner) {
        this.owner = owner;
    }
    public String getRefreshGroupName() {
        return this.refreshGroupName;
    }
    
    public void setRefreshGroupName(String refreshGroupName) {
        this.refreshGroupName = refreshGroupName;
    }
    public String getRefreshTemplateName() {
        return this.refreshTemplateName;
    }
    
    public void setRefreshTemplateName(String refreshTemplateName) {
        this.refreshTemplateName = refreshTemplateName;
    }
    public String getTemplateComment() {
        return this.templateComment;
    }
    
    public void setTemplateComment(String templateComment) {
        this.templateComment = templateComment;
    }
    public String getPublicTemplate() {
        return this.publicTemplate;
    }
    
    public void setPublicTemplate(String publicTemplate) {
        this.publicTemplate = publicTemplate;
    }
    public Date getLastModified() {
        return this.lastModified;
    }
    
    public void setLastModified(Date lastModified) {
        this.lastModified = lastModified;
    }
    public BigDecimal getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(BigDecimal modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public BigDecimal getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(BigDecimal createdBy) {
        this.createdBy = createdBy;
    }
    public BigDecimal getRefreshGroupId() {
        return this.refreshGroupId;
    }
    
    public void setRefreshGroupId(BigDecimal refreshGroupId) {
        this.refreshGroupId = refreshGroupId;
    }
    public byte[] getFlags() {
        return this.flags;
    }
    
    public void setFlags(byte[] flags) {
        this.flags = flags;
    }
    public String getSpare1() {
        return this.spare1;
    }
    
    public void setSpare1(String spare1) {
        this.spare1 = spare1;
    }
    public Set getRepcatInstantiationDdls() {
        return this.repcatInstantiationDdls;
    }
    
    public void setRepcatInstantiationDdls(Set repcatInstantiationDdls) {
        this.repcatInstantiationDdls = repcatInstantiationDdls;
    }
    public Set getRepcatTemplateRefgroupses() {
        return this.repcatTemplateRefgroupses;
    }
    
    public void setRepcatTemplateRefgroupses(Set repcatTemplateRefgroupses) {
        this.repcatTemplateRefgroupses = repcatTemplateRefgroupses;
    }
    public Set getRepcatTemplateParmses() {
        return this.repcatTemplateParmses;
    }
    
    public void setRepcatTemplateParmses(Set repcatTemplateParmses) {
        this.repcatTemplateParmses = repcatTemplateParmses;
    }
    public Set getRepcatUserAuthorizationses() {
        return this.repcatUserAuthorizationses;
    }
    
    public void setRepcatUserAuthorizationses(Set repcatUserAuthorizationses) {
        this.repcatUserAuthorizationses = repcatUserAuthorizationses;
    }
    public Set getRepcatTemplateObjectses() {
        return this.repcatTemplateObjectses;
    }
    
    public void setRepcatTemplateObjectses(Set repcatTemplateObjectses) {
        this.repcatTemplateObjectses = repcatTemplateObjectses;
    }




}


