package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA



/**
 * RepcatSiteObjects generated by hbm2java
 */
public class RepcatSiteObjects  implements java.io.Serializable {


     private RepcatSiteObjectsId id;
     private RepcatTemplateSites repcatTemplateSites;
     private RepcatObjectTypes repcatObjectTypes;

    

    
   
    public RepcatSiteObjectsId getId() {
        return this.id;
    }
    
    public void setId(RepcatSiteObjectsId id) {
        this.id = id;
    }
    public RepcatTemplateSites getRepcatTemplateSites() {
        return this.repcatTemplateSites;
    }
    
    public void setRepcatTemplateSites(RepcatTemplateSites repcatTemplateSites) {
        this.repcatTemplateSites = repcatTemplateSites;
    }
    public RepcatObjectTypes getRepcatObjectTypes() {
        return this.repcatObjectTypes;
    }
    
    public void setRepcatObjectTypes(RepcatObjectTypes repcatObjectTypes) {
        this.repcatObjectTypes = repcatObjectTypes;
    }




}


