package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA



/**
 * RepcatSnapgroup generated by hbm2java
 */
public class RepcatSnapgroup  implements java.io.Serializable {


     private RepcatSnapgroupId id;

    

    
   
    public RepcatSnapgroupId getId() {
        return this.id;
    }
    
    public void setId(RepcatSnapgroupId id) {
        this.id = id;
    }




}


