package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * RepcatPriorityId generated by hbm2java
 */
public class RepcatPriorityId  implements java.io.Serializable {


     private String sname;
     private String priorityGroup;
     private BigDecimal priority;

    

    
   
    public String getSname() {
        return this.sname;
    }
    
    public void setSname(String sname) {
        this.sname = sname;
    }
    public String getPriorityGroup() {
        return this.priorityGroup;
    }
    
    public void setPriorityGroup(String priorityGroup) {
        this.priorityGroup = priorityGroup;
    }
    public BigDecimal getPriority() {
        return this.priority;
    }
    
    public void setPriority(BigDecimal priority) {
        this.priority = priority;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RepcatPriorityId) ) return false;
		 RepcatPriorityId castOther = ( RepcatPriorityId ) other; 
         
		 return ( (this.getSname()==castOther.getSname()) || ( this.getSname()!=null && castOther.getSname()!=null && this.getSname().equals(castOther.getSname()) ) )
 && ( (this.getPriorityGroup()==castOther.getPriorityGroup()) || ( this.getPriorityGroup()!=null && castOther.getPriorityGroup()!=null && this.getPriorityGroup().equals(castOther.getPriorityGroup()) ) )
 && ( (this.getPriority()==castOther.getPriority()) || ( this.getPriority()!=null && castOther.getPriority()!=null && this.getPriority().equals(castOther.getPriority()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSname() == null ? 0 : this.getSname().hashCode() );
         result = 37 * result + ( getPriorityGroup() == null ? 0 : this.getPriorityGroup().hashCode() );
         result = 37 * result + ( getPriority() == null ? 0 : this.getPriority().hashCode() );
         return result;
   }   


}


