package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * RepcatTemplateTargets generated by hbm2java
 */
public class RepcatTemplateTargets  implements java.io.Serializable {


     private BigDecimal templateTargetId;
     private String targetDatabase;
     private String targetComment;
     private String connectString;
     private String spare1;

    

	
    
    
   
    public BigDecimal getTemplateTargetId() {
        return this.templateTargetId;
    }
    
    public void setTemplateTargetId(BigDecimal templateTargetId) {
        this.templateTargetId = templateTargetId;
    }
    public String getTargetDatabase() {
        return this.targetDatabase;
    }
    
    public void setTargetDatabase(String targetDatabase) {
        this.targetDatabase = targetDatabase;
    }
    public String getTargetComment() {
        return this.targetComment;
    }
    
    public void setTargetComment(String targetComment) {
        this.targetComment = targetComment;
    }
    public String getConnectString() {
        return this.connectString;
    }
    
    public void setConnectString(String connectString) {
        this.connectString = connectString;
    }
    public String getSpare1() {
        return this.spare1;
    }
    
    public void setSpare1(String spare1) {
        this.spare1 = spare1;
    }




}


