package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * RepcatPriorityGroup generated by hbm2java
 */
public class RepcatPriorityGroup  implements java.io.Serializable {


     private RepcatPriorityGroupId id;
     private BigDecimal dataTypeId;
     private BigDecimal fixedDataLength;
     private String priorityComment;
     private Set repcatPriorities = new HashSet(0);

    

	
    
    
   
    public RepcatPriorityGroupId getId() {
        return this.id;
    }
    
    public void setId(RepcatPriorityGroupId id) {
        this.id = id;
    }
    public BigDecimal getDataTypeId() {
        return this.dataTypeId;
    }
    
    public void setDataTypeId(BigDecimal dataTypeId) {
        this.dataTypeId = dataTypeId;
    }
    public BigDecimal getFixedDataLength() {
        return this.fixedDataLength;
    }
    
    public void setFixedDataLength(BigDecimal fixedDataLength) {
        this.fixedDataLength = fixedDataLength;
    }
    public String getPriorityComment() {
        return this.priorityComment;
    }
    
    public void setPriorityComment(String priorityComment) {
        this.priorityComment = priorityComment;
    }
    public Set getRepcatPriorities() {
        return this.repcatPriorities;
    }
    
    public void setRepcatPriorities(Set repcatPriorities) {
        this.repcatPriorities = repcatPriorities;
    }




}


