package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA



/**
 * RepcatKeyColumns generated by hbm2java
 */
public class RepcatKeyColumns  implements java.io.Serializable {


     private RepcatKeyColumnsId id;
     private RepcatRepobject repcatRepobject;

    

    
   
    public RepcatKeyColumnsId getId() {
        return this.id;
    }
    
    public void setId(RepcatKeyColumnsId id) {
        this.id = id;
    }
    public RepcatRepobject getRepcatRepobject() {
        return this.repcatRepobject;
    }
    
    public void setRepcatRepobject(RepcatRepobject repcatRepobject) {
        this.repcatRepobject = repcatRepobject;
    }




}


