package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;

/**
 * RepcatResolutionMethod generated by hbm2java
 */
public class RepcatResolutionMethod  implements java.io.Serializable {


     private RepcatResolutionMethodId id;
     private Set repcatResolutions = new HashSet(0);

    

	
    
    
   
    public RepcatResolutionMethodId getId() {
        return this.id;
    }
    
    public void setId(RepcatResolutionMethodId id) {
        this.id = id;
    }
    public Set getRepcatResolutions() {
        return this.repcatResolutions;
    }
    
    public void setRepcatResolutions(Set repcatResolutions) {
        this.repcatResolutions = repcatResolutions;
    }




}


