package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * RepcatSitesNew generated by hbm2java
 */
public class RepcatSitesNew  implements java.io.Serializable {


     private RepcatSitesNewId id;
     private RepcatExtension repcatExtension;
     private RepcatRepcat repcatRepcat;
     private String fullInstantiation;
     private BigDecimal masterStatus;

    

	
    
    
   
    public RepcatSitesNewId getId() {
        return this.id;
    }
    
    public void setId(RepcatSitesNewId id) {
        this.id = id;
    }
    public RepcatExtension getRepcatExtension() {
        return this.repcatExtension;
    }
    
    public void setRepcatExtension(RepcatExtension repcatExtension) {
        this.repcatExtension = repcatExtension;
    }
    public RepcatRepcat getRepcatRepcat() {
        return this.repcatRepcat;
    }
    
    public void setRepcatRepcat(RepcatRepcat repcatRepcat) {
        this.repcatRepcat = repcatRepcat;
    }
    public String getFullInstantiation() {
        return this.fullInstantiation;
    }
    
    public void setFullInstantiation(String fullInstantiation) {
        this.fullInstantiation = fullInstantiation;
    }
    public BigDecimal getMasterStatus() {
        return this.masterStatus;
    }
    
    public void setMasterStatus(BigDecimal masterStatus) {
        this.masterStatus = masterStatus;
    }




}


