package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA



/**
 * RepcatPriorityGroupId generated by hbm2java
 */
public class RepcatPriorityGroupId  implements java.io.Serializable {


     private String priorityGroup;
     private String sname;

    

    
   
    public String getPriorityGroup() {
        return this.priorityGroup;
    }
    
    public void setPriorityGroup(String priorityGroup) {
        this.priorityGroup = priorityGroup;
    }
    public String getSname() {
        return this.sname;
    }
    
    public void setSname(String sname) {
        this.sname = sname;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RepcatPriorityGroupId) ) return false;
		 RepcatPriorityGroupId castOther = ( RepcatPriorityGroupId ) other; 
         
		 return ( (this.getPriorityGroup()==castOther.getPriorityGroup()) || ( this.getPriorityGroup()!=null && castOther.getPriorityGroup()!=null && this.getPriorityGroup().equals(castOther.getPriorityGroup()) ) )
 && ( (this.getSname()==castOther.getSname()) || ( this.getSname()!=null && castOther.getSname()!=null && this.getSname().equals(castOther.getSname()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPriorityGroup() == null ? 0 : this.getPriorityGroup().hashCode() );
         result = 37 * result + ( getSname() == null ? 0 : this.getSname().hashCode() );
         return result;
   }   


}


