package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * RepcatRepschema generated by hbm2java
 */
public class RepcatRepschema  implements java.io.Serializable {


     private RepcatRepschemaId id;
     private DefDestination defDestination;
     private RepcatRepcat repcatRepcat;
     private String masterdef;
     private String snapmaster;
     private String masterComment;
     private String master;
     private BigDecimal propUpdates;
     private String myDblink;

    

	
    
    
   
    public RepcatRepschemaId getId() {
        return this.id;
    }
    
    public void setId(RepcatRepschemaId id) {
        this.id = id;
    }
    public DefDestination getDefDestination() {
        return this.defDestination;
    }
    
    public void setDefDestination(DefDestination defDestination) {
        this.defDestination = defDestination;
    }
    public RepcatRepcat getRepcatRepcat() {
        return this.repcatRepcat;
    }
    
    public void setRepcatRepcat(RepcatRepcat repcatRepcat) {
        this.repcatRepcat = repcatRepcat;
    }
    public String getMasterdef() {
        return this.masterdef;
    }
    
    public void setMasterdef(String masterdef) {
        this.masterdef = masterdef;
    }
    public String getSnapmaster() {
        return this.snapmaster;
    }
    
    public void setSnapmaster(String snapmaster) {
        this.snapmaster = snapmaster;
    }
    public String getMasterComment() {
        return this.masterComment;
    }
    
    public void setMasterComment(String masterComment) {
        this.masterComment = masterComment;
    }
    public String getMaster() {
        return this.master;
    }
    
    public void setMaster(String master) {
        this.master = master;
    }
    public BigDecimal getPropUpdates() {
        return this.propUpdates;
    }
    
    public void setPropUpdates(BigDecimal propUpdates) {
        this.propUpdates = propUpdates;
    }
    public String getMyDblink() {
        return this.myDblink;
    }
    
    public void setMyDblink(String myDblink) {
        this.myDblink = myDblink;
    }




}


