package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * RepcatResolutionStatisticsId generated by hbm2java
 */
public class RepcatResolutionStatisticsId  implements java.io.Serializable {


     private String sname;
     private String oname;
     private BigDecimal conflictTypeId;
     private String referenceName;
     private String methodName;
     private String functionName;
     private String priorityGroup;
     private Date resolvedDate;
     private String primaryKeyValue;

    

	
    
    
   
    public String getSname() {
        return this.sname;
    }
    
    public void setSname(String sname) {
        this.sname = sname;
    }
    public String getOname() {
        return this.oname;
    }
    
    public void setOname(String oname) {
        this.oname = oname;
    }
    public BigDecimal getConflictTypeId() {
        return this.conflictTypeId;
    }
    
    public void setConflictTypeId(BigDecimal conflictTypeId) {
        this.conflictTypeId = conflictTypeId;
    }
    public String getReferenceName() {
        return this.referenceName;
    }
    
    public void setReferenceName(String referenceName) {
        this.referenceName = referenceName;
    }
    public String getMethodName() {
        return this.methodName;
    }
    
    public void setMethodName(String methodName) {
        this.methodName = methodName;
    }
    public String getFunctionName() {
        return this.functionName;
    }
    
    public void setFunctionName(String functionName) {
        this.functionName = functionName;
    }
    public String getPriorityGroup() {
        return this.priorityGroup;
    }
    
    public void setPriorityGroup(String priorityGroup) {
        this.priorityGroup = priorityGroup;
    }
    public Date getResolvedDate() {
        return this.resolvedDate;
    }
    
    public void setResolvedDate(Date resolvedDate) {
        this.resolvedDate = resolvedDate;
    }
    public String getPrimaryKeyValue() {
        return this.primaryKeyValue;
    }
    
    public void setPrimaryKeyValue(String primaryKeyValue) {
        this.primaryKeyValue = primaryKeyValue;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RepcatResolutionStatisticsId) ) return false;
		 RepcatResolutionStatisticsId castOther = ( RepcatResolutionStatisticsId ) other; 
         
		 return ( (this.getSname()==castOther.getSname()) || ( this.getSname()!=null && castOther.getSname()!=null && this.getSname().equals(castOther.getSname()) ) )
 && ( (this.getOname()==castOther.getOname()) || ( this.getOname()!=null && castOther.getOname()!=null && this.getOname().equals(castOther.getOname()) ) )
 && ( (this.getConflictTypeId()==castOther.getConflictTypeId()) || ( this.getConflictTypeId()!=null && castOther.getConflictTypeId()!=null && this.getConflictTypeId().equals(castOther.getConflictTypeId()) ) )
 && ( (this.getReferenceName()==castOther.getReferenceName()) || ( this.getReferenceName()!=null && castOther.getReferenceName()!=null && this.getReferenceName().equals(castOther.getReferenceName()) ) )
 && ( (this.getMethodName()==castOther.getMethodName()) || ( this.getMethodName()!=null && castOther.getMethodName()!=null && this.getMethodName().equals(castOther.getMethodName()) ) )
 && ( (this.getFunctionName()==castOther.getFunctionName()) || ( this.getFunctionName()!=null && castOther.getFunctionName()!=null && this.getFunctionName().equals(castOther.getFunctionName()) ) )
 && ( (this.getPriorityGroup()==castOther.getPriorityGroup()) || ( this.getPriorityGroup()!=null && castOther.getPriorityGroup()!=null && this.getPriorityGroup().equals(castOther.getPriorityGroup()) ) )
 && ( (this.getResolvedDate()==castOther.getResolvedDate()) || ( this.getResolvedDate()!=null && castOther.getResolvedDate()!=null && this.getResolvedDate().equals(castOther.getResolvedDate()) ) )
 && ( (this.getPrimaryKeyValue()==castOther.getPrimaryKeyValue()) || ( this.getPrimaryKeyValue()!=null && castOther.getPrimaryKeyValue()!=null && this.getPrimaryKeyValue().equals(castOther.getPrimaryKeyValue()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSname() == null ? 0 : this.getSname().hashCode() );
         result = 37 * result + ( getOname() == null ? 0 : this.getOname().hashCode() );
         result = 37 * result + ( getConflictTypeId() == null ? 0 : this.getConflictTypeId().hashCode() );
         result = 37 * result + ( getReferenceName() == null ? 0 : this.getReferenceName().hashCode() );
         result = 37 * result + ( getMethodName() == null ? 0 : this.getMethodName().hashCode() );
         result = 37 * result + ( getFunctionName() == null ? 0 : this.getFunctionName().hashCode() );
         result = 37 * result + ( getPriorityGroup() == null ? 0 : this.getPriorityGroup().hashCode() );
         result = 37 * result + ( getResolvedDate() == null ? 0 : this.getResolvedDate().hashCode() );
         result = 37 * result + ( getPrimaryKeyValue() == null ? 0 : this.getPrimaryKeyValue().hashCode() );
         return result;
   }   


}


