package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA



/**
 * RepcatKeyColumnsId generated by hbm2java
 */
public class RepcatKeyColumnsId  implements java.io.Serializable {


     private String sname;
     private String oname;
     private String col;

    

    
   
    public String getSname() {
        return this.sname;
    }
    
    public void setSname(String sname) {
        this.sname = sname;
    }
    public String getOname() {
        return this.oname;
    }
    
    public void setOname(String oname) {
        this.oname = oname;
    }
    public String getCol() {
        return this.col;
    }
    
    public void setCol(String col) {
        this.col = col;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RepcatKeyColumnsId) ) return false;
		 RepcatKeyColumnsId castOther = ( RepcatKeyColumnsId ) other; 
         
		 return ( (this.getSname()==castOther.getSname()) || ( this.getSname()!=null && castOther.getSname()!=null && this.getSname().equals(castOther.getSname()) ) )
 && ( (this.getOname()==castOther.getOname()) || ( this.getOname()!=null && castOther.getOname()!=null && this.getOname().equals(castOther.getOname()) ) )
 && ( (this.getCol()==castOther.getCol()) || ( this.getCol()!=null && castOther.getCol()!=null && this.getCol().equals(castOther.getCol()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSname() == null ? 0 : this.getSname().hashCode() );
         result = 37 * result + ( getOname() == null ? 0 : this.getOname().hashCode() );
         result = 37 * result + ( getCol() == null ? 0 : this.getCol().hashCode() );
         return result;
   }   


}


