package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA



/**
 * RepcatAuditColumn generated by hbm2java
 */
public class RepcatAuditColumn  implements java.io.Serializable {


     private RepcatAuditColumnId id;
     private RepcatAuditAttribute repcatAuditAttribute;
     private RepcatConflict repcatConflict;

    

    
   
    public RepcatAuditColumnId getId() {
        return this.id;
    }
    
    public void setId(RepcatAuditColumnId id) {
        this.id = id;
    }
    public RepcatAuditAttribute getRepcatAuditAttribute() {
        return this.repcatAuditAttribute;
    }
    
    public void setRepcatAuditAttribute(RepcatAuditAttribute repcatAuditAttribute) {
        this.repcatAuditAttribute = repcatAuditAttribute;
    }
    public RepcatConflict getRepcatConflict() {
        return this.repcatConflict;
    }
    
    public void setRepcatConflict(RepcatConflict repcatConflict) {
        this.repcatConflict = repcatConflict;
    }




}


