package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA



/**
 * RepcatDdl generated by hbm2java
 */
public class RepcatDdl  implements java.io.Serializable {


     private RepcatDdlId id;
     private RepcatRepcatlog repcatRepcatlog;

    

	
    
    
   
    public RepcatDdlId getId() {
        return this.id;
    }
    
    public void setId(RepcatDdlId id) {
        this.id = id;
    }
    public RepcatRepcatlog getRepcatRepcatlog() {
        return this.repcatRepcatlog;
    }
    
    public void setRepcatRepcatlog(RepcatRepcatlog repcatRepcatlog) {
        this.repcatRepcatlog = repcatRepcatlog;
    }




}


