package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * RepcatGroupedColumnId generated by hbm2java
 */
public class RepcatGroupedColumnId  implements java.io.Serializable {


     private String sname;
     private String oname;
     private String groupName;
     private String columnName;
     private BigDecimal pos;

    

    
   
    public String getSname() {
        return this.sname;
    }
    
    public void setSname(String sname) {
        this.sname = sname;
    }
    public String getOname() {
        return this.oname;
    }
    
    public void setOname(String oname) {
        this.oname = oname;
    }
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }
    public String getColumnName() {
        return this.columnName;
    }
    
    public void setColumnName(String columnName) {
        this.columnName = columnName;
    }
    public BigDecimal getPos() {
        return this.pos;
    }
    
    public void setPos(BigDecimal pos) {
        this.pos = pos;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RepcatGroupedColumnId) ) return false;
		 RepcatGroupedColumnId castOther = ( RepcatGroupedColumnId ) other; 
         
		 return ( (this.getSname()==castOther.getSname()) || ( this.getSname()!=null && castOther.getSname()!=null && this.getSname().equals(castOther.getSname()) ) )
 && ( (this.getOname()==castOther.getOname()) || ( this.getOname()!=null && castOther.getOname()!=null && this.getOname().equals(castOther.getOname()) ) )
 && ( (this.getGroupName()==castOther.getGroupName()) || ( this.getGroupName()!=null && castOther.getGroupName()!=null && this.getGroupName().equals(castOther.getGroupName()) ) )
 && ( (this.getColumnName()==castOther.getColumnName()) || ( this.getColumnName()!=null && castOther.getColumnName()!=null && this.getColumnName().equals(castOther.getColumnName()) ) )
 && ( (this.getPos()==castOther.getPos()) || ( this.getPos()!=null && castOther.getPos()!=null && this.getPos().equals(castOther.getPos()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSname() == null ? 0 : this.getSname().hashCode() );
         result = 37 * result + ( getOname() == null ? 0 : this.getOname().hashCode() );
         result = 37 * result + ( getGroupName() == null ? 0 : this.getGroupName().hashCode() );
         result = 37 * result + ( getColumnName() == null ? 0 : this.getColumnName().hashCode() );
         result = 37 * result + ( getPos() == null ? 0 : this.getPos().hashCode() );
         return result;
   }   


}


