package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * RepcatInstantiationDdlId generated by hbm2java
 */
public class RepcatInstantiationDdlId  implements java.io.Serializable {


     private BigDecimal refreshTemplateId;
     private BigDecimal phase;
     private BigDecimal ddlNum;

    

    
   
    public BigDecimal getRefreshTemplateId() {
        return this.refreshTemplateId;
    }
    
    public void setRefreshTemplateId(BigDecimal refreshTemplateId) {
        this.refreshTemplateId = refreshTemplateId;
    }
    public BigDecimal getPhase() {
        return this.phase;
    }
    
    public void setPhase(BigDecimal phase) {
        this.phase = phase;
    }
    public BigDecimal getDdlNum() {
        return this.ddlNum;
    }
    
    public void setDdlNum(BigDecimal ddlNum) {
        this.ddlNum = ddlNum;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RepcatInstantiationDdlId) ) return false;
		 RepcatInstantiationDdlId castOther = ( RepcatInstantiationDdlId ) other; 
         
		 return ( (this.getRefreshTemplateId()==castOther.getRefreshTemplateId()) || ( this.getRefreshTemplateId()!=null && castOther.getRefreshTemplateId()!=null && this.getRefreshTemplateId().equals(castOther.getRefreshTemplateId()) ) )
 && ( (this.getPhase()==castOther.getPhase()) || ( this.getPhase()!=null && castOther.getPhase()!=null && this.getPhase().equals(castOther.getPhase()) ) )
 && ( (this.getDdlNum()==castOther.getDdlNum()) || ( this.getDdlNum()!=null && castOther.getDdlNum()!=null && this.getDdlNum().equals(castOther.getDdlNum()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRefreshTemplateId() == null ? 0 : this.getRefreshTemplateId().hashCode() );
         result = 37 * result + ( getPhase() == null ? 0 : this.getPhase().hashCode() );
         result = 37 * result + ( getDdlNum() == null ? 0 : this.getDdlNum().hashCode() );
         return result;
   }   


}


