package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * RepcatRepprop generated by hbm2java
 */
public class RepcatRepprop  implements java.io.Serializable {


     private RepcatReppropId id;
     private RepcatRepobject repcatRepobject;
     private BigDecimal how;
     private String propagateComment;
     private BigDecimal deliveryOrder;
     private BigDecimal recipientKey;
     private byte[] extensionId;

    

	
    
    
   
    public RepcatReppropId getId() {
        return this.id;
    }
    
    public void setId(RepcatReppropId id) {
        this.id = id;
    }
    public RepcatRepobject getRepcatRepobject() {
        return this.repcatRepobject;
    }
    
    public void setRepcatRepobject(RepcatRepobject repcatRepobject) {
        this.repcatRepobject = repcatRepobject;
    }
    public BigDecimal getHow() {
        return this.how;
    }
    
    public void setHow(BigDecimal how) {
        this.how = how;
    }
    public String getPropagateComment() {
        return this.propagateComment;
    }
    
    public void setPropagateComment(String propagateComment) {
        this.propagateComment = propagateComment;
    }
    public BigDecimal getDeliveryOrder() {
        return this.deliveryOrder;
    }
    
    public void setDeliveryOrder(BigDecimal deliveryOrder) {
        this.deliveryOrder = deliveryOrder;
    }
    public BigDecimal getRecipientKey() {
        return this.recipientKey;
    }
    
    public void setRecipientKey(BigDecimal recipientKey) {
        this.recipientKey = recipientKey;
    }
    public byte[] getExtensionId() {
        return this.extensionId;
    }
    
    public void setExtensionId(byte[] extensionId) {
        this.extensionId = extensionId;
    }




}


