package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * RepcatObjectParmsId generated by hbm2java
 */
public class RepcatObjectParmsId  implements java.io.Serializable {


     private BigDecimal templateParameterId;
     private BigDecimal templateObjectId;

    

    
   
    public BigDecimal getTemplateParameterId() {
        return this.templateParameterId;
    }
    
    public void setTemplateParameterId(BigDecimal templateParameterId) {
        this.templateParameterId = templateParameterId;
    }
    public BigDecimal getTemplateObjectId() {
        return this.templateObjectId;
    }
    
    public void setTemplateObjectId(BigDecimal templateObjectId) {
        this.templateObjectId = templateObjectId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RepcatObjectParmsId) ) return false;
		 RepcatObjectParmsId castOther = ( RepcatObjectParmsId ) other; 
         
		 return ( (this.getTemplateParameterId()==castOther.getTemplateParameterId()) || ( this.getTemplateParameterId()!=null && castOther.getTemplateParameterId()!=null && this.getTemplateParameterId().equals(castOther.getTemplateParameterId()) ) )
 && ( (this.getTemplateObjectId()==castOther.getTemplateObjectId()) || ( this.getTemplateObjectId()!=null && castOther.getTemplateObjectId()!=null && this.getTemplateObjectId().equals(castOther.getTemplateObjectId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTemplateParameterId() == null ? 0 : this.getTemplateParameterId().hashCode() );
         result = 37 * result + ( getTemplateObjectId() == null ? 0 : this.getTemplateObjectId().hashCode() );
         return result;
   }   


}


