package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * RepcatTemplateTypes generated by hbm2java
 */
public class RepcatTemplateTypes  implements java.io.Serializable {


     private BigDecimal templateTypeId;
     private String templateDescription;
     private byte[] flags;
     private String spare1;
     private Set repcatRefreshTemplateses = new HashSet(0);

    

	
    
    
   
    public BigDecimal getTemplateTypeId() {
        return this.templateTypeId;
    }
    
    public void setTemplateTypeId(BigDecimal templateTypeId) {
        this.templateTypeId = templateTypeId;
    }
    public String getTemplateDescription() {
        return this.templateDescription;
    }
    
    public void setTemplateDescription(String templateDescription) {
        this.templateDescription = templateDescription;
    }
    public byte[] getFlags() {
        return this.flags;
    }
    
    public void setFlags(byte[] flags) {
        this.flags = flags;
    }
    public String getSpare1() {
        return this.spare1;
    }
    
    public void setSpare1(String spare1) {
        this.spare1 = spare1;
    }
    public Set getRepcatRefreshTemplateses() {
        return this.repcatRefreshTemplateses;
    }
    
    public void setRepcatRefreshTemplateses(Set repcatRefreshTemplateses) {
        this.repcatRefreshTemplateses = repcatRefreshTemplateses;
    }




}


