package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * RepcatRepcatlog generated by hbm2java
 */
public class RepcatRepcatlog  implements java.io.Serializable {


     private RepcatRepcatlogId id;
     private BigDecimal version;
     private String userid;
     private Date timestamp;
     private String sname;
     private BigDecimal request;
     private String oname;
     private BigDecimal type;
     private String AComment;
     private String boolArg;
     private String anoBoolArg;
     private BigDecimal intArg;
     private BigDecimal anoIntArg;
     private BigDecimal lines;
     private BigDecimal status;
     private String message;
     private BigDecimal errnum;
     private String gname;
     private Set repcatDdls = new HashSet(0);

    

	
    
    
   
    public RepcatRepcatlogId getId() {
        return this.id;
    }
    
    public void setId(RepcatRepcatlogId id) {
        this.id = id;
    }
    public BigDecimal getVersion() {
        return this.version;
    }
    
    public void setVersion(BigDecimal version) {
        this.version = version;
    }
    public String getUserid() {
        return this.userid;
    }
    
    public void setUserid(String userid) {
        this.userid = userid;
    }
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    public String getSname() {
        return this.sname;
    }
    
    public void setSname(String sname) {
        this.sname = sname;
    }
    public BigDecimal getRequest() {
        return this.request;
    }
    
    public void setRequest(BigDecimal request) {
        this.request = request;
    }
    public String getOname() {
        return this.oname;
    }
    
    public void setOname(String oname) {
        this.oname = oname;
    }
    public BigDecimal getType() {
        return this.type;
    }
    
    public void setType(BigDecimal type) {
        this.type = type;
    }
    public String getAComment() {
        return this.AComment;
    }
    
    public void setAComment(String AComment) {
        this.AComment = AComment;
    }
    public String getBoolArg() {
        return this.boolArg;
    }
    
    public void setBoolArg(String boolArg) {
        this.boolArg = boolArg;
    }
    public String getAnoBoolArg() {
        return this.anoBoolArg;
    }
    
    public void setAnoBoolArg(String anoBoolArg) {
        this.anoBoolArg = anoBoolArg;
    }
    public BigDecimal getIntArg() {
        return this.intArg;
    }
    
    public void setIntArg(BigDecimal intArg) {
        this.intArg = intArg;
    }
    public BigDecimal getAnoIntArg() {
        return this.anoIntArg;
    }
    
    public void setAnoIntArg(BigDecimal anoIntArg) {
        this.anoIntArg = anoIntArg;
    }
    public BigDecimal getLines() {
        return this.lines;
    }
    
    public void setLines(BigDecimal lines) {
        this.lines = lines;
    }
    public BigDecimal getStatus() {
        return this.status;
    }
    
    public void setStatus(BigDecimal status) {
        this.status = status;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public BigDecimal getErrnum() {
        return this.errnum;
    }
    
    public void setErrnum(BigDecimal errnum) {
        this.errnum = errnum;
    }
    public String getGname() {
        return this.gname;
    }
    
    public void setGname(String gname) {
        this.gname = gname;
    }
    public Set getRepcatDdls() {
        return this.repcatDdls;
    }
    
    public void setRepcatDdls(Set repcatDdls) {
        this.repcatDdls = repcatDdls;
    }




}


