package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * RepcatRepgroupPrivsId generated by hbm2java
 */
public class RepcatRepgroupPrivsId  implements java.io.Serializable {


     private BigDecimal userid;
     private String username;
     private String gowner;
     private String gname;
     private BigDecimal globalFlag;
     private Date created;
     private BigDecimal privilege;

    

	
    
    
   
    public BigDecimal getUserid() {
        return this.userid;
    }
    
    public void setUserid(BigDecimal userid) {
        this.userid = userid;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getGowner() {
        return this.gowner;
    }
    
    public void setGowner(String gowner) {
        this.gowner = gowner;
    }
    public String getGname() {
        return this.gname;
    }
    
    public void setGname(String gname) {
        this.gname = gname;
    }
    public BigDecimal getGlobalFlag() {
        return this.globalFlag;
    }
    
    public void setGlobalFlag(BigDecimal globalFlag) {
        this.globalFlag = globalFlag;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public BigDecimal getPrivilege() {
        return this.privilege;
    }
    
    public void setPrivilege(BigDecimal privilege) {
        this.privilege = privilege;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RepcatRepgroupPrivsId) ) return false;
		 RepcatRepgroupPrivsId castOther = ( RepcatRepgroupPrivsId ) other; 
         
		 return ( (this.getUserid()==castOther.getUserid()) || ( this.getUserid()!=null && castOther.getUserid()!=null && this.getUserid().equals(castOther.getUserid()) ) )
 && ( (this.getUsername()==castOther.getUsername()) || ( this.getUsername()!=null && castOther.getUsername()!=null && this.getUsername().equals(castOther.getUsername()) ) )
 && ( (this.getGowner()==castOther.getGowner()) || ( this.getGowner()!=null && castOther.getGowner()!=null && this.getGowner().equals(castOther.getGowner()) ) )
 && ( (this.getGname()==castOther.getGname()) || ( this.getGname()!=null && castOther.getGname()!=null && this.getGname().equals(castOther.getGname()) ) )
 && ( (this.getGlobalFlag()==castOther.getGlobalFlag()) || ( this.getGlobalFlag()!=null && castOther.getGlobalFlag()!=null && this.getGlobalFlag().equals(castOther.getGlobalFlag()) ) )
 && ( (this.getCreated()==castOther.getCreated()) || ( this.getCreated()!=null && castOther.getCreated()!=null && this.getCreated().equals(castOther.getCreated()) ) )
 && ( (this.getPrivilege()==castOther.getPrivilege()) || ( this.getPrivilege()!=null && castOther.getPrivilege()!=null && this.getPrivilege().equals(castOther.getPrivilege()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUserid() == null ? 0 : this.getUserid().hashCode() );
         result = 37 * result + ( getUsername() == null ? 0 : this.getUsername().hashCode() );
         result = 37 * result + ( getGowner() == null ? 0 : this.getGowner().hashCode() );
         result = 37 * result + ( getGname() == null ? 0 : this.getGname().hashCode() );
         result = 37 * result + ( getGlobalFlag() == null ? 0 : this.getGlobalFlag().hashCode() );
         result = 37 * result + ( getCreated() == null ? 0 : this.getCreated().hashCode() );
         result = 37 * result + ( getPrivilege() == null ? 0 : this.getPrivilege().hashCode() );
         return result;
   }   


}


