package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * RepcatDdlId generated by hbm2java
 */
public class RepcatDdlId  implements java.io.Serializable {


     private BigDecimal logId;
     private String source;
     private String role;
     private String master;
     private BigDecimal line;
     private String text;
     private BigDecimal ddlNum;

    

    
   
    public BigDecimal getLogId() {
        return this.logId;
    }
    
    public void setLogId(BigDecimal logId) {
        this.logId = logId;
    }
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public String getMaster() {
        return this.master;
    }
    
    public void setMaster(String master) {
        this.master = master;
    }
    public BigDecimal getLine() {
        return this.line;
    }
    
    public void setLine(BigDecimal line) {
        this.line = line;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public BigDecimal getDdlNum() {
        return this.ddlNum;
    }
    
    public void setDdlNum(BigDecimal ddlNum) {
        this.ddlNum = ddlNum;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RepcatDdlId) ) return false;
		 RepcatDdlId castOther = ( RepcatDdlId ) other; 
         
		 return ( (this.getLogId()==castOther.getLogId()) || ( this.getLogId()!=null && castOther.getLogId()!=null && this.getLogId().equals(castOther.getLogId()) ) )
 && ( (this.getSource()==castOther.getSource()) || ( this.getSource()!=null && castOther.getSource()!=null && this.getSource().equals(castOther.getSource()) ) )
 && ( (this.getRole()==castOther.getRole()) || ( this.getRole()!=null && castOther.getRole()!=null && this.getRole().equals(castOther.getRole()) ) )
 && ( (this.getMaster()==castOther.getMaster()) || ( this.getMaster()!=null && castOther.getMaster()!=null && this.getMaster().equals(castOther.getMaster()) ) )
 && ( (this.getLine()==castOther.getLine()) || ( this.getLine()!=null && castOther.getLine()!=null && this.getLine().equals(castOther.getLine()) ) )
 && ( (this.getText()==castOther.getText()) || ( this.getText()!=null && castOther.getText()!=null && this.getText().equals(castOther.getText()) ) )
 && ( (this.getDdlNum()==castOther.getDdlNum()) || ( this.getDdlNum()!=null && castOther.getDdlNum()!=null && this.getDdlNum().equals(castOther.getDdlNum()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLogId() == null ? 0 : this.getLogId().hashCode() );
         result = 37 * result + ( getSource() == null ? 0 : this.getSource().hashCode() );
         result = 37 * result + ( getRole() == null ? 0 : this.getRole().hashCode() );
         result = 37 * result + ( getMaster() == null ? 0 : this.getMaster().hashCode() );
         result = 37 * result + ( getLine() == null ? 0 : this.getLine().hashCode() );
         result = 37 * result + ( getText() == null ? 0 : this.getText().hashCode() );
         result = 37 * result + ( getDdlNum() == null ? 0 : this.getDdlNum().hashCode() );
         return result;
   }   


}


