package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA



/**
 * RepcatGroupedColumn generated by hbm2java
 */
public class RepcatGroupedColumn  implements java.io.Serializable {


     private RepcatGroupedColumnId id;
     private RepcatColumnGroup repcatColumnGroup;

    

    
   
    public RepcatGroupedColumnId getId() {
        return this.id;
    }
    
    public void setId(RepcatGroupedColumnId id) {
        this.id = id;
    }
    public RepcatColumnGroup getRepcatColumnGroup() {
        return this.repcatColumnGroup;
    }
    
    public void setRepcatColumnGroup(RepcatColumnGroup repcatColumnGroup) {
        this.repcatColumnGroup = repcatColumnGroup;
    }




}


