package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA



/**
 * RepcatRepcatId generated by hbm2java
 */
public class RepcatRepcatId  implements java.io.Serializable {


     private String sname;
     private String gowner;

    

    
   
    public String getSname() {
        return this.sname;
    }
    
    public void setSname(String sname) {
        this.sname = sname;
    }
    public String getGowner() {
        return this.gowner;
    }
    
    public void setGowner(String gowner) {
        this.gowner = gowner;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RepcatRepcatId) ) return false;
		 RepcatRepcatId castOther = ( RepcatRepcatId ) other; 
         
		 return ( (this.getSname()==castOther.getSname()) || ( this.getSname()!=null && castOther.getSname()!=null && this.getSname().equals(castOther.getSname()) ) )
 && ( (this.getGowner()==castOther.getGowner()) || ( this.getGowner()!=null && castOther.getGowner()!=null && this.getGowner().equals(castOther.getGowner()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSname() == null ? 0 : this.getSname().hashCode() );
         result = 37 * result + ( getGowner() == null ? 0 : this.getGowner().hashCode() );
         return result;
   }   


}


