package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * RepcatResolStatsControl generated by hbm2java
 */
public class RepcatResolStatsControl  implements java.io.Serializable {


     private RepcatResolStatsControlId id;
     private Date created;
     private BigDecimal status;
     private Date statusUpdateDate;
     private Date purgedDate;
     private Date lastPurgeStartDate;
     private Date lastPurgeEndDate;

    

	
    
    
   
    public RepcatResolStatsControlId getId() {
        return this.id;
    }
    
    public void setId(RepcatResolStatsControlId id) {
        this.id = id;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public BigDecimal getStatus() {
        return this.status;
    }
    
    public void setStatus(BigDecimal status) {
        this.status = status;
    }
    public Date getStatusUpdateDate() {
        return this.statusUpdateDate;
    }
    
    public void setStatusUpdateDate(Date statusUpdateDate) {
        this.statusUpdateDate = statusUpdateDate;
    }
    public Date getPurgedDate() {
        return this.purgedDate;
    }
    
    public void setPurgedDate(Date purgedDate) {
        this.purgedDate = purgedDate;
    }
    public Date getLastPurgeStartDate() {
        return this.lastPurgeStartDate;
    }
    
    public void setLastPurgeStartDate(Date lastPurgeStartDate) {
        this.lastPurgeStartDate = lastPurgeStartDate;
    }
    public Date getLastPurgeEndDate() {
        return this.lastPurgeEndDate;
    }
    
    public void setLastPurgeEndDate(Date lastPurgeEndDate) {
        this.lastPurgeEndDate = lastPurgeEndDate;
    }




}


