package com.xedb.data;
// Generated 20/01/2016 09:51:24 AM by Hibernate Tools 3.2.4.GA



/**
 * SqlplusProductProfile generated by hbm2java
 */
public class SqlplusProductProfile  implements java.io.Serializable {


     private SqlplusProductProfileId id;

    

    
   
    public SqlplusProductProfileId getId() {
        return this.id;
    }
    
    public void setId(SqlplusProductProfileId id) {
        this.id = id;
    }




}


